# Generated by aifn -- do not edit manually.
# Package: generate-slug v1.0.0

from typing import Any, Optional
from dataclasses import dataclass


@dataclass
class GenerateSlugInput:
    title: str  # The article or page title.
    description: Optional[str] = None  # Optional longer description to inform slug and meta generation.
    language: Optional[str] = None  # Content language hint (e.g. 'en', 'zh-CN'). Slug will always be ASCII.


@dataclass
class GenerateSlugOutput:
    meta_description: str  # SEO meta description (120-160 characters recommended).
    slug: str  # URL-safe slug using lowercase ASCII letters, numbers, and hyphens.
    tags: list[str]  # Suggested tags or keywords for the content.

