// Generated by aifn — do not edit manually.
// Package: rewrite v1.0.0

namespace Aifunc.Rewrite;

using System.Collections.Generic;

internal static class RewriteAifunc
{
	internal static readonly Dictionary<string, object?> ARTIFACT_DATA =
		new Dictionary<string, object?>
		{
			["api"] = new Dictionary<string, object?>
			{
				["description"] = "Rewrite text according to a specified style or instruction while preserving the original meaning.",
				["input"] = new Dictionary<string, object?>
				{
					["additionalProperties"] = false,
					["properties"] = new Dictionary<string, object?>
					{
						["instructions"] = new Dictionary<string, object?>
						{
							["description"] = "Additional rewriting instructions or constraints.",
							["type"] = "string",
						},
						["style"] = new Dictionary<string, object?>
						{
							["description"] = "Target style or tone (e.g. 'formal', 'casual', 'concise', 'expanded', 'academic', 'humorous').",
							["minLength"] = (double)1,
							["type"] = "string",
						},
						["text"] = new Dictionary<string, object?>
						{
							["description"] = "The original text to rewrite.",
							["minLength"] = (double)1,
							["type"] = "string",
						},
					},
					["required"] = new List<object?>
					{
						"text",
						"style",
					},
					["type"] = "object",
				},
				["name"] = "rewrite",
				["output"] = new Dictionary<string, object?>
				{
					["additionalProperties"] = false,
					["properties"] = new Dictionary<string, object?>
					{
						["rewritten"] = new Dictionary<string, object?>
						{
							["description"] = "The rewritten text.",
							["type"] = "string",
						},
					},
					["required"] = new List<object?>
					{
						"rewritten",
					},
					["type"] = "object",
				},
			},
			["artifactVersion"] = "0.1.0",
			["metadata"] = new Dictionary<string, object?>
			{
				["contentHash"] = "sha256:d730cdf6c2da955b293cb369f21c58c745d22e5f1676db19b025d70e152adcbc",
				["generatedAt"] = "2026-07-12T14:20:07Z",
				["sourcePackageVersion"] = "1.0.0",
			},
			["modelParams"] = new Dictionary<string, object?>
			{
				["rules"] = new List<object?>
				{
					new Dictionary<string, object?>
					{
						["match"] = new Dictionary<string, object?>
						{
							["pattern"] = ".*",
						},
						["params"] = new Dictionary<string, object?>
						{
							["maxTokens"] = (double)2048,
							["temperature"] = 0.7,
						},
					},
				},
				["schemaVersion"] = "0.1.0",
			},
			["package"] = new Dictionary<string, object?>
			{
				["author"] = new Dictionary<string, object?>
				{
					["name"] = "GildenEye",
				},
				["description"] = "Rewrite text in a specified style or tone, such as formal, casual, concise, or expanded.",
				["engine"] = "^0.1.0",
				["name"] = "rewrite",
				["type"] = "standalone",
				["version"] = "1.0.0",
			},
			["prompts"] = new Dictionary<string, object?>
			{
				["general"] = "# System\n\nYou are a text rewriting function. You must only return a JSON object in the following format:\n{\"rewritten\": \"<rewritten text>\"}\n\nDo not output Markdown, do not include any extra explanation, and do not add undeclared fields.\n\nRequirements:\n- Rewrite the input text according to the specified style/tone.\n- Preserve the original meaning and key information — do not add or remove facts.\n- The output language should match the input language unless the style implies otherwise.\n- Common styles include: formal, casual, concise, expanded, academic, humorous, professional, poetic, simplified.\n- If additional instructions are provided, follow them as constraints on the rewrite.\n- Produce natural, fluent text that reads as if originally written in the target style.\n\n# User\n\nOriginal text:\n{{text}}\n\nTarget style: {{style}}\n\nAdditional instructions: {{instructions}}\n",
			},
			["schemaVersion"] = "0.1.0",
		};
}
