// Generated by aifn — do not edit manually.
// Package: rewrite v1.0.0

namespace Aifunc.Rewrite;

using System.Collections.Generic;

public static class RewriteTypes
{
	public sealed class RewriteInput
	{
		/// <summary>The original text to rewrite.</summary>
		public string Text { get; }
		/// <summary>Target style or tone (e.g. 'formal', 'casual', 'concise', 'expanded', 'academic', 'humorous').</summary>
		public string Style { get; }
		/// <summary>Additional rewriting instructions or constraints.</summary>
		public string? Instructions { get; set; }

		public RewriteInput(string text, string style, string? instructions = null)
		{
			Text = text;
			Style = style;
			Instructions = instructions;
		}
	}

	public sealed class RewriteOutput
	{
		/// <summary>The rewritten text.</summary>
		public string Rewritten { get; }

		public RewriteOutput(string rewritten)
		{
			Rewritten = rewritten;
		}
	}
}
