// Generated by aifn — do not edit manually.
// Package: answer-question v1.0.0

namespace Aifunc.AnswerQuestion;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Aifunc;
using Aifunc.Engine.Csharp.V0_1_0;

/// <summary>Answer a question based on provided context or general knowledge.</summary>
public static class AnswerQuestion
{
	private static readonly object? MOCK_DATA = AnswerQuestionAifuncMock.MOCK_DATA;

	public static async Task<AnswerQuestionTypes.AnswerQuestionOutput> AnswerQuestionAsync(AIFuncConfig? config, AnswerQuestionTypes.AnswerQuestionInput input)
	{
		if (config is null)
			config = new AIFuncConfig { Mock = true, MockData = MOCK_DATA };
		else if (config.Mock && config.MockData is null)
			config = config.WithMockData(MOCK_DATA);


		var artifact = Artifact.FromMap(AnswerQuestionAifunc.ARTIFACT_DATA);
		var inputMap = InputToMap(input);
		var result = await Runtime.ExecuteAsync(artifact, inputMap, config).ConfigureAwait(false);
		return MapToOutput(result);
	}

	private static Dictionary<string, object?> InputToMap(AnswerQuestionTypes.AnswerQuestionInput input)
	{
		var m = new Dictionary<string, object?>();
		if (input.Context is not null) m["context"] = input.Context;
		if (input.Language is not null) m["language"] = input.Language;
		if (input.MaxLength is not null) m["maxLength"] = input.MaxLength;
		m["question"] = input.Question;
		return m;
	}

	private static AnswerQuestionTypes.AnswerQuestionOutput MapToOutput(Dictionary<string, object?> m)
	{
		string answer;
		if (m.TryGetValue("answer", out var _v0))
			answer = _v0 is string _s0 ? _s0 : (_v0?.ToString() ?? "");
		else
			answer = "";
		double confidence;
		if (m.TryGetValue("confidence", out var _v1))
			confidence = _v1 is IConvertible _c1 ? Convert.ToDouble(_c1) : 0.0;
		else
			confidence = 0.0;
		bool grounded;
		if (m.TryGetValue("grounded", out var _v2))
			grounded = _v2 is bool _b2 ? _b2 : false;
		else
			grounded = false;
		return new AnswerQuestionTypes.AnswerQuestionOutput(answer, confidence, grounded);
	}
}
