// Generated by aifn — do not edit manually.
// Package: generate-email v1.0.0

namespace Aifunc.GenerateEmail;

using System.Collections.Generic;

internal static class GenerateEmailAifunc
{
	internal static readonly Dictionary<string, object?> ARTIFACT_DATA =
		new Dictionary<string, object?>
		{
			["api"] = new Dictionary<string, object?>
			{
				["description"] = "Generate a complete email from a brief description of intent and context.",
				["input"] = new Dictionary<string, object?>
				{
					["additionalProperties"] = false,
					["properties"] = new Dictionary<string, object?>
					{
						["intent"] = new Dictionary<string, object?>
						{
							["description"] = "What the email should accomplish.",
							["minLength"] = (double)1,
							["type"] = "string",
						},
						["keyPoints"] = new Dictionary<string, object?>
						{
							["description"] = "Specific points or details to include in the email body.",
							["items"] = new Dictionary<string, object?>
							{
								["type"] = "string",
							},
							["type"] = "array",
						},
						["language"] = new Dictionary<string, object?>
						{
							["description"] = "Email language. Default: 'English'.",
							["type"] = "string",
						},
						["recipientName"] = new Dictionary<string, object?>
						{
							["description"] = "Name or role of the recipient, used in the greeting.",
							["type"] = "string",
						},
						["senderName"] = new Dictionary<string, object?>
						{
							["description"] = "Name of the sender, used in the sign-off.",
							["type"] = "string",
						},
						["tone"] = new Dictionary<string, object?>
						{
							["description"] = "Desired tone: 'formal', 'friendly', 'assertive'. Default: 'formal'.",
							["type"] = "string",
						},
					},
					["required"] = new List<object?>
					{
						"intent",
					},
					["type"] = "object",
				},
				["name"] = "generate-email",
				["output"] = new Dictionary<string, object?>
				{
					["additionalProperties"] = false,
					["properties"] = new Dictionary<string, object?>
					{
						["body"] = new Dictionary<string, object?>
						{
							["description"] = "Full email body including greeting and sign-off.",
							["type"] = "string",
						},
						["subject"] = new Dictionary<string, object?>
						{
							["description"] = "Suggested email subject line.",
							["type"] = "string",
						},
					},
					["required"] = new List<object?>
					{
						"subject",
						"body",
					},
					["type"] = "object",
				},
			},
			["artifactVersion"] = "0.1.0",
			["metadata"] = new Dictionary<string, object?>
			{
				["contentHash"] = "sha256:cde93eb8df15df168dc26ad673e60cbf8b4616c6b6b79c25a0ec0e0e762504f1",
				["generatedAt"] = "2026-07-12T14:20:06Z",
				["sourcePackageVersion"] = "1.0.0",
			},
			["modelParams"] = new Dictionary<string, object?>
			{
				["rules"] = new List<object?>
				{
					new Dictionary<string, object?>
					{
						["match"] = new Dictionary<string, object?>
						{
							["pattern"] = ".*",
						},
						["params"] = new Dictionary<string, object?>
						{
							["maxTokens"] = (double)2048,
							["temperature"] = 0.7,
						},
					},
				},
				["schemaVersion"] = "0.1.0",
			},
			["package"] = new Dictionary<string, object?>
			{
				["author"] = new Dictionary<string, object?>
				{
					["name"] = "GildenEye",
				},
				["description"] = "Generate a complete email from a brief description of intent and context.",
				["engine"] = "^0.1.0",
				["name"] = "generate-email",
				["type"] = "standalone",
				["version"] = "1.0.0",
			},
			["prompts"] = new Dictionary<string, object?>
			{
				["general"] = "# System\n\nYou are an email generation function. You must only return a JSON object in the following format:\n{\"subject\": \"<subject line>\", \"body\": \"<full email body>\"}\n\nDo not output Markdown, do not include any extra explanation, and do not add undeclared fields.\n\nRequirements:\n- Write a complete, professional email that accomplishes the stated intent.\n- Apply the requested tone (default: formal).\n- Use recipientName in the greeting if provided.\n- Use senderName in the sign-off if provided.\n- Incorporate all keyPoints naturally into the body.\n- Write in the requested language (default: English).\n- The subject should be concise and descriptive.\n\n# User\n\nIntent: {{intent}}\n\nTone: {{tone}}\n\nSender name: {{senderName}}\n\nRecipient name: {{recipientName}}\n\nKey points: {{keyPoints}}\n\nLanguage: {{language}}\n",
			},
			["schemaVersion"] = "0.1.0",
		};
}
