// Generated by aifn — do not edit manually.
// Package: generate-email v1.0.0

namespace Aifunc.GenerateEmail;

using System.Collections.Generic;

public static class GenerateEmailTypes
{
	public sealed class GenerateEmailInput
	{
		/// <summary>What the email should accomplish.</summary>
		public string Intent { get; }
		/// <summary>Specific points or details to include in the email body.</summary>
		public List<string>? KeyPoints { get; set; }
		/// <summary>Email language. Default: 'English'.</summary>
		public string? Language { get; set; }
		/// <summary>Name or role of the recipient, used in the greeting.</summary>
		public string? RecipientName { get; set; }
		/// <summary>Name of the sender, used in the sign-off.</summary>
		public string? SenderName { get; set; }
		/// <summary>Desired tone: 'formal', 'friendly', 'assertive'. Default: 'formal'.</summary>
		public string? Tone { get; set; }

		public GenerateEmailInput(string intent, List<string>? keyPoints = null, string? language = null, string? recipientName = null, string? senderName = null, string? tone = null)
		{
			Intent = intent;
			KeyPoints = keyPoints;
			Language = language;
			RecipientName = recipientName;
			SenderName = senderName;
			Tone = tone;
		}
	}

	public sealed class GenerateEmailOutput
	{
		/// <summary>Full email body including greeting and sign-off.</summary>
		public string Body { get; }
		/// <summary>Suggested email subject line.</summary>
		public string Subject { get; }

		public GenerateEmailOutput(string body, string subject)
		{
			Body = body;
			Subject = subject;
		}
	}
}
