// Generated by aifn — do not edit manually.
// Package: review-stream v1.0.0

namespace Aifunc.ReviewStream;

using System.Collections.Generic;

internal static class ReviewStreamAifunc
{
	internal static readonly Dictionary<string, object?> ARTIFACT_DATA =
		new Dictionary<string, object?>
		{
			["api"] = new Dictionary<string, object?>
			{
				["description"] = "Stream a structured review of code or a document, with issues and suggestions delivered incrementally. Returns plain text.",
				["injectOutputSchema"] = false,
				["input"] = new Dictionary<string, object?>
				{
					["additionalProperties"] = false,
					["properties"] = new Dictionary<string, object?>
					{
						["content"] = new Dictionary<string, object?>
						{
							["description"] = "The code or document text to review.",
							["minLength"] = (double)1,
							["type"] = "string",
						},
						["context"] = new Dictionary<string, object?>
						{
							["description"] = "Optional context about the codebase, project, or purpose to inform the review.",
							["type"] = "string",
						},
						["focus"] = new Dictionary<string, object?>
						{
							["description"] = "Review focus areas (e.g. 'correctness, security', 'style, clarity', 'performance'). If omitted, covers all areas.",
							["type"] = "string",
						},
						["language"] = new Dictionary<string, object?>
						{
							["description"] = "Programming language (when type is 'code', e.g. 'TypeScript', 'Python', 'Go'). Ignored for non-code types.",
							["type"] = "string",
						},
						["outputLanguage"] = new Dictionary<string, object?>
						{
							["description"] = "Language for the review output. If omitted, matches the language of the content or defaults to English.",
							["type"] = "string",
						},
						["severity"] = new Dictionary<string, object?>
						{
							["default"] = "all",
							["description"] = "Minimum severity level to report: 'all', 'suggestions-and-above', 'warnings-and-above', 'errors-only'. Default: 'all'.",
							["enum"] = new List<object?>
							{
								"all",
								"suggestions-and-above",
								"warnings-and-above",
								"errors-only",
							},
							["type"] = "string",
						},
						["type"] = new Dictionary<string, object?>
						{
							["default"] = "code",
							["description"] = "Content type: 'code', 'document', 'pull-request', 'essay'. Default: 'code'.",
							["enum"] = new List<object?>
							{
								"code",
								"document",
								"pull-request",
								"essay",
							},
							["type"] = "string",
						},
					},
					["required"] = new List<object?>
					{
						"content",
					},
					["type"] = "object",
				},
				["name"] = "review_stream",
				["output"] = new Dictionary<string, object?>
				{
					["description"] = "The review findings as plain text, delivered incrementally.",
					["type"] = "string",
					["x-delivery-mode"] = "stream",
				},
			},
			["artifactVersion"] = "0.1.0",
			["metadata"] = new Dictionary<string, object?>
			{
				["contentHash"] = "sha256:91ad80317086e2640a83045874c158a4419b3469ea911a1406e661d7caf5cd0f",
				["generatedAt"] = "2026-07-16T23:54:34Z",
				["sourcePackageVersion"] = "1.0.0",
			},
			["modelParams"] = new Dictionary<string, object?>
			{
				["rules"] = new List<object?>
				{
					new Dictionary<string, object?>
					{
						["match"] = new Dictionary<string, object?>
						{
							["pattern"] = ".*",
						},
						["params"] = new Dictionary<string, object?>
						{
							["maxTokens"] = (double)4096,
							["temperature"] = 0.3,
						},
					},
				},
				["schemaVersion"] = "0.1.0",
			},
			["package"] = new Dictionary<string, object?>
			{
				["author"] = new Dictionary<string, object?>
				{
					["name"] = "GildenEye",
				},
				["description"] = "Stream a structured review of code or a document, with issues and suggestions delivered incrementally. Returns plain text.",
				["engine"] = "^0.2.0",
				["engineOptions"] = new Dictionary<string, object?>
				{
					["injectOutputSchema"] = false,
				},
				["name"] = "review-stream",
				["type"] = "standalone",
				["version"] = "1.0.0",
			},
			["prompts"] = new Dictionary<string, object?>
			{
				["general"] = "# System\n\nYou are a thorough and constructive code and document reviewer. Your task is to review the provided content and deliver actionable, well-organized feedback.\n\n## Requirements\n\n- Content type: {{input.type}}\n- Programming language: {{input.language}} (applies when type is 'code')\n- Focus areas: {{input.focus}} — if not specified, cover all relevant dimensions (correctness, security, performance, style, readability, maintainability)\n- Severity filter: {{input.severity}} — only report issues at or above this level\n  - \"errors-only\": bugs, security vulnerabilities, data loss risks\n  - \"warnings-and-above\": also include likely problems and bad practices\n  - \"suggestions-and-above\": also include improvements and style issues\n  - \"all\": include all of the above plus minor nitpicks\n- Structure your review as a numbered list of findings. Each finding should state:\n  1. Severity: [Error | Warning | Suggestion | Nitpick]\n  2. Location: line number or section (if determinable)\n  3. Issue: what the problem or opportunity is\n  4. Recommendation: what to do about it\n- End with a brief overall summary (2-3 sentences).\n- Output plain text only — no Markdown formatting, no JSON, no code fences.\n- If an output language is specified, write the review in that language. Otherwise, use English.\n- Be specific and actionable. Avoid vague praise or generic advice.\n\n## Context\n\n{{input.context}}\n\n## Content to Review\n\n{{input.content}}\n\nOutput language: {{input.outputLanguage}}\n",
			},
			["schemaVersion"] = "0.1.0",
		};
}
