// Generated by aifn — do not edit manually.
// Package: review-stream v1.0.0

namespace Aifunc.ReviewStream;

using System.Collections.Generic;

public static class ReviewStreamTypes
{
	public sealed class ReviewStreamInput
	{
		/// <summary>The code or document text to review.</summary>
		public string Content { get; }
		/// <summary>Optional context about the codebase, project, or purpose to inform the review.</summary>
		public string? Context { get; set; }
		/// <summary>Review focus areas (e.g. 'correctness, security', 'style, clarity', 'performance'). If omitted, covers all areas.</summary>
		public string? Focus { get; set; }
		/// <summary>Programming language (when type is 'code', e.g. 'TypeScript', 'Python', 'Go'). Ignored for non-code types.</summary>
		public string? Language { get; set; }
		/// <summary>Language for the review output. If omitted, matches the language of the content or defaults to English.</summary>
		public string? OutputLanguage { get; set; }
		/// <summary>Minimum severity level to report: 'all', 'suggestions-and-above', 'warnings-and-above', 'errors-only'. Default: 'all'.</summary>
		public string? Severity { get; set; }
		/// <summary>Content type: 'code', 'document', 'pull-request', 'essay'. Default: 'code'.</summary>
		public string? Type { get; set; }

		public ReviewStreamInput(string content, string? context = null, string? focus = null, string? language = null, string? outputLanguage = null, string? severity = null, string? type = null)
		{
			Content = content;
			Context = context;
			Focus = focus;
			Language = language;
			OutputLanguage = outputLanguage;
			Severity = severity;
			Type = type;
		}
	}
}
