// Generated by aifn — do not edit manually.
// Package: review-stream v1.0.0

namespace Aifunc.ReviewStream;

using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading;
using Aifunc;
using Aifunc.Engine.Csharp.V0_2_0;

/// <summary>Stream a structured review of code or a document, with issues and suggestions delivered incrementally. Returns plain text.</summary>
public static class ReviewStream
{
	/// <summary>
	/// Stream a structured review of code or a document, with issues and suggestions delivered incrementally. Returns plain text.
	/// </summary>
	/// <remarks>
	/// Pass a <see cref="CancellationToken"/> to cancel the stream at any time.
	/// <code>
	/// using var cts = new CancellationTokenSource();
	/// await foreach (var token in ReviewStreamAsync(config, input, cts.Token))
	///     Console.Write(token);
	/// </code>
	/// </remarks>
	public static async IAsyncEnumerable<string> ReviewStreamAsync(
		AIFuncConfig? config,
		ReviewStreamTypes.ReviewStreamInput input,
		[EnumeratorCancellation] CancellationToken cancellationToken = default)
	{
		if (config is null)
			config = new AIFuncConfig();


		var artifact = Artifact.FromMap(ReviewStreamAifunc.ARTIFACT_DATA);
		var inputMap = InputToMap(input);
		await foreach (var token in Runtime.ExecuteStreamAsync(
			artifact, inputMap, config, cancellationToken))
		{
			yield return token;
		}
	}

	private static System.Collections.Generic.Dictionary<string, object?> InputToMap(ReviewStreamTypes.ReviewStreamInput input)
	{
		var m = new System.Collections.Generic.Dictionary<string, object?>();
		m["content"] = input.Content;
		if (input.Context is not null) m["context"] = input.Context;
		if (input.Focus is not null) m["focus"] = input.Focus;
		if (input.Language is not null) m["language"] = input.Language;
		if (input.OutputLanguage is not null) m["outputLanguage"] = input.OutputLanguage;
		if (input.Severity is not null) m["severity"] = input.Severity;
		if (input.Type is not null) m["type"] = input.Type;
		return m;
	}

}
