# Generated by aifn -- do not edit manually.
# Package: recognize-intent v1.0.0

from typing import Any, Optional
from dataclasses import dataclass


@dataclass
class RecognizeIntentInput:
    intents: list[str]  # List of candidate intents to recognize from.
    text: str  # The user message to recognize intent from.
    context: Optional[str] = None  # Optional conversation context or system description to improve recognition accuracy.


@dataclass
class RecognizeIntentOutput:
    confidence: float  # Confidence score of the top intent, between 0 and 1.
    intent: str  # The highest-confidence recognized intent.
    rankings: list[dict[str, Any]]  # All intents ranked by confidence (highest first).

