// Generated by aifn — do not edit manually.
// Package: summarize v1.0.0

namespace Aifunc.Summarize;

using System.Collections.Generic;

public static class SummarizeTypes
{
	public sealed class SummarizeInput
	{
		/// <summary>The text to summarize.</summary>
		public string Text { get; }
		/// <summary>Maximum word count for the summary. Defaults to 80.</summary>
		public int? MaxLength { get; set; }

		public SummarizeInput(string text, int? maxLength = null)
		{
			Text = text;
			MaxLength = maxLength;
		}
	}

	public sealed class SummarizeOutput
	{
		/// <summary>The generated summary.</summary>
		public string Summary { get; }
		/// <summary>Approximate word count of the summary.</summary>
		public int WordCount { get; }

		public SummarizeOutput(string summary, int wordCount)
		{
			Summary = summary;
			WordCount = wordCount;
		}
	}
}
