// Generated by aifn — do not edit manually.
// Package: summarize v1.0.0

namespace Aifunc.Summarize;

using System.Collections.Generic;

internal static class SummarizeAifunc
{
	internal static readonly Dictionary<string, object?> ARTIFACT_DATA =
		new Dictionary<string, object?>
		{
			["api"] = new Dictionary<string, object?>
			{
				["description"] = "Generate a concise summary of the input text.",
				["input"] = new Dictionary<string, object?>
				{
					["additionalProperties"] = false,
					["properties"] = new Dictionary<string, object?>
					{
						["maxLength"] = new Dictionary<string, object?>
						{
							["default"] = (double)80,
							["description"] = "Maximum word count for the summary. Defaults to 80.",
							["maximum"] = (double)300,
							["minimum"] = (double)20,
							["type"] = "integer",
						},
						["text"] = new Dictionary<string, object?>
						{
							["description"] = "The text to summarize.",
							["minLength"] = (double)1,
							["type"] = "string",
						},
					},
					["required"] = new List<object?>
					{
						"text",
					},
					["type"] = "object",
				},
				["name"] = "summarize",
				["output"] = new Dictionary<string, object?>
				{
					["additionalProperties"] = false,
					["properties"] = new Dictionary<string, object?>
					{
						["summary"] = new Dictionary<string, object?>
						{
							["description"] = "The generated summary.",
							["type"] = "string",
						},
						["wordCount"] = new Dictionary<string, object?>
						{
							["description"] = "Approximate word count of the summary.",
							["minimum"] = (double)0,
							["type"] = "integer",
						},
					},
					["required"] = new List<object?>
					{
						"summary",
						"wordCount",
					},
					["type"] = "object",
				},
			},
			["artifactVersion"] = "0.1.0",
			["metadata"] = new Dictionary<string, object?>
			{
				["contentHash"] = "sha256:2b1e7439696465851cc4e8259aaf744dcc058d61d69aba494a40e34c5df46f9c",
				["generatedAt"] = "2026-07-17T10:36:34Z",
				["sourcePackageVersion"] = "1.0.0",
			},
			["modelParams"] = new Dictionary<string, object?>
			{
				["rules"] = new List<object?>
				{
					new Dictionary<string, object?>
					{
						["match"] = new Dictionary<string, object?>
						{
							["pattern"] = ".*",
						},
						["params"] = new Dictionary<string, object?>
						{
							["maxTokens"] = (double)300,
							["temperature"] = 0.2,
						},
					},
				},
				["schemaVersion"] = "0.1.0",
			},
			["package"] = new Dictionary<string, object?>
			{
				["author"] = new Dictionary<string, object?>
				{
					["name"] = "GildenEye",
				},
				["description"] = "Generate a concise summary of the input text.",
				["engine"] = "^0.2.0",
				["name"] = "summarize",
				["type"] = "standalone",
				["version"] = "1.0.0",
			},
			["prompts"] = new Dictionary<string, object?>
			{
				["general"] = "# System\n\nYou are a strict summarization function. You must only return a JSON object that conforms to the output schema. Do not output Markdown, do not include any extra explanation, and do not add undeclared fields.\n\nRequirements:\n- The summary language must match the language of the input text — do not translate.\n- The summary should be concise, accurate, and fluent.\n- Preserve the most essential information; do not fabricate anything not present in the original.\n- If the input covers multiple points, prioritize the most important 1 to 3.\n- `summary` must not exceed the word/character count specified by `maxLength`; default to 80 if not provided.\n- `wordCount` should reflect the approximate length of the summary.\n\n# User\n\nText:\n{{text}}\n\nMaximum length:\n{{maxLength}}\n",
			},
			["schemaVersion"] = "0.1.0",
		};
}
