// Generated by aifn -- do not edit manually.
// Package: score-quality v1.0.0

import { execute } from '../_engine/typescript/v0.1.0/index';
import type { AIFuncArtifact, AIFuncConfig } from '../_engine/typescript/v0.1.0/index';
import artifact from './score-quality.aifunc';
import mockData from './score-quality.mock';
import type { ScoreQualityInput, ScoreQualityOutput } from './score-quality.types';

export type { AIFuncConfig, ScoreQualityInput, ScoreQualityOutput };

/** Evaluate text quality across multiple dimensions and return structured scores with improvement advice. */
export async function scoreQuality(config: AIFuncConfig = { mock: true }, input: ScoreQualityInput): Promise<ScoreQualityOutput> {
const _projectDefaults = {};

  const runtimeConfig: AIFuncConfig = config.mock && !config.mockData
    ? { ...config, mockData }
    : config;

  return execute<ScoreQualityOutput>(
    artifact as AIFuncArtifact,
    input as unknown as Record<string, unknown>,
    runtimeConfig,
    _projectDefaults,
  );
}
