// Generated by aifn — do not edit manually.
// Package: extract-entities v1.0.0

namespace Aifunc.ExtractEntities;

using System.Collections.Generic;

internal static class ExtractEntitiesAifuncMock
{
	internal static readonly object? MOCK_DATA =
		new Dictionary<string, object?>
		{
			["cases"] = new List<object?>
			{
				new Dictionary<string, object?>
				{
					["description"] = "Entity extraction from a news sentence.",
					["id"] = "news-sentence",
					["output"] = new Dictionary<string, object?>
					{
						["entities"] = new List<object?>
						{
							new Dictionary<string, object?>
							{
								["end"] = (double)5,
								["start"] = (double)0,
								["text"] = "Apple",
								["type"] = "organization",
							},
							new Dictionary<string, object?>
							{
								["end"] = (double)18,
								["start"] = (double)10,
								["text"] = "Tim Cook",
								["type"] = "person",
							},
							new Dictionary<string, object?>
							{
								["end"] = (double)42,
								["start"] = (double)33,
								["text"] = "Cupertino",
								["type"] = "location",
							},
							new Dictionary<string, object?>
							{
								["end"] = (double)56,
								["start"] = (double)46,
								["text"] = "March 2024",
								["type"] = "date",
							},
						},
					},
				},
			},
			["delay"] = new Dictionary<string, object?>
			{
				["maxMs"] = (double)120,
				["minMs"] = (double)30,
			},
			["random"] = new Dictionary<string, object?>
			{
				["enabled"] = false,
				["seed"] = "extract-entity",
			},
			["version"] = "1.0.0",
		};
}
