// Generated by aifn — do not edit manually.
// Package: extract-entities v1.0.0

namespace Aifunc.ExtractEntities;

using System.Collections.Generic;

public static class ExtractEntitiesTypes
{
	public sealed class ExtractEntitiesInput
	{
		/// <summary>The text to extract entities from.</summary>
		public string Text { get; }
		/// <summary>Optional filter: only extract entities of these types. If omitted, extract all recognized types.</summary>
		public List<string>? EntityTypes { get; set; }

		public ExtractEntitiesInput(string text, List<string>? entityTypes = null)
		{
			Text = text;
			EntityTypes = entityTypes;
		}
	}

	public sealed class ExtractEntitiesOutput
	{
		/// <summary>List of extracted entities.</summary>
		public List<Dictionary<string, object?>> Entities { get; }

		public ExtractEntitiesOutput(List<Dictionary<string, object?>> entities)
		{
			Entities = entities;
		}
	}
}
