// Generated by aifn — do not edit manually.
// Package: extract-entities v1.0.0

namespace Aifunc.ExtractEntities;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Aifunc;
using Aifunc.Engine.Csharp.V0_2_0;

/// <summary>Extract named entities from text, identifying their type and position.</summary>
public static class ExtractEntities
{
	private static readonly object? MOCK_DATA = ExtractEntitiesAifuncMock.MOCK_DATA;

	public static async Task<ExtractEntitiesTypes.ExtractEntitiesOutput> ExtractEntitiesAsync(AIFuncConfig? config, ExtractEntitiesTypes.ExtractEntitiesInput input)
	{
		if (config is null)
			config = new AIFuncConfig { Mock = true, MockData = MOCK_DATA };
		else if (config.Mock && config.MockData is null)
			config = config.WithMockData(MOCK_DATA);


		var artifact = Artifact.FromMap(ExtractEntitiesAifunc.ARTIFACT_DATA);
		var inputMap = InputToMap(input);
		var result = await Runtime.ExecuteAsync(artifact, inputMap, config).ConfigureAwait(false);
		return MapToOutput(result);
	}

	private static System.Collections.Generic.Dictionary<string, object?> InputToMap(ExtractEntitiesTypes.ExtractEntitiesInput input)
	{
		var m = new System.Collections.Generic.Dictionary<string, object?>();
		if (input.EntityTypes is not null) m["entityTypes"] = input.EntityTypes;
		m["text"] = input.Text;
		return m;
	}

	private static ExtractEntitiesTypes.ExtractEntitiesOutput MapToOutput(Dictionary<string, object?> m)
	{
		List<ExtractEntitiesTypes.Entity> entities;
		if (m.TryGetValue("entities", out var _v0))
			entities = (_v0 is System.Collections.IEnumerable _en0
				? _en0.Cast<object?>().Select(_item0 =>
				{
					var _d0 = _item0 as Dictionary<string, object?> ?? new Dictionary<string, object?>();
					return new ExtractEntitiesTypes.Entity((_d0.TryGetValue("text", out var _nv0_0) ? _nv0_0 is string _s0 ? _s0 : (_nv0_0?.ToString() ?? "") : ""), (_d0.TryGetValue("type", out var _nv0_1) ? _nv0_1 is string _s1 ? _s1 : (_nv0_1?.ToString() ?? "") : ""), (_d0.TryGetValue("start", out var _nv0_2) ? _nv0_2 is IConvertible _c2 ? Convert.ToInt32(_c2) : 0 : 0), (_d0.TryGetValue("end", out var _nv0_3) ? _nv0_3 is IConvertible _c3 ? Convert.ToInt32(_c3) : 0 : 0));
				}).ToList()
				: new List<ExtractEntitiesTypes.Entity>());
		else
			entities = new List<ExtractEntitiesTypes.Entity>();
		return new ExtractEntitiesTypes.ExtractEntitiesOutput(entities);
	}
}
