// Generated by aifn — do not edit manually.
// Package: extract-entities v1.0.0

namespace Aifunc.ExtractEntities;

using System.Collections.Generic;

internal static class ExtractEntitiesAifunc
{
	internal static readonly Dictionary<string, object?> ARTIFACT_DATA =
		new Dictionary<string, object?>
		{
			["api"] = new Dictionary<string, object?>
			{
				["description"] = "Extract named entities from text, identifying their type and position.",
				["input"] = new Dictionary<string, object?>
				{
					["additionalProperties"] = false,
					["properties"] = new Dictionary<string, object?>
					{
						["entityTypes"] = new Dictionary<string, object?>
						{
							["description"] = "Optional filter: only extract entities of these types. If omitted, extract all recognized types.",
							["items"] = new Dictionary<string, object?>
							{
								["minLength"] = (double)1,
								["type"] = "string",
							},
							["type"] = "array",
						},
						["text"] = new Dictionary<string, object?>
						{
							["description"] = "The text to extract entities from.",
							["minLength"] = (double)1,
							["type"] = "string",
						},
					},
					["required"] = new List<object?>
					{
						"text",
					},
					["type"] = "object",
				},
				["name"] = "extract-entities",
				["output"] = new Dictionary<string, object?>
				{
					["additionalProperties"] = false,
					["properties"] = new Dictionary<string, object?>
					{
						["entities"] = new Dictionary<string, object?>
						{
							["description"] = "List of extracted entities.",
							["items"] = new Dictionary<string, object?>
							{
								["additionalProperties"] = false,
								["properties"] = new Dictionary<string, object?>
								{
									["end"] = new Dictionary<string, object?>
									{
										["description"] = "End character offset (exclusive) in the input text.",
										["minimum"] = (double)0,
										["type"] = "integer",
									},
									["start"] = new Dictionary<string, object?>
									{
										["description"] = "Start character offset in the input text (0-based).",
										["minimum"] = (double)0,
										["type"] = "integer",
									},
									["text"] = new Dictionary<string, object?>
									{
										["description"] = "The entity text as it appears in the input.",
										["type"] = "string",
									},
									["type"] = new Dictionary<string, object?>
									{
										["description"] = "Entity type (e.g. 'person', 'location', 'organization', 'date', 'money', 'product').",
										["type"] = "string",
									},
								},
								["required"] = new List<object?>
								{
									"text",
									"type",
									"start",
									"end",
								},
								["type"] = "object",
							},
							["type"] = "array",
						},
					},
					["required"] = new List<object?>
					{
						"entities",
					},
					["type"] = "object",
				},
			},
			["artifactVersion"] = "0.1.0",
			["metadata"] = new Dictionary<string, object?>
			{
				["contentHash"] = "sha256:c4e635a44440fd8fb1ac9be0c9a102a163dc81b1df07d150c46e2e196beef37b",
				["generatedAt"] = "2026-07-12T14:20:06Z",
				["sourcePackageVersion"] = "1.0.0",
			},
			["modelParams"] = new Dictionary<string, object?>
			{
				["rules"] = new List<object?>
				{
					new Dictionary<string, object?>
					{
						["match"] = new Dictionary<string, object?>
						{
							["pattern"] = ".*",
						},
						["params"] = new Dictionary<string, object?>
						{
							["maxTokens"] = (double)1024,
							["temperature"] = (double)0,
						},
					},
				},
				["schemaVersion"] = "0.1.0",
			},
			["package"] = new Dictionary<string, object?>
			{
				["author"] = new Dictionary<string, object?>
				{
					["name"] = "GildenEye",
				},
				["description"] = "Extract named entities (people, places, organizations, dates, etc.) from text.",
				["engine"] = "^0.1.0",
				["name"] = "extract-entities",
				["type"] = "standalone",
				["version"] = "1.0.0",
			},
			["prompts"] = new Dictionary<string, object?>
			{
				["general"] = "# System\n\nYou are a named entity recognition (NER) function. You must only return a JSON object in the following format:\n{\"entities\": [{\"text\": \"<entity>\", \"type\": \"<type>\", \"start\": <int>, \"end\": <int>}, ...]}\n\nDo not output Markdown, do not include any extra explanation, and do not add undeclared fields.\n\nRequirements:\n- Extract all named entities from the input text.\n- Common entity types include: person, location, organization, date, time, money, percentage, product, event. Use lowercase type names.\n- If `entityTypes` is provided, only extract entities matching those types. Otherwise, extract all recognized entities.\n- `start` is the 0-based character offset where the entity begins in the input text.\n- `end` is the exclusive character offset where the entity ends (i.e. text[start:end] == entity text).\n- The `text` field must exactly match the substring in the input at the given offsets.\n- Do not overlap entities. If a span could match multiple types, choose the most specific one.\n- Return entities in the order they appear in the text (by `start` offset).\n\n# User\n\nText:\n{{text}}\n\nEntity types to extract: {{entityTypes}}\n",
			},
			["schemaVersion"] = "0.1.0",
		};
}
