// Generated by aifn — do not edit manually.
// Package: generate-post v1.0.0

namespace Aifunc.GeneratePost;

using System.Collections.Generic;

internal static class GeneratePostAifunc
{
	internal static readonly Dictionary<string, object?> ARTIFACT_DATA =
		new Dictionary<string, object?>
		{
			["api"] = new Dictionary<string, object?>
			{
				["description"] = "Generate a social media post or short article from a topic or brief.",
				["input"] = new Dictionary<string, object?>
				{
					["additionalProperties"] = false,
					["properties"] = new Dictionary<string, object?>
					{
						["includeHashtags"] = new Dictionary<string, object?>
						{
							["description"] = "Whether to append relevant hashtags. Default: false.",
							["type"] = "boolean",
						},
						["maxLength"] = new Dictionary<string, object?>
						{
							["description"] = "Maximum character count.",
							["maximum"] = (double)2000,
							["minimum"] = (double)10,
							["type"] = "integer",
						},
						["platform"] = new Dictionary<string, object?>
						{
							["description"] = "Target platform: 'twitter', 'linkedin', 'instagram', 'general'. Default: 'general'.",
							["type"] = "string",
						},
						["tone"] = new Dictionary<string, object?>
						{
							["description"] = "Desired tone (e.g. 'professional', 'casual', 'inspirational'). Default: 'casual'.",
							["type"] = "string",
						},
						["topic"] = new Dictionary<string, object?>
						{
							["description"] = "The subject or key idea of the post.",
							["minLength"] = (double)1,
							["type"] = "string",
						},
					},
					["required"] = new List<object?>
					{
						"topic",
					},
					["type"] = "object",
				},
				["name"] = "generate-post",
				["output"] = new Dictionary<string, object?>
				{
					["additionalProperties"] = false,
					["properties"] = new Dictionary<string, object?>
					{
						["charCount"] = new Dictionary<string, object?>
						{
							["description"] = "Character count of the generated post.",
							["type"] = "integer",
						},
						["hashtags"] = new Dictionary<string, object?>
						{
							["description"] = "Suggested hashtags (empty if includeHashtags is false).",
							["items"] = new Dictionary<string, object?>
							{
								["type"] = "string",
							},
							["type"] = "array",
						},
						["post"] = new Dictionary<string, object?>
						{
							["description"] = "The generated post content.",
							["type"] = "string",
						},
					},
					["required"] = new List<object?>
					{
						"post",
						"hashtags",
						"charCount",
					},
					["type"] = "object",
				},
			},
			["artifactVersion"] = "0.1.0",
			["metadata"] = new Dictionary<string, object?>
			{
				["contentHash"] = "sha256:19bc07226587b2060125840142f8d58cca5bc2a6c8788b284cff285e1dccf76a",
				["generatedAt"] = "2026-07-12T14:20:06Z",
				["sourcePackageVersion"] = "1.0.0",
			},
			["modelParams"] = new Dictionary<string, object?>
			{
				["rules"] = new List<object?>
				{
					new Dictionary<string, object?>
					{
						["match"] = new Dictionary<string, object?>
						{
							["pattern"] = ".*",
						},
						["params"] = new Dictionary<string, object?>
						{
							["maxTokens"] = (double)1024,
							["temperature"] = 0.7,
						},
					},
				},
				["schemaVersion"] = "0.1.0",
			},
			["package"] = new Dictionary<string, object?>
			{
				["author"] = new Dictionary<string, object?>
				{
					["name"] = "GildenEye",
				},
				["description"] = "Generate a social media post or short article from a topic or brief.",
				["engine"] = "^0.1.0",
				["name"] = "generate-post",
				["type"] = "standalone",
				["version"] = "1.0.0",
			},
			["prompts"] = new Dictionary<string, object?>
			{
				["general"] = "# System\n\nYou are a social media post generation function. You must only return a JSON object in the following format:\n{\"post\": \"<post content>\", \"hashtags\": [\"<tag1>\", \"<tag2>\"], \"charCount\": <integer>}\n\nDo not output Markdown, do not include any extra explanation, and do not add undeclared fields.\n\nRequirements:\n- Write a compelling post about the given topic.\n- Adapt length and style to the target platform (twitter: ≤280 chars, linkedin: professional medium-length, instagram: engaging with emojis ok, general: flexible).\n- Apply the requested tone. Default is casual.\n- If maxLength is provided, do not exceed it.\n- If includeHashtags is true, add 3–5 relevant hashtags in the 'hashtags' array (without # prefix). Otherwise return an empty array.\n- Set charCount to the character count of the 'post' field only (not including hashtags).\n\n# User\n\nTopic: {{topic}}\n\nPlatform: {{platform}}\n\nTone: {{tone}}\n\nMax length: {{maxLength}}\n\nInclude hashtags: {{includeHashtags}}\n",
			},
			["schemaVersion"] = "0.1.0",
		};
}
