// Generated by aifn — do not edit manually.
// Package: generate-post v1.0.0

namespace Aifunc.GeneratePost;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Aifunc;
using Aifunc.Engine.Csharp.V0_2_0;

/// <summary>Generate a social media post or short article from a topic or brief.</summary>
public static class GeneratePost
{
	private static readonly object? MOCK_DATA = GeneratePostAifuncMock.MOCK_DATA;

	public static async Task<GeneratePostTypes.GeneratePostOutput> GeneratePostAsync(AIFuncConfig? config, GeneratePostTypes.GeneratePostInput input)
	{
		if (config is null)
			config = new AIFuncConfig { Mock = true, MockData = MOCK_DATA };
		else if (config.Mock && config.MockData is null)
			config = config.WithMockData(MOCK_DATA);


		var artifact = Artifact.FromMap(GeneratePostAifunc.ARTIFACT_DATA);
		var inputMap = InputToMap(input);
		var result = await Runtime.ExecuteAsync(artifact, inputMap, config).ConfigureAwait(false);
		return MapToOutput(result);
	}

	private static System.Collections.Generic.Dictionary<string, object?> InputToMap(GeneratePostTypes.GeneratePostInput input)
	{
		var m = new System.Collections.Generic.Dictionary<string, object?>();
		if (input.IncludeHashtags is not null) m["includeHashtags"] = input.IncludeHashtags;
		if (input.MaxLength is not null) m["maxLength"] = input.MaxLength;
		if (input.Platform is not null) m["platform"] = input.Platform;
		if (input.Tone is not null) m["tone"] = input.Tone;
		m["topic"] = input.Topic;
		return m;
	}

	private static GeneratePostTypes.GeneratePostOutput MapToOutput(Dictionary<string, object?> m)
	{
		string post;
		if (m.TryGetValue("post", out var _v0))
			post = _v0 is string _s0 ? _s0 : (_v0?.ToString() ?? "");
		else
			post = "";
		List<string> hashtags;
		if (m.TryGetValue("hashtags", out var _v1))
			hashtags = _v1 is List<string> _l1 ? _l1 : new List<string>();
		else
			hashtags = new List<string>();
		int charCount;
		if (m.TryGetValue("charCount", out var _v2))
			charCount = _v2 is IConvertible _c2 ? Convert.ToInt32(_c2) : 0;
		else
			charCount = 0;
		return new GeneratePostTypes.GeneratePostOutput(post, hashtags, charCount);
	}
}
