// Generated by aifn — do not edit manually.
// Package: recognize-intent v1.0.0

namespace Aifunc.RecognizeIntent;

using System.Collections.Generic;

internal static class RecognizeIntentAifunc
{
	internal static readonly Dictionary<string, object?> ARTIFACT_DATA =
		new Dictionary<string, object?>
		{
			["api"] = new Dictionary<string, object?>
			{
				["description"] = "Recognize user intent from conversational text with confidence scores.",
				["input"] = new Dictionary<string, object?>
				{
					["additionalProperties"] = false,
					["properties"] = new Dictionary<string, object?>
					{
						["context"] = new Dictionary<string, object?>
						{
							["description"] = "Optional conversation context or system description to improve recognition accuracy.",
							["type"] = "string",
						},
						["intents"] = new Dictionary<string, object?>
						{
							["description"] = "List of candidate intents to recognize from.",
							["items"] = new Dictionary<string, object?>
							{
								["minLength"] = (double)1,
								["type"] = "string",
							},
							["minItems"] = (double)2,
							["type"] = "array",
						},
						["text"] = new Dictionary<string, object?>
						{
							["description"] = "The user message to recognize intent from.",
							["minLength"] = (double)1,
							["type"] = "string",
						},
					},
					["required"] = new List<object?>
					{
						"text",
						"intents",
					},
					["type"] = "object",
				},
				["name"] = "recognize-intent",
				["output"] = new Dictionary<string, object?>
				{
					["additionalProperties"] = false,
					["properties"] = new Dictionary<string, object?>
					{
						["confidence"] = new Dictionary<string, object?>
						{
							["description"] = "Confidence score of the top intent, between 0 and 1.",
							["maximum"] = (double)1,
							["minimum"] = (double)0,
							["type"] = "number",
						},
						["intent"] = new Dictionary<string, object?>
						{
							["description"] = "The highest-confidence recognized intent.",
							["type"] = "string",
						},
						["rankings"] = new Dictionary<string, object?>
						{
							["description"] = "All intents ranked by confidence (highest first).",
							["items"] = new Dictionary<string, object?>
							{
								["additionalProperties"] = false,
								["properties"] = new Dictionary<string, object?>
								{
									["confidence"] = new Dictionary<string, object?>
									{
										["description"] = "Confidence score between 0 and 1.",
										["maximum"] = (double)1,
										["minimum"] = (double)0,
										["type"] = "number",
									},
									["intent"] = new Dictionary<string, object?>
									{
										["description"] = "Intent label.",
										["type"] = "string",
									},
								},
								["required"] = new List<object?>
								{
									"intent",
									"confidence",
								},
								["type"] = "object",
							},
							["type"] = "array",
						},
					},
					["required"] = new List<object?>
					{
						"intent",
						"confidence",
						"rankings",
					},
					["type"] = "object",
				},
			},
			["artifactVersion"] = "0.1.0",
			["metadata"] = new Dictionary<string, object?>
			{
				["contentHash"] = "sha256:447ebba1e669ee49b44239ad85f6cae2de2eaa4ea7ed1e658c1d4e3c0f909d91",
				["generatedAt"] = "2026-07-12T14:54:47Z",
				["sourcePackageVersion"] = "1.0.0",
			},
			["modelParams"] = new Dictionary<string, object?>
			{
				["rules"] = null,
				["schemaVersion"] = "",
			},
			["package"] = new Dictionary<string, object?>
			{
				["author"] = new Dictionary<string, object?>
				{
					["name"] = "GildenEye",
				},
				["description"] = "Recognize user intent from conversational text with confidence scores (zero-shot).",
				["engine"] = "^0.1.0",
				["name"] = "recognize-intent",
				["type"] = "standalone",
				["version"] = "1.0.0",
			},
			["prompts"] = new Dictionary<string, object?>
			{
				["general"] = "# System\n\nYou are a conversational intent recognition function. You must only return a JSON object in the following format:\n{\"intent\": \"<top_intent>\", \"confidence\": <0-1>, \"rankings\": [{\"intent\": \"<label>\", \"confidence\": <0-1>}, ...]}\n\nDo not output Markdown, do not include any extra explanation, and do not add undeclared fields.\n\nRequirements:\n- Analyze the user's message to determine their underlying intent (what they want to accomplish).\n- Only use intents from the provided candidate list — never invent new ones.\n- Assign a confidence score (0 to 1) to each intent indicating how likely the user's message maps to that intent.\n- Sort `rankings` by confidence from highest to lowest.\n- The `intent` field should contain the highest-ranked intent label.\n- Focus on the user's goal and action, not the topic or sentiment.\n- If context is provided, use it to disambiguate between similar intents.\n\n# User\n\nMessage:\n{{text}}\n\nCandidate intents:\n{{intents}}\n\n{{#if context}}\nContext:\n{{context}}\n{{/if}}\n",
			},
			["schemaVersion"] = "0.1.0",
		};
}
