// Generated by aifn -- do not edit manually.
// Package: score-quality v1.0.0

package score_quality

import (
	"context"
	"fmt"

	engine "all-packages/aifunc/_engine/go/v0.1.0"
)

// AIFuncConfig controls the runtime mode and model connection.
type AIFuncConfig = engine.AIFuncConfig

// mockData contains the built-in offline test cases.
var mockData any = score_qualityMockData

// ScoreQuality Evaluate text quality across multiple dimensions and return structured scores with improvement advice.
func ScoreQuality(ctx context.Context, config *AIFuncConfig, input ScoreQualityInput) (ScoreQualityOutput, error) {
	if config == nil {
		config = &AIFuncConfig{Mock: true, MockData: mockData}
	}
	if config.Mock && config.MockData == nil {
		copy := *config
		copy.MockData = mockData
		config = &copy
	}

	artifact, err := engine.ArtifactFromMap(artifactData)
	if err != nil {
		return ScoreQualityOutput{}, fmt.Errorf("load artifact: %w", err)
	}

	inputMap := inputToMap(input)

	result, err := engine.Execute(ctx, artifact, inputMap, *config)
	if err != nil {
		return ScoreQualityOutput{}, err
	}

	return mapToOutput(result), nil
}

func inputToMap(input ScoreQualityInput) map[string]any {
	m := map[string]any{}
	if input.MaxSuggestions != nil { m["maxSuggestions"] = *input.MaxSuggestions }
	if input.Purpose != nil { m["purpose"] = *input.Purpose }
	if input.Strictness != nil { m["strictness"] = *input.Strictness }
	if input.TargetAudience != nil { m["targetAudience"] = *input.TargetAudience }
	m["text"] = input.Text
	return m
}

func mapToOutput(m map[string]any) ScoreQualityOutput {
	var out ScoreQualityOutput
	if v, ok := m["actionabilityScore"]; ok { out.ActionabilityScore = coerceInt(v) }
	if v, ok := m["clarityScore"]; ok { out.ClarityScore = coerceInt(v) }
	if v, ok := m["level"]; ok { out.Level = coerceString(v) }
	if v, ok := m["overallScore"]; ok { out.OverallScore = coerceInt(v) }
	if v, ok := m["structureScore"]; ok { out.StructureScore = coerceInt(v) }
	if v, ok := m["suggestions"]; ok { out.Suggestions = coerceSliceString(v) }
	if v, ok := m["summary"]; ok { out.Summary = coerceString(v) }
	if v, ok := m["toneScore"]; ok { out.ToneScore = coerceInt(v) }
	return out
}

func coerceInt(v any) int {
	switch n := v.(type) {
	case float64:
		return int(n)
	case int:
		return n
	case int64:
		return int(n)
	}
	return 0
}

func coerceString(v any) string {
	if s, ok := v.(string); ok { return s }
	return fmt.Sprintf("%v", v)
}

func coerceSliceString(v any) []string {
	if s, ok := v.([]string); ok { return s }
	if s, ok := v.([]any); ok {
		out := make([]string, 0, len(s))
		for _, item := range s {
			if str, ok := item.(string); ok {
				out = append(out, str)
			} else {
				out = append(out, fmt.Sprintf("%v", item))
			}
		}
		return out
	}
	return nil
}

