// Generated by aifn -- do not edit manually.
// Package: score-quality v1.0.0

package score_quality

// ScoreQualityInput holds the input parameters.
type ScoreQualityInput struct {
	// The text content to evaluate.
	Text string
	// Maximum number of improvement suggestions to return.
	MaxSuggestions *int
	// Writing purpose (e.g. 'explanation', 'marketing', 'support', 'learning').
	Purpose *string
	// Evaluation strictness from 1 (lenient) to 5 (very strict).
	Strictness *int
	// Intended readers (e.g. 'developers', 'customers', 'students', 'executives').
	TargetAudience *string
}

// ScoreQualityOutput holds the function result.
type ScoreQualityOutput struct {
	// How actionable and useful the text is, from 0 to 100.
	ActionabilityScore int
	// Clarity score from 0 to 100.
	ClarityScore int
	// Overall quality level.
	Level string
	// Overall quality score from 0 to 100.
	OverallScore int
	// Organization and logical structure score from 0 to 100.
	StructureScore int
	// Concise improvement suggestions, ordered by importance.
	Suggestions []string
	// One short sentence summarizing the evaluation.
	Summary string
	// Tone suitability score from 0 to 100.
	ToneScore int
}
