// Generated by aifn -- do not edit manually.
// Package: article-stream v1.0.0

package article_stream

import (
	"context"
	"fmt"

	engine "all-packages-stream/aifunc/_engine/go/v0.2.0"
)

// AIFuncConfig controls the runtime mode and model connection.
type AIFuncConfig = engine.AIFuncConfig

// ArticleStream Stream a full article from a title and optional outline. Returns plain text.
// ctx controls cancellation -- cancel it to stop the stream at any time.
// Returns (tokensCh, errCh): range over tokensCh, then read errCh once.
func ArticleStream(ctx context.Context, config *AIFuncConfig, input ArticleStreamInput) (<-chan string, <-chan error) {
	if config == nil {
		config = &AIFuncConfig{Mock: true}
	}

	artifact, err := engine.ArtifactFromMap(artifactData)
	if err != nil {
		tokens := make(chan string)
		errc := make(chan error, 1)
		close(tokens)
		errc <- fmt.Errorf("load artifact: %w", err)
		close(errc)
		return tokens, errc
	}

	return engine.ExecuteStream(ctx, artifact, inputToMap(input), *config)
}

func inputToMap(input ArticleStreamInput) map[string]any {
	m := map[string]any{}
	if input.Audience != nil { m["audience"] = *input.Audience }
	if input.Language != nil { m["language"] = *input.Language }
	if input.Outline != nil { m["outline"] = *input.Outline }
	if input.Style != nil { m["style"] = *input.Style }
	m["title"] = input.Title
	if input.WordCount != nil { m["wordCount"] = *input.WordCount }
	return m
}

