// Copyright 2026 GildenEye
// SPDX-License-Identifier: Apache-2.0

package golang

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"aifunc/cli/internal/types"
)

const (
	goIndent = "\t"
	filePerm = 0644
	dirPerm  = 0755
)

// Generate writes <name>_types.go, <name>_aifunc.go, and <name>.go for the
// given compiled artifact into outputDir.
// goModule is the Go module name from go.mod (e.g. "hello-aifunc"); it is used
// to build a proper module-path import for the engine instead of a relative path.
func Generate(artifact *types.CompiledArtifact, outputDir string, hasMock bool, engineVersion string, cfg types.AifuncConfig, goModule string) error {
	if err := os.MkdirAll(outputDir, dirPerm); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	pkgName := sanitizePackageName(artifact.Package.Name)
	fileBase := sanitizeFileName(artifact.Package.Name)

	relOutputDir := filepath.ToSlash(cfg.GetOutputDir())
	engineImport := goModule + "/" + relOutputDir + "/_engine/go/v" + engineVersion

	files := []struct {
		name      string
		generator func() (string, error)
	}{
		{fileBase + "_types.go", func() (string, error) { return generateTypes(artifact, pkgName) }},
		{fileBase + "_aifunc.go", func() (string, error) { return generateArtifactModule(artifact, pkgName) }},
		{fileBase + ".go", func() (string, error) {
			return generateEntry(artifact, pkgName, fileBase, hasMock, engineImport, cfg)
		}},
	}

	for _, f := range files {
		content, err := f.generator()
		if err != nil {
			return fmt.Errorf("generate %s: %w", f.name, err)
		}
		if err := os.WriteFile(filepath.Join(outputDir, f.name), []byte(content), filePerm); err != nil {
			return fmt.Errorf("write %s: %w", f.name, err)
		}
	}
	return nil
}

// generateTypes produces <name>_types.go with strongly-typed Input/Output structs.
func generateTypes(artifact *types.CompiledArtifact, pkgName string) (string, error) {
	var b strings.Builder
	writeGoHeader(&b, artifact, pkgName)

	baseName := toPascalCase(artifact.API.Name)
	inputName := baseName + "Input"
	outputName := baseName + "Output"

	inputFields := schemaToGoFields(artifact.API.Input)
	outputFields := schemaToGoFields(artifact.API.Output)

	fmt.Fprintf(&b, "// %s holds the input parameters.\n", inputName)
	fmt.Fprintf(&b, "type %s struct {\n", inputName)
	b.WriteString(inputFields)
	b.WriteString("}\n\n")

	fmt.Fprintf(&b, "// %s holds the function result.\n", outputName)
	fmt.Fprintf(&b, "type %s struct {\n", outputName)
	b.WriteString(outputFields)
	b.WriteString("}\n")

	return b.String(), nil
}

// generateArtifactModule produces <name>_aifunc.go with the artifact as a Go map literal.
func generateArtifactModule(artifact *types.CompiledArtifact, pkgName string) (string, error) {
	var b strings.Builder
	b.WriteString("// Generated by aifn -- do not edit manually.\n")
	fmt.Fprintf(&b, "// Package: %s v%s\n\n", artifact.Package.Name, artifact.Package.Version)
	fmt.Fprintf(&b, "package %s\n\n", pkgName)
	b.WriteString("var artifactData = ")
	b.WriteString(ToGoMap(artifact, 0))
	b.WriteString("\n")
	return b.String(), nil
}

// generateEntry produces <name>.go — the callable function the user imports.
func generateEntry(artifact *types.CompiledArtifact, pkgName, fileBase string, hasMock bool, engineImport string, cfg types.AifuncConfig) (string, error) {
	var b strings.Builder

	funcName := toPascalCase(artifact.API.Name)
	baseName := toPascalCase(artifact.API.Name)
	inputName := baseName + "Input"
	outputName := baseName + "Output"

	b.WriteString("// Generated by aifn -- do not edit manually.\n")
	fmt.Fprintf(&b, "// Package: %s v%s\n\n", artifact.Package.Name, artifact.Package.Version)
	fmt.Fprintf(&b, "package %s\n\n", pkgName)
	b.WriteString("import (\n\t\"context\"\n\t\"fmt\"\n\n")
	fmt.Fprintf(&b, "\tengine %q\n", engineImport)
	b.WriteString(")\n\n")

	b.WriteString("// AIFuncConfig controls the runtime mode and model connection.\n")
	b.WriteString("type AIFuncConfig = engine.AIFuncConfig\n\n")

	if hasMock {
		fmt.Fprintf(&b, "// mockData contains the built-in offline test cases.\n")
		fmt.Fprintf(&b, "var mockData any = %sMockData\n\n", fileBase)
	}

	desc := artifact.API.Description
	if desc == "" {
		desc = artifact.Package.Description
	}
	if desc != "" {
		fmt.Fprintf(&b, "// %s %s\n", funcName, desc)
	}

	fmt.Fprintf(&b, "func %s(ctx context.Context, config *AIFuncConfig, input %s) (%s, error) {\n", funcName, inputName, outputName)

	b.WriteString("\tif config == nil {\n")
	if hasMock {
		b.WriteString("\t\tconfig = &AIFuncConfig{Mock: true, MockData: mockData}\n")
	} else {
		b.WriteString("\t\tconfig = &AIFuncConfig{}\n")
	}
	b.WriteString("\t}\n")
	if hasMock {
		b.WriteString("\tif config.Mock && config.MockData == nil {\n\t\tcopy := *config\n\t\tcopy.MockData = mockData\n\t\tconfig = &copy\n\t}\n")
	}
	b.WriteString("\n")

	b.WriteString("\tartifact, err := engine.ArtifactFromMap(artifactData)\n")
	b.WriteString("\tif err != nil {\n")
	fmt.Fprintf(&b, "\t\treturn %s{}, fmt.Errorf(\"load artifact: %%w\", err)\n", outputName)
	b.WriteString("\t}\n\n")

	b.WriteString("\tinputMap := inputToMap(input)\n")

	if cfg.Timeout != nil {
		fmt.Fprintf(&b, "\tif config.Timeout == 0 { config.Timeout = %d }\n", *cfg.Timeout)
	}
	if cfg.MaxRetries != nil {
		fmt.Fprintf(&b, "\tif config.MaxRetries == 0 { config.MaxRetries = %d }\n", *cfg.MaxRetries)
	}
	b.WriteString("\n")

	b.WriteString("\tresult, err := engine.Execute(ctx, artifact, inputMap, *config)\n")
	b.WriteString("\tif err != nil {\n")
	fmt.Fprintf(&b, "\t\treturn %s{}, err\n", outputName)
	b.WriteString("\t}\n\n")

	b.WriteString("\treturn mapToOutput(result), nil\n")
	b.WriteString("}\n\n")

	// inputToMap helper — BUG FIX: slice/map optional fields must not be dereferenced
	b.WriteString("func inputToMap(input " + inputName + ") map[string]any {\n")
	b.WriteString("\tm := map[string]any{}\n")
	inputProps, _ := artifact.API.Input["properties"].(map[string]any)
	for _, camelKey := range sortedKeys(inputProps) {
		goField := toPascalCase(camelToSnake(camelKey))
		if isRequired(camelKey, artifact.API.Input) {
			fmt.Fprintf(&b, "\tm[%q] = input.%s\n", camelKey, goField)
		} else {
			propSchema, _ := inputProps[camelKey].(map[string]any)
			goType := jsonSchemaToGoType(propSchema, false)
			if isSliceOrMap(goType) {
				fmt.Fprintf(&b, "\tif input.%s != nil { m[%q] = input.%s }\n", goField, camelKey, goField)
			} else {
				fmt.Fprintf(&b, "\tif input.%s != nil { m[%q] = *input.%s }\n", goField, camelKey, goField)
			}
		}
	}
	b.WriteString("\treturn m\n}\n\n")

	// mapToOutput helper
	b.WriteString("func mapToOutput(m map[string]any) " + outputName + " {\n")
	b.WriteString("\tvar out " + outputName + "\n")
	outputProps, _ := artifact.API.Output["properties"].(map[string]any)
	for _, camelKey := range sortedKeys(outputProps) {
		goField := toPascalCase(camelToSnake(camelKey))
		propSchema, _ := outputProps[camelKey].(map[string]any)
		goType := jsonSchemaToGoType(propSchema, false)
		fmt.Fprintf(&b, "\tif v, ok := m[%q]; ok { out.%s = coerce%s(v) }\n", camelKey, goField, cleanTypeName(goType))
	}
	b.WriteString("\treturn out\n}\n\n")

	// coercion helpers
	b.WriteString(generateCoercionHelpers(outputProps))

	return b.String(), nil
}

// isSliceOrMap reports whether a Go type is a slice or map (neither is a pointer).
func isSliceOrMap(goType string) bool {
	return strings.HasPrefix(goType, "[]") || strings.HasPrefix(goType, "map[")
}

func generateCoercionHelpers(props map[string]any) string {
	seen := map[string]bool{}
	var b strings.Builder

	for _, camelKey := range sortedKeys(props) {
		propSchema, _ := props[camelKey].(map[string]any)
		goType := jsonSchemaToGoType(propSchema, false)
		typeName := cleanTypeName(goType)
		if seen[typeName] {
			continue
		}
		seen[typeName] = true

		switch {
		case goType == "string":
			b.WriteString("func coerceString(v any) string {\n\tif s, ok := v.(string); ok { return s }\n\treturn fmt.Sprintf(\"%v\", v)\n}\n\n")
		case goType == "int":
			b.WriteString("func coerceInt(v any) int {\n\tswitch n := v.(type) {\n\tcase float64:\n\t\treturn int(n)\n\tcase int:\n\t\treturn n\n\tcase int64:\n\t\treturn int(n)\n\t}\n\treturn 0\n}\n\n")
		case goType == "float64":
			b.WriteString("func coerceFloat64(v any) float64 {\n\tswitch n := v.(type) {\n\tcase float64:\n\t\treturn n\n\tcase int:\n\t\treturn float64(n)\n\t}\n\treturn 0\n}\n\n")
		case goType == "bool":
			b.WriteString("func coerceBool(v any) bool {\n\tif b, ok := v.(bool); ok { return b }\n\treturn false\n}\n\n")
		case goType == "[]any":
			b.WriteString("func coerceSliceAny(v any) []any {\n\tif a, ok := v.([]any); ok { return a }\n\treturn nil\n}\n\n")
		case goType == "[]string":
			b.WriteString("func coerceSliceString(v any) []string {\n\tif s, ok := v.([]string); ok { return s }\n\tif s, ok := v.([]any); ok {\n\t\tout := make([]string, 0, len(s))\n\t\tfor _, item := range s {\n\t\t\tif str, ok := item.(string); ok {\n\t\t\t\tout = append(out, str)\n\t\t\t} else {\n\t\t\t\tout = append(out, fmt.Sprintf(\"%v\", item))\n\t\t\t}\n\t\t}\n\t\treturn out\n\t}\n\treturn nil\n}\n\n")
		case goType == "[]map[string]any":
			b.WriteString("func coerceSliceMapStringAny(v any) []map[string]any {\n\tif s, ok := v.([]map[string]any); ok { return s }\n\tif s, ok := v.([]any); ok {\n\t\tout := make([]map[string]any, 0, len(s))\n\t\tfor _, item := range s {\n\t\t\tif m, ok := item.(map[string]any); ok {\n\t\t\t\tout = append(out, m)\n\t\t\t}\n\t\t}\n\t\treturn out\n\t}\n\treturn nil\n}\n\n")
		case goType == "map[string]any":
			b.WriteString("func coerceMapStringAny(v any) map[string]any {\n\tif m, ok := v.(map[string]any); ok { return m }\n\treturn nil\n}\n\n")
		}
	}
	return b.String()
}

func cleanTypeName(goType string) string {
	switch goType {
	case "string":
		return "String"
	case "int":
		return "Int"
	case "float64":
		return "Float64"
	case "bool":
		return "Bool"
	case "[]any":
		return "SliceAny"
	case "[]string":
		return "SliceString"
	case "[]map[string]any":
		return "SliceMapStringAny"
	case "map[string]any":
		return "MapStringAny"
	default:
		return "Any"
	}
}

// schemaToGoFields converts a JSON Schema object's properties to Go struct fields.
func schemaToGoFields(schema map[string]any) string {
	if t, _ := schema["type"].(string); t != "object" {
		return ""
	}
	props, ok := schema["properties"].(map[string]any)
	if !ok || len(props) == 0 {
		return ""
	}
	required := requiredSet(schema)
	keys := sortedKeys(props)

	var reqFields, optFields []string
	for _, key := range keys {
		val := props[key]
		prop, ok := val.(map[string]any)
		if !ok {
			continue
		}
		isReq := required[key]
		goFieldName := toPascalCase(camelToSnake(key))
		goType := jsonSchemaToGoType(prop, !isReq)
		desc, _ := prop["description"].(string)

		var line strings.Builder
		if desc != "" {
			fmt.Fprintf(&line, "%s// %s\n", goIndent, desc)
		}
		fmt.Fprintf(&line, "%s%s %s", goIndent, goFieldName, goType)
		if isReq {
			reqFields = append(reqFields, line.String())
		} else {
			optFields = append(optFields, line.String())
		}
	}

	var b strings.Builder
	for _, f := range reqFields {
		b.WriteString(f)
		b.WriteString("\n")
	}
	for _, f := range optFields {
		b.WriteString(f)
		b.WriteString("\n")
	}
	return b.String()
}

func jsonSchemaToGoType(prop map[string]any, optional bool) string {
	t, _ := prop["type"].(string)
	switch t {
	case "string":
		if optional {
			return "*string"
		}
		return "string"
	case "boolean":
		if optional {
			return "*bool"
		}
		return "bool"
	case "integer":
		if optional {
			return "*int"
		}
		return "int"
	case "number":
		if optional {
			return "*float64"
		}
		return "float64"
	case "array":
		if items, ok := prop["items"].(map[string]any); ok {
			return "[]" + jsonSchemaToGoType(items, false)
		}
		return "[]any"
	case "object":
		return "map[string]any"
	default:
		return "any"
	}
}

func requiredSet(schema map[string]any) map[string]bool {
	set := make(map[string]bool)
	arr, _ := schema["required"].([]any)
	for _, v := range arr {
		if s, ok := v.(string); ok {
			set[s] = true
		}
	}
	return set
}

func isRequired(key string, schema map[string]any) bool {
	return requiredSet(schema)[key]
}

// ToGoMap serialises any value to a Go map[string]any / []any literal string.
func ToGoMap(v any, indent int) string {
	switch val := v.(type) {
	case nil:
		return "nil"
	case bool:
		if val {
			return "true"
		}
		return "false"
	case float64:
		if val == float64(int64(val)) {
			return fmt.Sprintf("%d", int64(val))
		}
		return fmt.Sprintf("%g", val)
	case string:
		return fmt.Sprintf("%q", val)
	case []any:
		return sliceToGoLiteral(val, indent)
	case map[string]any:
		return mapToGoLiteral(val, indent)
	default:
		data, _ := json.Marshal(val)
		var parsed any
		json.Unmarshal(data, &parsed)
		return ToGoMap(parsed, indent)
	}
}

func mapToGoLiteral(m map[string]any, indent int) string {
	if len(m) == 0 {
		return "map[string]any{}"
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	prefix := strings.Repeat(goIndent, indent+1)
	var b strings.Builder
	b.WriteString("map[string]any{\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "%s%q: %s,\n", prefix, k, ToGoMap(m[k], indent+1))
	}
	b.WriteString(strings.Repeat(goIndent, indent) + "}")
	return b.String()
}

func sliceToGoLiteral(arr []any, indent int) string {
	if len(arr) == 0 {
		return "[]any{}"
	}
	prefix := strings.Repeat(goIndent, indent+1)
	var b strings.Builder
	b.WriteString("[]any{\n")
	for _, v := range arr {
		fmt.Fprintf(&b, "%s%s,\n", prefix, ToGoMap(v, indent+1))
	}
	b.WriteString(strings.Repeat(goIndent, indent) + "}")
	return b.String()
}

// ---- naming helpers ----

func writeGoHeader(b *strings.Builder, artifact *types.CompiledArtifact, pkgName string) {
	b.WriteString("// Generated by aifn -- do not edit manually.\n")
	fmt.Fprintf(b, "// Package: %s v%s\n\n", artifact.Package.Name, artifact.Package.Version)
	fmt.Fprintf(b, "package %s\n\n", pkgName)
}

func toPascalCase(s string) string {
	parts := splitIdentifier(s)
	var b strings.Builder
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + strings.ToLower(p[1:]))
	}
	return b.String()
}

func camelToSnake(s string) string {
	var result strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				result.WriteByte('_')
			}
			result.WriteRune(r + 32)
		} else if r == '-' {
			result.WriteByte('_')
		} else {
			result.WriteRune(r)
		}
	}
	return result.String()
}

func sanitizePackageName(name string) string {
	name = strings.TrimPrefix(name, "@")
	if idx := strings.LastIndex(name, "/"); idx >= 0 {
		name = name[idx+1:]
	}
	name = strings.ReplaceAll(name, "-", "_")
	return strings.ToLower(name)
}

func sanitizeFileName(name string) string {
	name = strings.TrimPrefix(name, "@")
	name = strings.ReplaceAll(name, "/", "__")
	name = strings.ReplaceAll(name, "-", "_")
	return strings.ToLower(name)
}

func splitIdentifier(s string) []string {
	s = strings.ReplaceAll(s, "-", "_")
	return strings.Split(s, "_")
}

func sortedKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
