// Generated by aifn — do not edit manually.
// Package: rewrite v1.0.0

package aifunc.rewrite;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
@SuppressWarnings("serial")
final class RewriteAifuncMock {

	private RewriteAifuncMock() {}

	static final Object MOCK_DATA =
		new java.util.LinkedHashMap<String, Object>() {{
			put("cases", new java.util.ArrayList<Object>(java.util.Arrays.asList(
				new java.util.LinkedHashMap<String, Object>() {{
					put("description", "Rewrite casual text into formal style.");
					put("id", "formal-rewrite");
					put("output", new java.util.LinkedHashMap<String, Object>() {{
						put("rewritten", "We would like to inform you that the project has been completed ahead of schedule. Please review the deliverables at your earliest convenience.");
					}});
				}}
			)));
			put("delay", new java.util.LinkedHashMap<String, Object>() {{
				put("maxMs", 120L);
				put("minMs", 30L);
			}});
			put("random", new java.util.LinkedHashMap<String, Object>() {{
				put("enabled", false);
				put("seed", "rewrite");
			}});
			put("version", "1.0.0");
		}};
}
