// Generated by aifn — do not edit manually.
// Package: rewrite v1.0.0

package aifunc.rewrite;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
@SuppressWarnings("serial")
final class RewriteAifunc {

	private RewriteAifunc() {}

	static final java.util.Map<String, Object> ARTIFACT_DATA =
		new java.util.LinkedHashMap<String, Object>() {{
			put("api", new java.util.LinkedHashMap<String, Object>() {{
				put("description", "Rewrite text according to a specified style or instruction while preserving the original meaning.");
				put("input", new java.util.LinkedHashMap<String, Object>() {{
					put("additionalProperties", false);
					put("properties", new java.util.LinkedHashMap<String, Object>() {{
						put("instructions", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Additional rewriting instructions or constraints.");
							put("type", "string");
						}});
						put("style", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Target style or tone (e.g. 'formal', 'casual', 'concise', 'expanded', 'academic', 'humorous').");
							put("minLength", 1L);
							put("type", "string");
						}});
						put("text", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "The original text to rewrite.");
							put("minLength", 1L);
							put("type", "string");
						}});
					}});
					put("required", new java.util.ArrayList<Object>(java.util.Arrays.asList(
						"text",
						"style"
					)));
					put("type", "object");
				}});
				put("name", "rewrite");
				put("output", new java.util.LinkedHashMap<String, Object>() {{
					put("additionalProperties", false);
					put("properties", new java.util.LinkedHashMap<String, Object>() {{
						put("rewritten", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "The rewritten text.");
							put("type", "string");
						}});
					}});
					put("required", new java.util.ArrayList<Object>(java.util.Arrays.asList(
						"rewritten"
					)));
					put("type", "object");
				}});
			}});
			put("artifactVersion", "0.1.0");
			put("metadata", new java.util.LinkedHashMap<String, Object>() {{
				put("contentHash", "sha256:d730cdf6c2da955b293cb369f21c58c745d22e5f1676db19b025d70e152adcbc");
				put("generatedAt", "2026-07-12T06:36:24Z");
				put("sourcePackageVersion", "1.0.0");
			}});
			put("modelParams", new java.util.LinkedHashMap<String, Object>() {{
				put("rules", new java.util.ArrayList<Object>(java.util.Arrays.asList(
					new java.util.LinkedHashMap<String, Object>() {{
						put("match", new java.util.LinkedHashMap<String, Object>() {{
							put("pattern", ".*");
						}});
						put("params", new java.util.LinkedHashMap<String, Object>() {{
							put("maxTokens", 2048L);
							put("temperature", 0.7);
						}});
					}}
				)));
				put("schemaVersion", "0.1.0");
			}});
			put("package", new java.util.LinkedHashMap<String, Object>() {{
				put("author", new java.util.LinkedHashMap<String, Object>() {{
					put("name", "GildenEye");
				}});
				put("description", "Rewrite text in a specified style or tone, such as formal, casual, concise, or expanded.");
				put("engine", "^0.1.0");
				put("name", "rewrite");
				put("type", "standalone");
				put("version", "1.0.0");
			}});
			put("prompts", new java.util.LinkedHashMap<String, Object>() {{
				put("general", "# System\n\nYou are a text rewriting function. You must only return a JSON object in the following format:\n{\"rewritten\": \"<rewritten text>\"}\n\nDo not output Markdown, do not include any extra explanation, and do not add undeclared fields.\n\nRequirements:\n- Rewrite the input text according to the specified style/tone.\n- Preserve the original meaning and key information — do not add or remove facts.\n- The output language should match the input language unless the style implies otherwise.\n- Common styles include: formal, casual, concise, expanded, academic, humorous, professional, poetic, simplified.\n- If additional instructions are provided, follow them as constraints on the rewrite.\n- Produce natural, fluent text that reads as if originally written in the target style.\n\n# User\n\nOriginal text:\n{{text}}\n\nTarget style: {{style}}\n\nAdditional instructions: {{instructions}}\n");
			}});
			put("schemaVersion", "0.1.0");
		}};
}
