# Generated by aifn -- do not edit manually.

artifact = {
    "api": {
        "description": "Classify text into user-defined categories with confidence scores.",
        "input": {
            "additionalProperties": False,
            "properties": {
                "allowMultiple": {
                    "default": False,
                    "description": "If true, the text can be assigned to multiple categories. Defaults to false.",
                    "type": "boolean",
                },
                "categories": {
                    "description": "List of candidate categories to classify into.",
                    "items": {
                        "minLength": 1,
                        "type": "string",
                    },
                    "minItems": 2,
                    "type": "array",
                },
                "text": {
                    "description": "The text to classify.",
                    "minLength": 1,
                    "type": "string",
                },
            },
            "required": [
                "text",
                "categories",
            ],
            "type": "object",
        },
        "name": "classify",
        "output": {
            "additionalProperties": False,
            "properties": {
                "classifications": {
                    "description": "Classification results sorted by confidence (highest first).",
                    "items": {
                        "additionalProperties": False,
                        "properties": {
                            "category": {
                                "description": "The category label.",
                                "type": "string",
                            },
                            "confidence": {
                                "description": "Confidence score between 0 and 1.",
                                "maximum": 1,
                                "minimum": 0,
                                "type": "number",
                            },
                        },
                        "required": [
                            "category",
                            "confidence",
                        ],
                        "type": "object",
                    },
                    "type": "array",
                },
            },
            "required": [
                "classifications",
            ],
            "type": "object",
        },
    },
    "artifactVersion": "0.1.0",
    "metadata": {
        "contentHash": "sha256:de1695d4164aab5906d66496030b77676dfb754e96971dddebf1f82a9df19b69",
        "generatedAt": "2026-07-05T03:19:40Z",
        "sourcePackageVersion": "1.0.0",
    },
    "modelParams": {
        "rules": [
            {
                "match": {
                    "pattern": ".*",
                },
                "params": {
                    "maxTokens": 400,
                    "temperature": 0.1,
                },
            },
        ],
        "schemaVersion": "0.1.0",
    },
    "package": {
        "author": {
            "name": "GildenEye",
        },
        "description": "Classify text into user-defined categories with confidence scores (zero-shot).",
        "engine": "^0.1.0",
        "name": "classify",
        "type": "standalone",
        "version": "1.0.0",
    },
    "prompts": {
        "general": "# System\n\nYou are a zero-shot text classification function. You must only return a JSON object in the following format:\n{\"classifications\": [{\"category\": \"<label>\", \"confidence\": <0-1>}, ...]}\n\nDo not output Markdown, do not include any extra explanation, and do not add undeclared fields.\n\nRequirements:\n- Classify the input text into the provided candidate categories.\n- Assign a confidence score (0 to 1) to each category indicating how well the text fits.\n- Sort `classifications` by confidence from highest to lowest.\n- If `allowMultiple` is false, only one category should have a high confidence (dominant), and the rest should sum to roughly 1.\n- If `allowMultiple` is true, each category's confidence should independently reflect how well the text fits that category (they need not sum to 1).\n- Only use categories from the provided list — never invent new ones.\n- Base classification on the text's content, meaning, and intent.\n\n# User\n\nText:\n{{text}}\n\nCategories:\n{{categories}}\n\nAllow multiple: {{allowMultiple}}\n",
    },
    "schemaVersion": "0.1.0",
}
