# Generated by aifn - do not edit manually.

mock_data = {
    "cases": [
        {
            "description": "Classify a support ticket into categories.",
            "id": "support-ticket",
            "output": {
                "classifications": [
                    {
                        "category": "billing",
                        "confidence": 0.85,
                    },
                    {
                        "category": "technical",
                        "confidence": 0.1,
                    },
                    {
                        "category": "general",
                        "confidence": 0.05,
                    },
                ],
            },
        },
    ],
    "delay": {
        "maxMs": 100,
        "minMs": 30,
    },
    "random": {
        "enabled": False,
        "seed": "text-classify",
    },
    "version": "1.0.0",
}
