// Generated by aifn -- do not edit manually.
// Package: detect-language v1.0.0

import { execute } from '../_engine/typescript/v0.1.0/index';
import type { AIFuncArtifact, AIFuncConfig } from '../_engine/typescript/v0.1.0/index';
import artifact from './detect-language.aifunc';
import mockData from './detect-language.mock';
import type { DetectLanguageInput, DetectLanguageOutput } from './detect-language.types';

export type { AIFuncConfig, DetectLanguageInput, DetectLanguageOutput };

/** Detect the language of input text, returning a language code, language name, and confidence score. */
export async function detectLanguage(config: AIFuncConfig = { mock: true }, input: DetectLanguageInput): Promise<DetectLanguageOutput> {
const _projectDefaults = {};

  const runtimeConfig: AIFuncConfig = config.mock && !config.mockData
    ? { ...config, mockData }
    : config;

  return execute<DetectLanguageOutput>(
    artifact as AIFuncArtifact,
    input as unknown as Record<string, unknown>,
    runtimeConfig,
    _projectDefaults,
  );
}
