# Generated by aifn -- do not edit manually.

artifact = {
    "api": {
        "description": "Extract named entities from text, identifying their type and position.",
        "input": {
            "additionalProperties": False,
            "properties": {
                "entityTypes": {
                    "description": "Optional filter: only extract entities of these types. If omitted, extract all recognized types.",
                    "items": {
                        "minLength": 1,
                        "type": "string",
                    },
                    "type": "array",
                },
                "text": {
                    "description": "The text to extract entities from.",
                    "minLength": 1,
                    "type": "string",
                },
            },
            "required": [
                "text",
            ],
            "type": "object",
        },
        "name": "extract-entities",
        "output": {
            "additionalProperties": False,
            "properties": {
                "entities": {
                    "description": "List of extracted entities.",
                    "items": {
                        "additionalProperties": False,
                        "properties": {
                            "end": {
                                "description": "End character offset (exclusive) in the input text.",
                                "minimum": 0,
                                "type": "integer",
                            },
                            "start": {
                                "description": "Start character offset in the input text (0-based).",
                                "minimum": 0,
                                "type": "integer",
                            },
                            "text": {
                                "description": "The entity text as it appears in the input.",
                                "type": "string",
                            },
                            "type": {
                                "description": "Entity type (e.g. 'person', 'location', 'organization', 'date', 'money', 'product').",
                                "type": "string",
                            },
                        },
                        "required": [
                            "text",
                            "type",
                            "start",
                            "end",
                        ],
                        "type": "object",
                    },
                    "type": "array",
                },
            },
            "required": [
                "entities",
            ],
            "type": "object",
        },
    },
    "artifactVersion": "0.1.0",
    "metadata": {
        "contentHash": "sha256:f302a2b25694fb3cc2cbd56901803b9e9e35e12e2339c9a64aee6e7376a9ddb5",
        "generatedAt": "2026-07-15T13:20:50Z",
        "sourcePackageVersion": "1.0.0",
    },
    "modelParams": {
        "rules": [
            {
                "match": {
                    "pattern": ".*",
                },
                "params": {
                    "maxTokens": 1024,
                    "temperature": 0,
                },
            },
        ],
        "schemaVersion": "0.1.0",
    },
    "package": {
        "author": {
            "name": "GildenEye",
        },
        "description": "Extract named entities (people, places, organizations, dates, etc.) from text.",
        "engine": "^0.2.0",
        "name": "extract-entities",
        "type": "standalone",
        "version": "1.0.0",
    },
    "prompts": {
        "general": "# System\n\nYou are a named entity recognition (NER) function. You must only return a JSON object in the following format:\n{\"entities\": [{\"text\": \"<entity>\", \"type\": \"<type>\", \"start\": <int>, \"end\": <int>}, ...]}\n\nDo not output Markdown, do not include any extra explanation, and do not add undeclared fields.\n\nRequirements:\n- Extract all named entities from the input text.\n- Common entity types include: person, location, organization, date, time, money, percentage, product, event. Use lowercase type names.\n- If `entityTypes` is provided, only extract entities matching those types. Otherwise, extract all recognized entities.\n- `start` is the 0-based character offset where the entity begins in the input text.\n- `end` is the exclusive character offset where the entity ends (i.e. text[start:end] == entity text).\n- The `text` field must exactly match the substring in the input at the given offsets.\n- Do not overlap entities. If a span could match multiple types, choose the most specific one.\n- Return entities in the order they appear in the text (by `start` offset).\n\n# User\n\nText:\n{{text}}\n\nEntity types to extract: {{entityTypes}}\n",
    },
    "schemaVersion": "0.1.0",
}
