# Generated by aifn -- do not edit manually.
# Package: extract-entities v1.0.0

from typing import Any, Optional
from dataclasses import dataclass


@dataclass
class ExtractEntitiesInput:
    text: str  # The text to extract entities from.
    entity_types: Optional[list[str]] = None  # Optional filter: only extract entities of these types. If omitted, extract all recognized types.


@dataclass
class ExtractEntitiesOutput:
    entities: list[dict[str, Any]]  # List of extracted entities.

