// Generated by aifn -- do not edit manually.
// Package: generate-reply v1.0.0

package generate_reply

import (
	"context"
	"fmt"

	engine "all-packages/aifunc/_engine/go/v0.2.0"
)

// AIFuncConfig controls the runtime mode and model connection.
type AIFuncConfig = engine.AIFuncConfig

// mockData contains the built-in offline test cases.
var mockData any = generate_replyMockData

// GenerateReply Generate a contextually appropriate reply to a message or comment.
func GenerateReply(ctx context.Context, config *AIFuncConfig, input GenerateReplyInput) (GenerateReplyOutput, error) {
	if config == nil {
		config = &AIFuncConfig{Mock: true, MockData: mockData}
	}
	if config.Mock && config.MockData == nil {
		copy := *config
		copy.MockData = mockData
		config = &copy
	}

	artifact, err := engine.ArtifactFromMap(artifactData)
	if err != nil {
		return GenerateReplyOutput{}, fmt.Errorf("load artifact: %w", err)
	}

	inputMap := inputToMap(input)

	result, err := engine.Execute(ctx, artifact, inputMap, *config)
	if err != nil {
		return GenerateReplyOutput{}, err
	}

	return mapToOutput(result), nil
}

func inputToMap(input GenerateReplyInput) map[string]any {
	m := map[string]any{}
	if input.Context != nil { m["context"] = *input.Context }
	if input.Language != nil { m["language"] = *input.Language }
	m["message"] = input.Message
	if input.Tone != nil { m["tone"] = *input.Tone }
	return m
}

func mapToOutput(m map[string]any) GenerateReplyOutput {
	var out GenerateReplyOutput
	if v, ok := m["reply"]; ok { out.Reply = coerceString(v) }
	return out
}

func coerceString(v any) string {
	if s, ok := v.(string); ok { return s }
	return fmt.Sprintf("%v", v)
}

