// Generated by aifn - do not edit manually.

package generate_reply

var generate_replyMockData any = map[string]any{
	"cases": []any{
		map[string]any{
			"description": "Generate a friendly reply to a customer message.",
			"id": "friendly-reply",
			"output": map[string]any{
				"reply": "Thanks for reaching out! I completely understand your concern and I'm happy to help sort this out for you. Let me look into it right away.",
			},
		},
	},
	"delay": map[string]any{
		"maxMs": 120,
		"minMs": 30,
	},
	"random": map[string]any{
		"enabled": false,
		"seed": "generate-reply",
	},
	"version": "1.0.0",
}
