// Generated by aifn — do not edit manually.
// Package: detect-language v1.0.0

namespace Aifunc.DetectLanguage;

using System.Collections.Generic;

public static class DetectLanguageTypes
{
	public sealed class DetectLanguageInput
	{
		/// <summary>The text whose language should be detected.</summary>
		public string Text { get; }

		public DetectLanguageInput(string text)
		{
			Text = text;
		}
	}

	public sealed class DetectLanguageOutput
	{
		/// <summary>Confidence score between 0 and 1.</summary>
		public double Confidence { get; }
		/// <summary>Detected language code (e.g. 'en', 'zh-CN', 'ja', 'fr').</summary>
		public string Language { get; }
		/// <summary>Human-readable name of the detected language (e.g. 'English', '中文', '日本語').</summary>
		public string LanguageName { get; }

		public DetectLanguageOutput(double confidence, string language, string languageName)
		{
			Confidence = confidence;
			Language = language;
			LanguageName = languageName;
		}
	}
}
