// Generated by aifn — do not edit manually.
// Package: detect-language v1.0.0

namespace Aifunc.DetectLanguage;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Aifunc;
using Aifunc.Engine.Csharp.V0_1_0;

/// <summary>Detect the language of input text, returning a language code, language name, and confidence score.</summary>
public static class DetectLanguage
{
	private static readonly object? MOCK_DATA = DetectLanguageAifuncMock.MOCK_DATA;

	public static async Task<DetectLanguageTypes.DetectLanguageOutput> DetectLanguageAsync(AIFuncConfig? config, DetectLanguageTypes.DetectLanguageInput input)
	{
		if (config is null)
			config = new AIFuncConfig { Mock = true, MockData = MOCK_DATA };
		else if (config.Mock && config.MockData is null)
			config = config.WithMockData(MOCK_DATA);


		var artifact = Artifact.FromMap(DetectLanguageAifunc.ARTIFACT_DATA);
		var inputMap = InputToMap(input);
		var result = await Runtime.ExecuteAsync(artifact, inputMap, config).ConfigureAwait(false);
		return MapToOutput(result);
	}

	private static Dictionary<string, object?> InputToMap(DetectLanguageTypes.DetectLanguageInput input)
	{
		var m = new Dictionary<string, object?>();
		m["text"] = input.Text;
		return m;
	}

	private static DetectLanguageTypes.DetectLanguageOutput MapToOutput(Dictionary<string, object?> m)
	{
		double confidence;
		if (m.TryGetValue("confidence", out var _v0))
			confidence = _v0 is IConvertible _c0 ? Convert.ToDouble(_c0) : 0.0;
		else
			confidence = 0.0;
		string language;
		if (m.TryGetValue("language", out var _v1))
			language = _v1 is string _s1 ? _s1 : (_v1?.ToString() ?? "");
		else
			language = "";
		string languageName;
		if (m.TryGetValue("languageName", out var _v2))
			languageName = _v2 is string _s2 ? _s2 : (_v2?.ToString() ?? "");
		else
			languageName = "";
		return new DetectLanguageTypes.DetectLanguageOutput(confidence, language, languageName);
	}
}
