// Generated by aifn -- do not edit manually.
// Package: chat-stream v1.0.0

package chat_stream

import (
	"context"
	"fmt"

	engine "chat-stream/aifunc/_engine/go/v0.2.0"
)

// AIFuncConfig controls the runtime mode and model connection.
type AIFuncConfig = engine.AIFuncConfig

// ChatStream Send a message and stream a plain-text reply. Optionally include context such as prior turns.
// ctx controls cancellation -- cancel it to stop the stream at any time.
// Returns (tokensCh, errCh): range over tokensCh, then read errCh once.
func ChatStream(ctx context.Context, config *AIFuncConfig, input ChatStreamInput) (<-chan string, <-chan error) {
	if config == nil {
		config = &AIFuncConfig{Mock: true}
	}

	artifact, err := engine.ArtifactFromMap(artifactData)
	if err != nil {
		tokens := make(chan string)
		errc := make(chan error, 1)
		close(tokens)
		errc <- fmt.Errorf("load artifact: %w", err)
		close(errc)
		return tokens, errc
	}

	return engine.ExecuteStream(ctx, artifact, inputToMap(input), *config)
}

func inputToMap(input ChatStreamInput) map[string]any {
	m := map[string]any{}
	if input.Context != nil { m["context"] = *input.Context }
	m["message"] = input.Message
	return m
}

