// Generated by aifn -- do not edit manually.
// Package: summarize v1.0.0

export interface SummarizeInput {
  /** Maximum word count for the summary. Defaults to 80. */
  maxLength?: number;
  /** The text to summarize. */
  text: string;
}

export interface SummarizeOutput {
  /** The generated summary. */
  summary: string;
  /** Approximate word count of the summary. */
  wordCount: number;
}
