// Generated by aifn — do not edit manually.
// Package: explain-stream v1.0.0

package aifunc.explain_stream;

import aifunc.AIFuncConfig;
import aifunc._engine.java.v0_2_0.Runtime;
import aifunc._engine.java.v0_2_0.Artifact;
import aifunc._engine.java.v0_2_0.Types.AIFuncArtifact;
import java.util.LinkedHashMap;
import java.util.Map;

/** Stream a clear explanation of a concept, code snippet, or term. Returns plain text. */
/** Generated by aifn — do not edit manually. */
public final class ExplainStream {

	private ExplainStream() {}

	/**
	 * Stream tokens from the model.
	 * Returns a {@link ExplainStreamTypes.TokenStream} — use it in a try-with-resources block;
	 * {@code break} automatically cancels the stream and frees the background thread.
	 */
	public static ExplainStreamTypes.TokenStream explainStream(AIFuncConfig config, ExplainStreamTypes.ExplainStreamInput input) {
		if (config == null) config = AIFuncConfig.builder().build();

		AIFuncArtifact artifact = Artifact.fromMap(ExplainStreamAifunc.ARTIFACT_DATA);
		Map<String, Object> inputMap = inputToMap(input);
		return new ExplainStreamTypes.TokenStream(Runtime.executeStream(artifact, inputMap, config));
	}

	private static Map<String, Object> inputToMap(ExplainStreamTypes.ExplainStreamInput input) {
		Map<String, Object> m = new LinkedHashMap<>();
		if (input.getAudience() != null) m.put("audience", input.getAudience());
		if (input.getContext() != null) m.put("context", input.getContext());
		if (input.getDepth() != null) m.put("depth", input.getDepth());
		if (input.getLanguage() != null) m.put("language", input.getLanguage());
		m.put("topic", input.getTopic());
		return m;
	}
}

