// Generated by aifn — do not edit manually.
// Package: explain-stream v1.0.0

package aifunc.explain_stream;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
@SuppressWarnings("serial")
final class ExplainStreamAifunc {

	private ExplainStreamAifunc() {}

	static final java.util.Map<String, Object> ARTIFACT_DATA =
		new java.util.LinkedHashMap<String, Object>() {{
			put("api", new java.util.LinkedHashMap<String, Object>() {{
				put("description", "Stream a clear explanation of a concept, code snippet, or term. Returns plain text.");
				put("injectOutputSchema", false);
				put("input", new java.util.LinkedHashMap<String, Object>() {{
					put("additionalProperties", false);
					put("properties", new java.util.LinkedHashMap<String, Object>() {{
						put("audience", new java.util.LinkedHashMap<String, Object>() {{
							put("default", "intermediate");
							put("description", "Target audience level (e.g. 'beginner', 'intermediate', 'expert', 'non-technical'). Default: 'intermediate'.");
							put("type", "string");
						}});
						put("context", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Optional surrounding context (e.g. the file or system the code belongs to, or the domain the term is used in).");
							put("type", "string");
						}});
						put("depth", new java.util.LinkedHashMap<String, Object>() {{
							put("default", "standard");
							put("description", "Explanation depth: 'brief' (2-3 sentences), 'standard' (1-2 paragraphs), 'detailed' (full breakdown with examples). Default: 'standard'.");
							put("enum", new java.util.ArrayList<Object>(java.util.Arrays.asList(
								"brief",
								"standard",
								"detailed"
							)));
							put("type", "string");
						}});
						put("language", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Output language. If omitted, matches the language of the topic.");
							put("type", "string");
						}});
						put("topic", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "The concept, code snippet, or term to explain.");
							put("minLength", 1L);
							put("type", "string");
						}});
					}});
					put("required", new java.util.ArrayList<Object>(java.util.Arrays.asList(
						"topic"
					)));
					put("type", "object");
				}});
				put("name", "explain_stream");
				put("output", new java.util.LinkedHashMap<String, Object>() {{
					put("description", "The explanation as plain text.");
					put("type", "string");
					put("x-delivery-mode", "stream");
				}});
			}});
			put("artifactVersion", "0.1.0");
			put("metadata", new java.util.LinkedHashMap<String, Object>() {{
				put("contentHash", "sha256:ed6ff39e99f5f11ffd5cc18e0011297ef0eb6fc147182c90cd6c4792a2ca7852");
				put("generatedAt", "2026-07-17T10:45:42Z");
				put("sourcePackageVersion", "1.0.0");
			}});
			put("modelParams", new java.util.LinkedHashMap<String, Object>() {{
				put("rules", new java.util.ArrayList<Object>(java.util.Arrays.asList(
					new java.util.LinkedHashMap<String, Object>() {{
						put("match", new java.util.LinkedHashMap<String, Object>() {{
							put("pattern", ".*");
						}});
						put("params", new java.util.LinkedHashMap<String, Object>() {{
							put("maxTokens", 2048L);
							put("temperature", 0.4);
						}});
					}}
				)));
				put("schemaVersion", "0.1.0");
			}});
			put("package", new java.util.LinkedHashMap<String, Object>() {{
				put("author", new java.util.LinkedHashMap<String, Object>() {{
					put("name", "GildenEye");
				}});
				put("description", "Stream a clear explanation of a concept, code snippet, or term. Returns plain text.");
				put("engine", "^0.2.0");
				put("engineOptions", new java.util.LinkedHashMap<String, Object>() {{
					put("injectOutputSchema", false);
				}});
				put("name", "explain-stream");
				put("type", "standalone");
				put("version", "1.0.0");
			}});
			put("prompts", new java.util.LinkedHashMap<String, Object>() {{
				put("general", "# System\n\nYou are a knowledgeable and clear technical educator. Your task is to explain a concept, code snippet, or term to the reader.\n\n## Requirements\n\n- Audience level: {{input.audience}} — calibrate your vocabulary, assumed knowledge, and use of jargon accordingly.\n- Depth: {{input.depth}}\n  - \"brief\": 2–3 sentences, just the core idea.\n  - \"standard\": 1–2 paragraphs, covering what it is, why it matters, and a brief example if helpful.\n  - \"detailed\": full breakdown — definition, how it works, why it exists, common use cases, pitfalls, and a concrete example.\n- Begin directly with the explanation. Do not restate the topic as a heading or add any preamble.\n- Output plain text only — no Markdown formatting, no JSON, no labels.\n- If a language is specified, write in that language. Otherwise, match the language of the topic input.\n- Be accurate, concise, and avoid unnecessary filler.\n\n## Input\n\nTopic: {{input.topic}}\n\nContext: {{input.context}}\n\nAudience: {{input.audience}}\n\nDepth: {{input.depth}}\n\nLanguage: {{input.language}}\n");
			}});
			put("schemaVersion", "0.1.0");
		}};
}
