// Generated by aifn — do not edit manually.
// Package: extract-json v1.0.0

namespace Aifunc.ExtractJson;

using System.Collections.Generic;

public static class ExtractJsonTypes
{
	public sealed class ExtractJsonInput
	{
		/// <summary>Schema describing the fields to extract.</summary>
		public List<Dictionary<string, object?>> Fields { get; }
		/// <summary>The natural language text to extract information from.</summary>
		public string Text { get; }

		public ExtractJsonInput(List<Dictionary<string, object?>> fields, string text)
		{
			Fields = fields;
			Text = text;
		}
	}

	public sealed class ExtractJsonOutput
	{
		/// <summary>Extracted key-value pairs matching the requested fields.</summary>
		public Dictionary<string, object?> Extracted { get; }
		/// <summary>Field names that could not be found in the text.</summary>
		public List<string> Missing { get; }

		public ExtractJsonOutput(Dictionary<string, object?> extracted, List<string> missing)
		{
			Extracted = extracted;
			Missing = missing;
		}
	}
}
