// Generated by aifn — do not edit manually.
// Package: extract-json v1.0.0

namespace Aifunc.ExtractJson;

using System.Collections.Generic;

internal static class ExtractJsonAifunc
{
	internal static readonly Dictionary<string, object?> ARTIFACT_DATA =
		new Dictionary<string, object?>
		{
			["api"] = new Dictionary<string, object?>
			{
				["description"] = "Extract structured JSON from natural language text according to a user-defined field schema.",
				["input"] = new Dictionary<string, object?>
				{
					["additionalProperties"] = false,
					["properties"] = new Dictionary<string, object?>
					{
						["fields"] = new Dictionary<string, object?>
						{
							["description"] = "Schema describing the fields to extract.",
							["items"] = new Dictionary<string, object?>
							{
								["additionalProperties"] = false,
								["properties"] = new Dictionary<string, object?>
								{
									["description"] = new Dictionary<string, object?>
									{
										["description"] = "What this field represents, to guide extraction.",
										["type"] = "string",
									},
									["name"] = new Dictionary<string, object?>
									{
										["description"] = "Field name (will be the key in the output JSON).",
										["minLength"] = (double)1,
										["type"] = "string",
									},
									["type"] = new Dictionary<string, object?>
									{
										["description"] = "Expected value type.",
										["enum"] = new List<object?>
										{
											"string",
											"number",
											"boolean",
											"array",
											"object",
										},
										["type"] = "string",
									},
								},
								["required"] = new List<object?>
								{
									"name",
									"description",
									"type",
								},
								["type"] = "object",
							},
							["minItems"] = (double)1,
							["type"] = "array",
						},
						["text"] = new Dictionary<string, object?>
						{
							["description"] = "The natural language text to extract information from.",
							["minLength"] = (double)1,
							["type"] = "string",
						},
					},
					["required"] = new List<object?>
					{
						"text",
						"fields",
					},
					["type"] = "object",
				},
				["name"] = "extract-json",
				["output"] = new Dictionary<string, object?>
				{
					["additionalProperties"] = false,
					["properties"] = new Dictionary<string, object?>
					{
						["extracted"] = new Dictionary<string, object?>
						{
							["additionalProperties"] = true,
							["description"] = "Extracted key-value pairs matching the requested fields.",
							["type"] = "object",
						},
						["missing"] = new Dictionary<string, object?>
						{
							["description"] = "Field names that could not be found in the text.",
							["items"] = new Dictionary<string, object?>
							{
								["type"] = "string",
							},
							["type"] = "array",
						},
					},
					["required"] = new List<object?>
					{
						"extracted",
						"missing",
					},
					["type"] = "object",
				},
			},
			["artifactVersion"] = "0.1.0",
			["metadata"] = new Dictionary<string, object?>
			{
				["contentHash"] = "sha256:9da2d18f5fb3a155da515c417aeb72b33f7f487601ae13723fb1d733ccda158d",
				["generatedAt"] = "2026-07-12T14:20:06Z",
				["sourcePackageVersion"] = "1.0.0",
			},
			["modelParams"] = new Dictionary<string, object?>
			{
				["rules"] = new List<object?>
				{
					new Dictionary<string, object?>
					{
						["match"] = new Dictionary<string, object?>
						{
							["pattern"] = ".*",
						},
						["params"] = new Dictionary<string, object?>
						{
							["maxTokens"] = (double)1024,
							["temperature"] = (double)0,
						},
					},
				},
				["schemaVersion"] = "0.1.0",
			},
			["package"] = new Dictionary<string, object?>
			{
				["author"] = new Dictionary<string, object?>
				{
					["name"] = "GildenEye",
				},
				["description"] = "Extract structured JSON data from natural language text based on a user-defined field schema.",
				["engine"] = "^0.1.0",
				["name"] = "extract-json",
				["type"] = "standalone",
				["version"] = "1.0.0",
			},
			["prompts"] = new Dictionary<string, object?>
			{
				["general"] = "# System\n\nYou are a structured information extraction function. You must only return a JSON object in the following format:\n{\"extracted\": {<fieldName>: <value>, ...}, \"missing\": [<fieldName>, ...]}\n\nDo not output Markdown, do not include any extra explanation, and do not add undeclared fields.\n\nRequirements:\n- Extract information from the text based on the field definitions provided.\n- Each field has a `name`, `description` (what to look for), and `type` (the expected value type).\n- Place successfully extracted values in `extracted` using the field name as key.\n- Values must match the declared type: \"string\" -> string, \"number\" -> number, \"boolean\" -> true/false, \"array\" -> JSON array, \"object\" -> JSON object.\n- If a field's value cannot be determined from the text, do NOT guess — add the field name to the `missing` array and omit it from `extracted`.\n- Do not invent information that is not present or clearly implied in the text.\n- For \"array\" fields, extract all relevant items mentioned in the text.\n- For \"number\" fields, parse numeric values (e.g. \"five years\" -> 5).\n\n# User\n\nText:\n{{text}}\n\nFields to extract:\n{{fields}}\n",
			},
			["schemaVersion"] = "0.1.0",
		};
}
