# Generated by aifn -- do not edit manually.
# Package: answer-question v1.0.0

from typing import Any, Optional
from dataclasses import dataclass


@dataclass
class AnswerQuestionInput:
    question: str  # The question to answer.
    context: Optional[str] = None  # Source text or document to base the answer on. If omitted, uses general knowledge.
    language: Optional[str] = None  # Answer language. If omitted, matches the question language.
    max_length: Optional[int] = None  # Maximum word count for the answer. Default: 100.


@dataclass
class AnswerQuestionOutput:
    answer: str  # The generated answer.
    confidence: float  # Confidence score between 0 and 1.
    grounded: bool  # True if the answer is based on the provided context, false if from general knowledge.

