// Generated by aifn — do not edit manually.
// Package: answer-stream v1.0.0

package aifunc.answer_stream;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
@SuppressWarnings("serial")
final class AnswerStreamAifunc {

	private AnswerStreamAifunc() {}

	static final java.util.Map<String, Object> ARTIFACT_DATA =
		new java.util.LinkedHashMap<String, Object>() {{
			put("api", new java.util.LinkedHashMap<String, Object>() {{
				put("description", "Stream a detailed answer to a question, optionally grounded in provided context for RAG use cases. Returns plain text.");
				put("injectOutputSchema", false);
				put("input", new java.util.LinkedHashMap<String, Object>() {{
					put("additionalProperties", false);
					put("properties", new java.util.LinkedHashMap<String, Object>() {{
						put("audience", new java.util.LinkedHashMap<String, Object>() {{
							put("default", "general");
							put("description", "Target audience (e.g. 'general', 'technical', 'expert'). Default: 'general'.");
							put("type", "string");
						}});
						put("context", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Optional source text, documents, or retrieved passages to ground the answer in. If provided, the answer must be based on this context.");
							put("type", "string");
						}});
						put("depth", new java.util.LinkedHashMap<String, Object>() {{
							put("default", "detailed");
							put("description", "Answer depth: 'concise' (1-2 paragraphs), 'detailed' (thorough explanation with examples). Default: 'detailed'.");
							put("enum", new java.util.ArrayList<Object>(java.util.Arrays.asList(
								"concise",
								"detailed"
							)));
							put("type", "string");
						}});
						put("language", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Answer language. If omitted, matches the language of the question.");
							put("type", "string");
						}});
						put("question", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "The question to answer.");
							put("minLength", 1L);
							put("type", "string");
						}});
					}});
					put("required", new java.util.ArrayList<Object>(java.util.Arrays.asList(
						"question"
					)));
					put("type", "object");
				}});
				put("name", "answer_stream");
				put("output", new java.util.LinkedHashMap<String, Object>() {{
					put("description", "The answer as plain text.");
					put("type", "string");
					put("x-delivery-mode", "stream");
				}});
			}});
			put("artifactVersion", "0.1.0");
			put("metadata", new java.util.LinkedHashMap<String, Object>() {{
				put("contentHash", "sha256:cc859b61013ba12f0b9533bd3cd3207eacafb98754fcf7dfbe18c03957554633");
				put("generatedAt", "2026-07-19T12:17:24Z");
				put("sourcePackageVersion", "1.0.0");
			}});
			put("modelParams", new java.util.LinkedHashMap<String, Object>() {{
				put("rules", new java.util.ArrayList<Object>(java.util.Arrays.asList(
					new java.util.LinkedHashMap<String, Object>() {{
						put("match", new java.util.LinkedHashMap<String, Object>() {{
							put("pattern", ".*");
						}});
						put("params", new java.util.LinkedHashMap<String, Object>() {{
							put("maxTokens", 4096L);
							put("temperature", 0.3);
						}});
					}}
				)));
				put("schemaVersion", "0.1.0");
			}});
			put("package", new java.util.LinkedHashMap<String, Object>() {{
				put("author", new java.util.LinkedHashMap<String, Object>() {{
					put("name", "GildenEye");
				}});
				put("description", "Stream a detailed answer to a question, optionally grounded in provided context for RAG use cases. Returns plain text.");
				put("engine", "^0.2.0");
				put("engineOptions", new java.util.LinkedHashMap<String, Object>() {{
					put("injectOutputSchema", false);
				}});
				put("name", "answer-stream");
				put("type", "standalone");
				put("version", "1.0.0");
			}});
			put("prompts", new java.util.LinkedHashMap<String, Object>() {{
				put("general", "# System\n\nYou are a knowledgeable and precise question-answering assistant. Your task is to answer the given question accurately and helpfully.\n\n## Requirements\n\n- Audience: {{input.audience}} — calibrate depth, vocabulary, and assumed knowledge accordingly.\n- Depth: {{input.depth}}\n  - \"concise\": answer in 1-2 focused paragraphs, covering just the key points.\n  - \"detailed\": provide a thorough answer with explanation, reasoning, and examples where helpful.\n- If context is provided, base your answer strictly on that context. Do not introduce information not present in it. If the context does not contain enough information to answer, say so clearly.\n- If no context is provided, answer from general knowledge.\n- Begin directly with the answer. Do not restate the question or add preamble.\n- Output plain text only — no Markdown formatting, no JSON, no labels.\n- If a language is specified, answer in that language. Otherwise, match the language of the question.\n- Be accurate, direct, and avoid unnecessary filler or hedging.\n\n## Context (source documents)\n\n{{input.context}}\n\n## Question\n\n{{input.question}}\n\nAudience: {{input.audience}}\n\nLanguage: {{input.language}}\n");
			}});
			put("schemaVersion", "0.1.0");
		}};
}
