// Generated by aifn -- do not edit manually.
// Package: recognize-intent v1.0.0

package recognize_intent

import (
	"context"
	"fmt"

	engine "customer-support/aifunc/_engine/go/v0.2.0"
)

// AIFuncConfig controls the runtime mode and model connection.
type AIFuncConfig = engine.AIFuncConfig

// mockData contains the built-in offline test cases.
var mockData any = recognize_intentMockData

// RecognizeIntent Recognize user intent from conversational text with confidence scores.
func RecognizeIntent(ctx context.Context, config *AIFuncConfig, input RecognizeIntentInput) (RecognizeIntentOutput, error) {
	if config == nil {
		config = &AIFuncConfig{Mock: true, MockData: mockData}
	}
	if config.Mock && config.MockData == nil {
		copy := *config
		copy.MockData = mockData
		config = &copy
	}

	artifact, err := engine.ArtifactFromMap(artifactData)
	if err != nil {
		return RecognizeIntentOutput{}, fmt.Errorf("load artifact: %w", err)
	}

	inputMap := inputToMap(input)

	result, err := engine.Execute(ctx, artifact, inputMap, *config)
	if err != nil {
		return RecognizeIntentOutput{}, err
	}

	return mapToOutput(result), nil
}

func inputToMap(input RecognizeIntentInput) map[string]any {
	m := map[string]any{}
	if input.Context != nil { m["context"] = *input.Context }
	m["intents"] = input.Intents
	m["text"] = input.Text
	return m
}

func mapToOutput(m map[string]any) RecognizeIntentOutput {
	var out RecognizeIntentOutput
	if v, ok := m["confidence"]; ok { out.Confidence = coerceFloat64(v) }
	if v, ok := m["intent"]; ok { out.Intent = coerceString(v) }
	if v, ok := m["rankings"]; ok { out.Rankings = coerceSliceMapStringAny(v) }
	return out
}

func coerceFloat64(v any) float64 {
	switch n := v.(type) {
	case float64:
		return n
	case int:
		return float64(n)
	}
	return 0
}

func coerceString(v any) string {
	if s, ok := v.(string); ok { return s }
	return fmt.Sprintf("%v", v)
}

func coerceSliceMapStringAny(v any) []map[string]any {
	if s, ok := v.([]map[string]any); ok { return s }
	if s, ok := v.([]any); ok {
		out := make([]map[string]any, 0, len(s))
		for _, item := range s {
			if m, ok := item.(map[string]any); ok {
				out = append(out, m)
			}
		}
		return out
	}
	return nil
}

