# Generated by aifn - do not edit manually.

mock_data = {
    "cases": [
        {
            "description": "Keyword extraction from a tech article.",
            "id": "tech-article",
            "output": {
                "keywords": [
                    {
                        "relevance": 0.95,
                        "word": "machine learning",
                    },
                    {
                        "relevance": 0.88,
                        "word": "neural network",
                    },
                    {
                        "relevance": 0.82,
                        "word": "deep learning",
                    },
                    {
                        "relevance": 0.75,
                        "word": "training data",
                    },
                    {
                        "relevance": 0.7,
                        "word": "model accuracy",
                    },
                ],
            },
        },
    ],
    "delay": {
        "maxMs": 100,
        "minMs": 30,
    },
    "random": {
        "enabled": False,
        "seed": "keyword-extract",
    },
    "version": "1.0.0",
}
