// Generated by aifn — do not edit manually.
// Package: recognize-intent v1.0.0

package aifunc.recognize_intent;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
@SuppressWarnings("serial")
final class RecognizeIntentAifunc {

	private RecognizeIntentAifunc() {}

	static final java.util.Map<String, Object> ARTIFACT_DATA =
		new java.util.LinkedHashMap<String, Object>() {{
			put("api", new java.util.LinkedHashMap<String, Object>() {{
				put("description", "Recognize user intent from conversational text with confidence scores.");
				put("input", new java.util.LinkedHashMap<String, Object>() {{
					put("additionalProperties", false);
					put("properties", new java.util.LinkedHashMap<String, Object>() {{
						put("context", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Optional conversation context or system description to improve recognition accuracy.");
							put("type", "string");
						}});
						put("intents", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "List of candidate intents to recognize from.");
							put("items", new java.util.LinkedHashMap<String, Object>() {{
								put("minLength", 1L);
								put("type", "string");
							}});
							put("minItems", 2L);
							put("type", "array");
						}});
						put("text", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "The user message to recognize intent from.");
							put("minLength", 1L);
							put("type", "string");
						}});
					}});
					put("required", new java.util.ArrayList<Object>(java.util.Arrays.asList(
						"text",
						"intents"
					)));
					put("type", "object");
				}});
				put("name", "recognize-intent");
				put("output", new java.util.LinkedHashMap<String, Object>() {{
					put("additionalProperties", false);
					put("properties", new java.util.LinkedHashMap<String, Object>() {{
						put("confidence", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Confidence score of the top intent, between 0 and 1.");
							put("maximum", 1L);
							put("minimum", 0L);
							put("type", "number");
						}});
						put("intent", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "The highest-confidence recognized intent.");
							put("type", "string");
						}});
						put("rankings", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "All intents ranked by confidence (highest first).");
							put("items", new java.util.LinkedHashMap<String, Object>() {{
								put("additionalProperties", false);
								put("properties", new java.util.LinkedHashMap<String, Object>() {{
									put("confidence", new java.util.LinkedHashMap<String, Object>() {{
										put("description", "Confidence score between 0 and 1.");
										put("maximum", 1L);
										put("minimum", 0L);
										put("type", "number");
									}});
									put("intent", new java.util.LinkedHashMap<String, Object>() {{
										put("description", "Intent label.");
										put("type", "string");
									}});
								}});
								put("required", new java.util.ArrayList<Object>(java.util.Arrays.asList(
									"intent",
									"confidence"
								)));
								put("type", "object");
							}});
							put("type", "array");
						}});
					}});
					put("required", new java.util.ArrayList<Object>(java.util.Arrays.asList(
						"intent",
						"confidence",
						"rankings"
					)));
					put("type", "object");
				}});
			}});
			put("artifactVersion", "0.1.0");
			put("metadata", new java.util.LinkedHashMap<String, Object>() {{
				put("contentHash", "sha256:447ebba1e669ee49b44239ad85f6cae2de2eaa4ea7ed1e658c1d4e3c0f909d91");
				put("generatedAt", "2026-07-12T06:55:26Z");
				put("sourcePackageVersion", "1.0.0");
			}});
			put("modelParams", new java.util.LinkedHashMap<String, Object>() {{
				put("rules", null);
				put("schemaVersion", "");
			}});
			put("package", new java.util.LinkedHashMap<String, Object>() {{
				put("author", new java.util.LinkedHashMap<String, Object>() {{
					put("name", "GildenEye");
				}});
				put("description", "Recognize user intent from conversational text with confidence scores (zero-shot).");
				put("engine", "^0.1.0");
				put("name", "recognize-intent");
				put("type", "standalone");
				put("version", "1.0.0");
			}});
			put("prompts", new java.util.LinkedHashMap<String, Object>() {{
				put("general", "# System\n\nYou are a conversational intent recognition function. You must only return a JSON object in the following format:\n{\"intent\": \"<top_intent>\", \"confidence\": <0-1>, \"rankings\": [{\"intent\": \"<label>\", \"confidence\": <0-1>}, ...]}\n\nDo not output Markdown, do not include any extra explanation, and do not add undeclared fields.\n\nRequirements:\n- Analyze the user's message to determine their underlying intent (what they want to accomplish).\n- Only use intents from the provided candidate list — never invent new ones.\n- Assign a confidence score (0 to 1) to each intent indicating how likely the user's message maps to that intent.\n- Sort `rankings` by confidence from highest to lowest.\n- The `intent` field should contain the highest-ranked intent label.\n- Focus on the user's goal and action, not the topic or sentiment.\n- If context is provided, use it to disambiguate between similar intents.\n\n# User\n\nMessage:\n{{text}}\n\nCandidate intents:\n{{intents}}\n\n{{#if context}}\nContext:\n{{context}}\n{{/if}}\n");
			}});
			put("schemaVersion", "0.1.0");
		}};
}
