# Generated by aifn -- do not edit manually.

artifact = {
    "api": {
        "description": "Extract structured JSON from natural language text according to a user-defined field schema.",
        "input": {
            "additionalProperties": False,
            "properties": {
                "fields": {
                    "description": "Schema describing the fields to extract.",
                    "items": {
                        "additionalProperties": False,
                        "properties": {
                            "description": {
                                "description": "What this field represents, to guide extraction.",
                                "type": "string",
                            },
                            "name": {
                                "description": "Field name (will be the key in the output JSON).",
                                "minLength": 1,
                                "type": "string",
                            },
                            "type": {
                                "description": "Expected value type.",
                                "enum": [
                                    "string",
                                    "number",
                                    "boolean",
                                    "array",
                                    "object",
                                ],
                                "type": "string",
                            },
                        },
                        "required": [
                            "name",
                            "description",
                            "type",
                        ],
                        "type": "object",
                    },
                    "minItems": 1,
                    "type": "array",
                },
                "text": {
                    "description": "The natural language text to extract information from.",
                    "minLength": 1,
                    "type": "string",
                },
            },
            "required": [
                "text",
                "fields",
            ],
            "type": "object",
        },
        "name": "extract-json",
        "output": {
            "additionalProperties": False,
            "properties": {
                "extracted": {
                    "additionalProperties": True,
                    "description": "Extracted key-value pairs matching the requested fields.",
                    "type": "object",
                },
                "missing": {
                    "description": "Field names that could not be found in the text.",
                    "items": {
                        "type": "string",
                    },
                    "type": "array",
                },
            },
            "required": [
                "extracted",
                "missing",
            ],
            "type": "object",
        },
    },
    "artifactVersion": "0.1.0",
    "metadata": {
        "contentHash": "sha256:9da2d18f5fb3a155da515c417aeb72b33f7f487601ae13723fb1d733ccda158d",
        "generatedAt": "2026-07-05T03:18:13Z",
        "sourcePackageVersion": "1.0.0",
    },
    "modelParams": {
        "rules": [
            {
                "match": {
                    "pattern": ".*",
                },
                "params": {
                    "maxTokens": 1024,
                    "temperature": 0,
                },
            },
        ],
        "schemaVersion": "0.1.0",
    },
    "package": {
        "author": {
            "name": "GildenEye",
        },
        "description": "Extract structured JSON data from natural language text based on a user-defined field schema.",
        "engine": "^0.1.0",
        "name": "extract-json",
        "type": "standalone",
        "version": "1.0.0",
    },
    "prompts": {
        "general": "# System\n\nYou are a structured information extraction function. You must only return a JSON object in the following format:\n{\"extracted\": {<fieldName>: <value>, ...}, \"missing\": [<fieldName>, ...]}\n\nDo not output Markdown, do not include any extra explanation, and do not add undeclared fields.\n\nRequirements:\n- Extract information from the text based on the field definitions provided.\n- Each field has a `name`, `description` (what to look for), and `type` (the expected value type).\n- Place successfully extracted values in `extracted` using the field name as key.\n- Values must match the declared type: \"string\" -> string, \"number\" -> number, \"boolean\" -> true/false, \"array\" -> JSON array, \"object\" -> JSON object.\n- If a field's value cannot be determined from the text, do NOT guess — add the field name to the `missing` array and omit it from `extracted`.\n- Do not invent information that is not present or clearly implied in the text.\n- For \"array\" fields, extract all relevant items mentioned in the text.\n- For \"number\" fields, parse numeric values (e.g. \"five years\" -> 5).\n\n# User\n\nText:\n{{text}}\n\nFields to extract:\n{{fields}}\n",
    },
    "schemaVersion": "0.1.0",
}
