# Generated by aifn - do not edit manually.

mock_data = {
    "cases": [
        {
            "description": "Extract structured info from a resume snippet.",
            "id": "resume-extraction",
            "output": {
                "extracted": {
                    "email": "zhangwei@example.com",
                    "name": "Zhang Wei",
                    "skills": [
                        "Python",
                        "Machine Learning",
                        "SQL",
                    ],
                    "yearsOfExperience": 5,
                },
                "missing": [],
            },
        },
    ],
    "delay": {
        "maxMs": 150,
        "minMs": 30,
    },
    "random": {
        "enabled": False,
        "seed": "json-extract",
    },
    "version": "1.0.0",
}
