// Generated by aifn -- do not edit manually.
// Package: chat-stream v1.0.0

export interface ChatStreamInput {
  /** Reply language. If omitted, matches the language of the last user message. */
  language?: string;
  /** Conversation history. Each item has a 'role' ('user' or 'assistant') and 'content' (string). */
  messages: {
    content: string;
    role: "user" | "assistant";
  }[];
  /** Optional system-level instruction that sets the assistant's persona, role, or constraints. */
  systemPrompt?: string;
}

export type ChatStreamOutput = string;
