// Generated by aifn — do not edit manually.
// Package: analyze-sentiment v1.0.0

package aifunc.analyze_sentiment;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
public final class AnalyzeSentimentTypes {

	private AnalyzeSentimentTypes() {}

	public static final class AnalyzeSentimentInput {
		/** The text to analyze sentiment for. */
		private final String text;
		/** Candidate sentiment labels. Defaults to ["positive", "negative", "neutral"]. */
		private java.util.List<String> labels;
		/** Return only the top K labels by score. If omitted, return all. */
		private Integer topK;

		public AnalyzeSentimentInput(String text, java.util.List<String> labels, Integer topK) {
			this.text = text;
			this.labels = labels;
			this.topK = topK;
		}

		public String getText() { return text; }
		public java.util.List<String> getLabels() { return labels; }
		public void setLabels(java.util.List<String> v) { this.labels = v; }
		public Integer getTopK() { return topK; }
		public void setTopK(Integer v) { this.topK = v; }
	}

	public static final class AnalyzeSentimentOutput {
		/** Confidence score of the top label, between 0 and 1. */
		private final Double confidence;
		/** The highest-scoring sentiment label. */
		private final String label;
		/** All labels ranked by score (highest first), limited by topK. */
		private final java.util.List<java.util.Map<String, Object>> rankings;

		public AnalyzeSentimentOutput(Double confidence, String label, java.util.List<java.util.Map<String, Object>> rankings) {
			this.confidence = confidence;
			this.label = label;
			this.rankings = rankings;
		}

		public Double getConfidence() { return confidence; }
		public String getLabel() { return label; }
		public java.util.List<java.util.Map<String, Object>> getRankings() { return rankings; }
	}
}
