# Generated by aifn -- do not edit manually.
# Package: generate-title v1.0.0

from typing import Any, Optional, Union
from dataclasses import asdict, replace

from .._engine.python.v0_1_0 import execute, AIFuncConfig, AIFuncArtifact
from .generate_title_aifunc import artifact
from .generate_title_mock import mock_data
from .generate_title_types import GenerateTitleInput, GenerateTitleOutput

__all__ = ["AIFuncConfig", "GenerateTitleInput", "GenerateTitleOutput", "generate_title"]


async def generate_title(config: Optional[AIFuncConfig], input_data: Union[GenerateTitleInput, dict[str, Any]]) -> GenerateTitleOutput:
    """Generate title or headline candidates for a piece of content."""
    if config is None:
        config = AIFuncConfig(mock=True, mock_data=mock_data)
    elif config.mock and config.mock_data is None:
        config = replace(config, mock_data=mock_data)

    _artifact = AIFuncArtifact.from_dict(artifact)
    if isinstance(input_data, dict):
        _input = input_data
    else:
        _input = _to_camel_dict(asdict(input_data))
    result = await execute(_artifact, _input, config)
    return GenerateTitleOutput(**_to_snake_dict(result))


def _to_camel(name: str) -> str:
    parts = name.split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def _to_snake(name: str) -> str:
    result = []
    for ch in name:
        if ch.isupper() and result:
            result.append("_")
        result.append(ch.lower())
    return "".join(result)


def _to_camel_dict(d: dict) -> dict:
    return {_to_camel(k): v for k, v in d.items() if v is not None}


def _to_snake_dict(d: dict) -> dict:
    return {_to_snake(k): v for k, v in d.items()}
