# Generated by aifn -- do not edit manually.
# Package: generate-title v1.0.0

from typing import Any, Optional
from dataclasses import dataclass


@dataclass
class GenerateTitleInput:
    content: str  # The text, summary, or topic to generate titles for.
    count: Optional[int] = None  # Number of title candidates to generate. Default: 3.
    max_length: Optional[int] = None  # Maximum character count per title. Default: 80.
    style: Optional[str] = None  # Title style: 'neutral', 'clickbait', 'seo', 'academic'. Default: 'neutral'.


@dataclass
class GenerateTitleOutput:
    titles: list[str]  # Generated title candidates, ordered from most to least recommended.

