# Generated by aifn -- do not edit manually.

artifact = {
    "api": {
        "description": "Generate title or headline candidates for a piece of content.",
        "input": {
            "additionalProperties": False,
            "properties": {
                "content": {
                    "description": "The text, summary, or topic to generate titles for.",
                    "minLength": 1,
                    "type": "string",
                },
                "count": {
                    "description": "Number of title candidates to generate. Default: 3.",
                    "maximum": 10,
                    "minimum": 1,
                    "type": "integer",
                },
                "maxLength": {
                    "description": "Maximum character count per title. Default: 80.",
                    "type": "integer",
                },
                "style": {
                    "description": "Title style: 'neutral', 'clickbait', 'seo', 'academic'. Default: 'neutral'.",
                    "type": "string",
                },
            },
            "required": [
                "content",
            ],
            "type": "object",
        },
        "name": "generate-title",
        "output": {
            "additionalProperties": False,
            "properties": {
                "titles": {
                    "description": "Generated title candidates, ordered from most to least recommended.",
                    "items": {
                        "type": "string",
                    },
                    "type": "array",
                },
            },
            "required": [
                "titles",
            ],
            "type": "object",
        },
    },
    "artifactVersion": "0.1.0",
    "metadata": {
        "contentHash": "sha256:1b034f24cb6f462c2b3e848382d68d156cc14939078808c7a84c1746bff345d2",
        "generatedAt": "2026-07-05T03:19:40Z",
        "sourcePackageVersion": "1.0.0",
    },
    "modelParams": {
        "rules": [
            {
                "match": {
                    "pattern": ".*",
                },
                "params": {
                    "maxTokens": 512,
                    "temperature": 0.7,
                },
            },
        ],
        "schemaVersion": "0.1.0",
    },
    "package": {
        "author": {
            "name": "GildenEye",
        },
        "description": "Generate title or headline candidates for a piece of content.",
        "engine": "^0.1.0",
        "name": "generate-title",
        "type": "standalone",
        "version": "1.0.0",
    },
    "prompts": {
        "general": "# System\n\nYou are a title generation function. You must only return a JSON object in the following format:\n{\"titles\": [\"<title 1>\", \"<title 2>\", ...]}\n\nDo not output Markdown, do not include any extra explanation, and do not add undeclared fields.\n\nRequirements:\n- Generate the requested number of title candidates (default: 3).\n- Order titles from most to least recommended.\n- Apply the requested style (default: neutral). 'clickbait' uses curiosity-driven language; 'seo' front-loads keywords; 'academic' is formal and descriptive.\n- Each title must not exceed maxLength characters (default: 80).\n- Titles should be distinct from each other — vary wording and angle.\n\n# User\n\nContent:\n{{content}}\n\nStyle: {{style}}\n\nCount: {{count}}\n\nMax length per title: {{maxLength}}\n",
    },
    "schemaVersion": "0.1.0",
}
