// Generated by aifn — do not edit manually.
// Package: write-stream v1.0.0

package aifunc.write_stream;

import aifunc.AIFuncConfig;
import aifunc._engine.java.v0_2_0.Runtime;
import aifunc._engine.java.v0_2_0.Artifact;
import aifunc._engine.java.v0_2_0.Types.AIFuncArtifact;
import java.util.LinkedHashMap;
import java.util.Map;

/** Stream long-form writing — articles, reports, or documents — from a prompt and optional structure. Returns plain text. */
/** Generated by aifn — do not edit manually. */
public final class WriteStream {

	private WriteStream() {}

	/**
	 * Stream tokens from the model.
	 * Returns a {@link WriteStreamTypes.TokenStream} — use it in a try-with-resources block;
	 * {@code break} automatically cancels the stream and frees the background thread.
	 */
	public static WriteStreamTypes.TokenStream writeStream(AIFuncConfig config, WriteStreamTypes.WriteStreamInput input) {
		if (config == null) config = AIFuncConfig.builder().build();

		AIFuncArtifact artifact = Artifact.fromMap(WriteStreamAifunc.ARTIFACT_DATA);
		Map<String, Object> inputMap = inputToMap(input);
		return new WriteStreamTypes.TokenStream(Runtime.executeStream(artifact, inputMap, config));
	}

	private static Map<String, Object> inputToMap(WriteStreamTypes.WriteStreamInput input) {
		Map<String, Object> m = new LinkedHashMap<>();
		if (input.getAudience() != null) m.put("audience", input.getAudience());
		if (input.getFormat() != null) m.put("format", input.getFormat());
		if (input.getLanguage() != null) m.put("language", input.getLanguage());
		m.put("prompt", input.getPrompt());
		if (input.getStructure() != null) m.put("structure", input.getStructure());
		if (input.getTone() != null) m.put("tone", input.getTone());
		if (input.getWordCount() != null) m.put("wordCount", input.getWordCount());
		return m;
	}
}

