// Generated by aifn -- do not edit manually.
// Package: recognize-intent v1.0.0

import { execute } from '../_engine/typescript/v0.1.0/index';
import type { AIFuncArtifact, AIFuncConfig } from '../_engine/typescript/v0.1.0/index';
import artifact from './recognize-intent.aifunc';
import mockData from './recognize-intent.mock';
import type { RecognizeIntentInput, RecognizeIntentOutput } from './recognize-intent.types';

export type { AIFuncConfig, RecognizeIntentInput, RecognizeIntentOutput };

/** Recognize user intent from conversational text with confidence scores. */
export async function recognizeIntent(config: AIFuncConfig = { mock: true }, input: RecognizeIntentInput): Promise<RecognizeIntentOutput> {
const _projectDefaults = {};

  const runtimeConfig: AIFuncConfig = config.mock && !config.mockData
    ? { ...config, mockData }
    : config;

  return execute<RecognizeIntentOutput>(
    artifact as AIFuncArtifact,
    input as unknown as Record<string, unknown>,
    runtimeConfig,
    _projectDefaults,
  );
}
