// Generated by aifn -- do not edit manually.
// Package: chat-stream v1.0.0

export interface ChatStreamInput {
  /** Optional conversation history or other background text the reply should take into account. */
  context?: string;
  /** The user message. */
  message: string;
}

export type ChatStreamOutput = string;
