// Generated by aifn — do not edit manually.
// Package: answer-question v1.0.0

package aifunc.answer_question;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
@SuppressWarnings("serial")
final class AnswerQuestionAifunc {

	private AnswerQuestionAifunc() {}

	static final java.util.Map<String, Object> ARTIFACT_DATA =
		new java.util.LinkedHashMap<String, Object>() {{
			put("api", new java.util.LinkedHashMap<String, Object>() {{
				put("description", "Answer a question based on provided context or general knowledge.");
				put("input", new java.util.LinkedHashMap<String, Object>() {{
					put("additionalProperties", false);
					put("properties", new java.util.LinkedHashMap<String, Object>() {{
						put("context", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Source text or document to base the answer on. If omitted, uses general knowledge.");
							put("type", "string");
						}});
						put("language", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Answer language. If omitted, matches the question language.");
							put("type", "string");
						}});
						put("maxLength", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Maximum word count for the answer. Default: 100.");
							put("maximum", 500L);
							put("minimum", 20L);
							put("type", "integer");
						}});
						put("question", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "The question to answer.");
							put("minLength", 1L);
							put("type", "string");
						}});
					}});
					put("required", new java.util.ArrayList<Object>(java.util.Arrays.asList(
						"question"
					)));
					put("type", "object");
				}});
				put("name", "answer-question");
				put("output", new java.util.LinkedHashMap<String, Object>() {{
					put("additionalProperties", false);
					put("properties", new java.util.LinkedHashMap<String, Object>() {{
						put("answer", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "The generated answer.");
							put("type", "string");
						}});
						put("confidence", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Confidence score between 0 and 1.");
							put("maximum", 1L);
							put("minimum", 0L);
							put("type", "number");
						}});
						put("grounded", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "True if the answer is based on the provided context, false if from general knowledge.");
							put("type", "boolean");
						}});
					}});
					put("required", new java.util.ArrayList<Object>(java.util.Arrays.asList(
						"answer",
						"grounded",
						"confidence"
					)));
					put("type", "object");
				}});
			}});
			put("artifactVersion", "0.1.0");
			put("metadata", new java.util.LinkedHashMap<String, Object>() {{
				put("contentHash", "sha256:35de1639dec8c92f5fb011d367ff6277069d3239fd02a3dee49a57fa7a0edc51");
				put("generatedAt", "2026-07-17T00:03:11Z");
				put("sourcePackageVersion", "1.0.0");
			}});
			put("modelParams", new java.util.LinkedHashMap<String, Object>() {{
				put("rules", new java.util.ArrayList<Object>(java.util.Arrays.asList(
					new java.util.LinkedHashMap<String, Object>() {{
						put("match", new java.util.LinkedHashMap<String, Object>() {{
							put("pattern", ".*");
						}});
						put("params", new java.util.LinkedHashMap<String, Object>() {{
							put("maxTokens", 1024L);
							put("temperature", 0.2);
						}});
					}}
				)));
				put("schemaVersion", "0.1.0");
			}});
			put("package", new java.util.LinkedHashMap<String, Object>() {{
				put("author", new java.util.LinkedHashMap<String, Object>() {{
					put("name", "GildenEye");
				}});
				put("description", "Answer a question based on provided context or general knowledge.");
				put("engine", "^0.2.0");
				put("name", "answer-question");
				put("type", "standalone");
				put("version", "1.0.0");
			}});
			put("prompts", new java.util.LinkedHashMap<String, Object>() {{
				put("general", "# System\n\nYou are a question answering function. You must only return a JSON object in the following format:\n{\"answer\": \"<answer text>\", \"grounded\": <true|false>, \"confidence\": <0.0-1.0>}\n\nDo not output Markdown, do not include any extra explanation, and do not add undeclared fields.\n\nRequirements:\n- If context is provided, answer based solely on that context. Set 'grounded' to true.\n- If no context is provided, answer from general knowledge. Set 'grounded' to false.\n- If the context does not contain enough information to answer, say so clearly and set confidence below 0.5.\n- Answer in the requested language; if not specified, match the question language.\n- Keep the answer within maxLength words (default: 100). Be concise and direct.\n- Set 'confidence' to reflect how certain you are about the answer (0.0 = no idea, 1.0 = certain).\n\n# User\n\nQuestion: {{question}}\n\nContext:\n{{context}}\n\nMax length (words): {{maxLength}}\n\nLanguage: {{language}}\n");
			}});
			put("schemaVersion", "0.1.0");
		}};
}
