// Generated by aifn — do not edit manually.
// Package: answer-question v1.0.0

package aifunc.answer_question;

import aifunc.AIFuncConfig;
import aifunc._engine.java.v0_1_0.Runtime;
import aifunc._engine.java.v0_1_0.Artifact;
import aifunc._engine.java.v0_1_0.Types.AIFuncArtifact;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

/** Answer a question based on provided context or general knowledge. */
/** Generated by aifn — do not edit manually. */
public final class AnswerQuestion {

	private AnswerQuestion() {}

	private static final Object MOCK_DATA = AnswerQuestionAifuncMock.MOCK_DATA;

	public static CompletableFuture<AnswerQuestionTypes.AnswerQuestionOutput> answerQuestion(AIFuncConfig config, AnswerQuestionTypes.AnswerQuestionInput input) {
		if (config == null) {
			config = AIFuncConfig.builder().mock(true).mockData(MOCK_DATA).build();
		} else if (config.isMock() && config.getMockData() == null) {
			config = config.toBuilder().mockData(MOCK_DATA).build();
		}


		AIFuncArtifact artifact = Artifact.fromMap(AnswerQuestionAifunc.ARTIFACT_DATA);
		Map<String, Object> inputMap = inputToMap(input);
		return Runtime.executeAsync(artifact, inputMap, config)
			.thenApply(AnswerQuestion::mapToOutput);
	}

	private static Map<String, Object> inputToMap(AnswerQuestionTypes.AnswerQuestionInput input) {
		Map<String, Object> m = new LinkedHashMap<>();
		if (input.getContext() != null) m.put("context", input.getContext());
		if (input.getLanguage() != null) m.put("language", input.getLanguage());
		if (input.getMaxLength() != null) m.put("maxLength", input.getMaxLength());
		m.put("question", input.getQuestion());
		return m;
	}

	private static AnswerQuestionTypes.AnswerQuestionOutput mapToOutput(Map<String, Object> m) {
		String answer = m.containsKey("answer") ? (m.get("answer") instanceof String) ? (String) m.get("answer") : String.valueOf(m.get("answer")) : null;
		Double confidence = m.containsKey("confidence") ? (m.get("confidence") instanceof Number) ? ((Number) m.get("confidence")).doubleValue() : null : null;
		Boolean grounded = m.containsKey("grounded") ? (m.get("grounded") instanceof Boolean) ? (Boolean) m.get("grounded") : null : null;
		return new AnswerQuestionTypes.AnswerQuestionOutput(answer, confidence, grounded);
	}
}
