// Generated by aifn — do not edit manually.
// Package: answer-question v1.0.0

package aifunc.answer_question;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
public final class AnswerQuestionTypes {

	private AnswerQuestionTypes() {}

	public static final class AnswerQuestionInput {
		/** The question to answer. */
		private final String question;
		/** Source text or document to base the answer on. If omitted, uses general knowledge. */
		private String context;
		/** Answer language. If omitted, matches the question language. */
		private String language;
		/** Maximum word count for the answer. Default: 100. */
		private Integer maxLength;

		public AnswerQuestionInput(String question, String context, String language, Integer maxLength) {
			this.question = question;
			this.context = context;
			this.language = language;
			this.maxLength = maxLength;
		}

		public String getQuestion() { return question; }
		public String getContext() { return context; }
		public void setContext(String v) { this.context = v; }
		public String getLanguage() { return language; }
		public void setLanguage(String v) { this.language = v; }
		public Integer getMaxLength() { return maxLength; }
		public void setMaxLength(Integer v) { this.maxLength = v; }
	}

	public static final class AnswerQuestionOutput {
		/** The generated answer. */
		private final String answer;
		/** Confidence score between 0 and 1. */
		private final Double confidence;
		/** True if the answer is based on the provided context, false if from general knowledge. */
		private final Boolean grounded;

		public AnswerQuestionOutput(String answer, Double confidence, Boolean grounded) {
			this.answer = answer;
			this.confidence = confidence;
			this.grounded = grounded;
		}

		public String getAnswer() { return answer; }
		public Double getConfidence() { return confidence; }
		public Boolean getGrounded() { return grounded; }
	}
}
