# Generated by aifn -- do not edit manually.

artifact = {
    "api": {
        "description": "Evaluate text quality across multiple dimensions and return structured scores with improvement advice.",
        "input": {
            "additionalProperties": False,
            "properties": {
                "maxSuggestions": {
                    "default": 3,
                    "description": "Maximum number of improvement suggestions to return.",
                    "maximum": 10,
                    "minimum": 1,
                    "type": "integer",
                },
                "purpose": {
                    "default": "general communication",
                    "description": "Writing purpose (e.g. 'explanation', 'marketing', 'support', 'learning').",
                    "type": "string",
                },
                "strictness": {
                    "default": 3,
                    "description": "Evaluation strictness from 1 (lenient) to 5 (very strict).",
                    "maximum": 5,
                    "minimum": 1,
                    "type": "integer",
                },
                "targetAudience": {
                    "default": "general readers",
                    "description": "Intended readers (e.g. 'developers', 'customers', 'students', 'executives').",
                    "type": "string",
                },
                "text": {
                    "description": "The text content to evaluate.",
                    "minLength": 1,
                    "type": "string",
                },
            },
            "required": [
                "text",
            ],
            "type": "object",
        },
        "name": "score-quality",
        "output": {
            "additionalProperties": False,
            "properties": {
                "actionabilityScore": {
                    "description": "How actionable and useful the text is, from 0 to 100.",
                    "maximum": 100,
                    "minimum": 0,
                    "type": "integer",
                },
                "clarityScore": {
                    "description": "Clarity score from 0 to 100.",
                    "maximum": 100,
                    "minimum": 0,
                    "type": "integer",
                },
                "level": {
                    "description": "Overall quality level.",
                    "enum": [
                        "excellent",
                        "good",
                        "fair",
                        "poor",
                    ],
                    "type": "string",
                },
                "overallScore": {
                    "description": "Overall quality score from 0 to 100.",
                    "maximum": 100,
                    "minimum": 0,
                    "type": "integer",
                },
                "structureScore": {
                    "description": "Organization and logical structure score from 0 to 100.",
                    "maximum": 100,
                    "minimum": 0,
                    "type": "integer",
                },
                "suggestions": {
                    "description": "Concise improvement suggestions, ordered by importance.",
                    "items": {
                        "type": "string",
                    },
                    "minItems": 0,
                    "type": "array",
                },
                "summary": {
                    "description": "One short sentence summarizing the evaluation.",
                    "type": "string",
                },
                "toneScore": {
                    "description": "Tone suitability score from 0 to 100.",
                    "maximum": 100,
                    "minimum": 0,
                    "type": "integer",
                },
            },
            "required": [
                "overallScore",
                "clarityScore",
                "structureScore",
                "toneScore",
                "actionabilityScore",
                "level",
                "summary",
                "suggestions",
            ],
            "type": "object",
        },
    },
    "artifactVersion": "0.1.0",
    "metadata": {
        "contentHash": "sha256:762f256bb8916716b45cb2a91f6c3692630d1124fcb890e1dac2542ec25a0fdc",
        "generatedAt": "2026-07-05T03:19:40Z",
        "sourcePackageVersion": "1.0.0",
    },
    "modelParams": {
        "rules": [
            {
                "match": {
                    "pattern": ".*",
                },
                "params": {
                    "maxTokens": 700,
                    "temperature": 0.1,
                },
            },
            {
                "match": {
                    "models": [
                        "gpt-4o-mini",
                        "gpt-4o",
                    ],
                },
                "params": {
                    "maxTokens": 650,
                    "temperature": 0,
                },
                "providerParams": {
                    "openai": {
                        "reasoningEffort": "low",
                    },
                },
            },
        ],
        "schemaVersion": "0.1.0",
    },
    "package": {
        "author": {
            "name": "GildenEye",
        },
        "description": "Evaluate text quality across multiple dimensions and return structured scores with improvement advice.",
        "engine": "^0.1.0",
        "name": "score-quality",
        "type": "standalone",
        "version": "1.0.0",
    },
    "prompts": {
        "general": "# System\n\nYou are a strict text quality evaluation function. You must only return a JSON object in EXACTLY this format:\n{\"overallScore\": <0-100>, \"clarityScore\": <0-100>, \"structureScore\": <0-100>, \"toneScore\": <0-100>, \"actionabilityScore\": <0-100>, \"level\": \"<excellent|good|fair|poor>\", \"summary\": \"<one sentence>\", \"suggestions\": [\"...\"]}\n\nDo not output Markdown, do not include any extra explanation, and do not omit any fields.\n\nScoring dimensions:\n- overallScore: holistic usefulness and quality.\n- clarityScore: ease of understanding, precision, and lack of ambiguity.\n- structureScore: organization, flow, and logical sequencing.\n- toneScore: suitability for the target audience and purpose.\n- actionabilityScore: whether the reader can understand what to do or take away.\n\nLevel mapping:\n- excellent: overallScore >= 90\n- good: overallScore >= 75 and < 90\n- fair: overallScore >= 50 and < 75\n- poor: overallScore < 50\n\nsummary: one concise sentence summarizing the overall evaluation result.\n\nsuggestions: up to maxSuggestions concise, actionable improvement tips (default 3 if not specified).\n\n# User\n\nText to evaluate:\n{{text}}\n\nTarget audience:\n{{targetAudience}}\n\nPurpose:\n{{purpose}}\n\nMaximum suggestions:\n{{maxSuggestions}}\n\nStrictness from 1 to 5:\n{{strictness}}\n",
    },
    "schemaVersion": "0.1.0",
}
