// Generated by aifn -- do not edit manually.
// Package: extract-json v1.0.0

import { execute } from '../_engine/typescript/v0.1.0/index';
import type { AIFuncArtifact, AIFuncConfig } from '../_engine/typescript/v0.1.0/index';
import artifact from './extract-json.aifunc';
import mockData from './extract-json.mock';
import type { ExtractJsonInput, ExtractJsonOutput } from './extract-json.types';

export type { AIFuncConfig, ExtractJsonInput, ExtractJsonOutput };

/** Extract structured JSON from natural language text according to a user-defined field schema. */
export async function extractJson(config: AIFuncConfig = { mock: true }, input: ExtractJsonInput): Promise<ExtractJsonOutput> {
  const runtimeConfig: AIFuncConfig = config.mock && !config.mockData
    ? { ...config, mockData }
    : config;

  return execute<ExtractJsonOutput>(
    artifact as AIFuncArtifact,
    input as unknown as Record<string, unknown>,
    runtimeConfig,
  );
}
