// Generated by aifn — do not edit manually.
// Package: translate v1.0.0

package aifunc.translate;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
@SuppressWarnings("serial")
final class TranslateAifuncMock {

	private TranslateAifuncMock() {}

	static final Object MOCK_DATA =
		new java.util.LinkedHashMap<String, Object>() {{
			put("cases", new java.util.ArrayList<Object>(java.util.Arrays.asList(
				new java.util.LinkedHashMap<String, Object>() {{
					put("description", "Translate Chinese text to English with auto-detected source language.");
					put("id", "zh-to-en");
					put("output", new java.util.LinkedHashMap<String, Object>() {{
						put("sourceLang", "zh-CN");
						put("translation", "Artificial intelligence is changing the way we work and live.");
					}});
				}}
			)));
			put("delay", new java.util.LinkedHashMap<String, Object>() {{
				put("maxMs", 120L);
				put("minMs", 30L);
			}});
			put("random", new java.util.LinkedHashMap<String, Object>() {{
				put("enabled", false);
				put("seed", "translate");
			}});
			put("version", "1.0.0");
		}};
}
