// Generated by aifn — do not edit manually.
// Package: translate v1.0.0

package aifunc.translate;

import aifunc.AIFuncConfig;
import aifunc._engine.java.v0_1_0.Runtime;
import aifunc._engine.java.v0_1_0.Artifact;
import aifunc._engine.java.v0_1_0.Types.AIFuncArtifact;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

/** Translate text into a specified target language with automatic source language detection. */
/** Generated by aifn — do not edit manually. */
public final class Translate {

	private Translate() {}

	private static final Object MOCK_DATA = TranslateAifuncMock.MOCK_DATA;

	public static CompletableFuture<TranslateTypes.TranslateOutput> translate(AIFuncConfig config, TranslateTypes.TranslateInput input) {
		if (config == null) {
			config = AIFuncConfig.builder().mock(true).mockData(MOCK_DATA).build();
		} else if (config.isMock() && config.getMockData() == null) {
			config = config.toBuilder().mockData(MOCK_DATA).build();
		}


		AIFuncArtifact artifact = Artifact.fromMap(TranslateAifunc.ARTIFACT_DATA);
		Map<String, Object> inputMap = inputToMap(input);
		return Runtime.executeAsync(artifact, inputMap, config)
			.thenApply(Translate::mapToOutput);
	}

	private static Map<String, Object> inputToMap(TranslateTypes.TranslateInput input) {
		Map<String, Object> m = new LinkedHashMap<>();
		if (input.getSourceLang() != null) m.put("sourceLang", input.getSourceLang());
		m.put("targetLang", input.getTargetLang());
		m.put("text", input.getText());
		return m;
	}

	private static TranslateTypes.TranslateOutput mapToOutput(Map<String, Object> m) {
		String sourceLang = m.containsKey("sourceLang") ? (m.get("sourceLang") instanceof String) ? (String) m.get("sourceLang") : String.valueOf(m.get("sourceLang")) : null;
		String translation = m.containsKey("translation") ? (m.get("translation") instanceof String) ? (String) m.get("translation") : String.valueOf(m.get("translation")) : null;
		return new TranslateTypes.TranslateOutput(sourceLang, translation);
	}
}
