// Generated by aifn -- do not edit manually.
// Package: translate v1.0.0

import { execute } from '../_engine/typescript/v0.1.0/index';
import type { AIFuncArtifact, AIFuncConfig } from '../_engine/typescript/v0.1.0/index';
import artifact from './translate.aifunc';
import mockData from './translate.mock';
import type { TranslateInput, TranslateOutput } from './translate.types';

export type { AIFuncConfig, TranslateInput, TranslateOutput };

/** Translate text into a specified target language with automatic source language detection. */
export async function translate(config: AIFuncConfig = { mock: true }, input: TranslateInput): Promise<TranslateOutput> {
  const runtimeConfig: AIFuncConfig = config.mock && !config.mockData
    ? { ...config, mockData }
    : config;

  return execute<TranslateOutput>(
    artifact as AIFuncArtifact,
    input as unknown as Record<string, unknown>,
    runtimeConfig,
  );
}
