# Generated by aifn -- do not edit manually.
# Package: translate-stream v1.0.0

from typing import Any, Optional
from dataclasses import dataclass


@dataclass
class TranslateStreamInput:
    target_lang: str  # Target language (e.g. 'Chinese', 'English', 'French', 'zh-CN').
    text: str  # The text or document to translate.
    domain: Optional[str] = None  # Subject domain hint to improve terminology accuracy (e.g. 'legal', 'medical', 'technical', 'literary'). Optional.
    source_lang: Optional[str] = None  # Source language. If omitted, it is auto-detected.
    style: Optional[str] = None  # Translation style: 'literal' (close to source), 'natural' (idiomatic), 'formal'. Default: 'natural'.

