// Generated by aifn — do not edit manually.
// Package: generate-slug v1.0.0

package aifunc.generate_slug;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
@SuppressWarnings("serial")
final class GenerateSlugAifunc {

	private GenerateSlugAifunc() {}

	static final java.util.Map<String, Object> ARTIFACT_DATA =
		new java.util.LinkedHashMap<String, Object>() {{
			put("api", new java.util.LinkedHashMap<String, Object>() {{
				put("description", "Generate an SEO-friendly URL slug, meta description, and tag suggestions from a title.");
				put("input", new java.util.LinkedHashMap<String, Object>() {{
					put("additionalProperties", false);
					put("properties", new java.util.LinkedHashMap<String, Object>() {{
						put("description", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Optional longer description to inform slug and meta generation.");
							put("type", "string");
						}});
						put("language", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Content language hint (e.g. 'en', 'zh-CN'). Slug will always be ASCII.");
							put("type", "string");
						}});
						put("title", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "The article or page title.");
							put("minLength", 1L);
							put("type", "string");
						}});
					}});
					put("required", new java.util.ArrayList<Object>(java.util.Arrays.asList(
						"title"
					)));
					put("type", "object");
				}});
				put("name", "generate-slug");
				put("output", new java.util.LinkedHashMap<String, Object>() {{
					put("additionalProperties", false);
					put("properties", new java.util.LinkedHashMap<String, Object>() {{
						put("metaDescription", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "SEO meta description (120-160 characters recommended).");
							put("type", "string");
						}});
						put("slug", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "URL-safe slug using lowercase ASCII letters, numbers, and hyphens.");
							put("type", "string");
						}});
						put("tags", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Suggested tags or keywords for the content.");
							put("items", new java.util.LinkedHashMap<String, Object>() {{
								put("type", "string");
							}});
							put("type", "array");
						}});
					}});
					put("required", new java.util.ArrayList<Object>(java.util.Arrays.asList(
						"slug",
						"metaDescription",
						"tags"
					)));
					put("type", "object");
				}});
			}});
			put("artifactVersion", "0.1.0");
			put("metadata", new java.util.LinkedHashMap<String, Object>() {{
				put("contentHash", "sha256:0e508a60148b537c7c3e7f427f3d787db1bf8857add3c48eaae483496bdb9228");
				put("generatedAt", "2026-07-12T06:36:24Z");
				put("sourcePackageVersion", "1.0.0");
			}});
			put("modelParams", new java.util.LinkedHashMap<String, Object>() {{
				put("rules", new java.util.ArrayList<Object>(java.util.Arrays.asList(
					new java.util.LinkedHashMap<String, Object>() {{
						put("match", new java.util.LinkedHashMap<String, Object>() {{
							put("pattern", ".*");
						}});
						put("params", new java.util.LinkedHashMap<String, Object>() {{
							put("maxTokens", 400L);
							put("temperature", 0.3);
						}});
					}}
				)));
				put("schemaVersion", "0.1.0");
			}});
			put("package", new java.util.LinkedHashMap<String, Object>() {{
				put("author", new java.util.LinkedHashMap<String, Object>() {{
					put("name", "GildenEye");
				}});
				put("description", "Generate SEO-friendly URL slugs, meta descriptions, and tag suggestions from titles.");
				put("engine", "^0.1.0");
				put("name", "generate-slug");
				put("type", "standalone");
				put("version", "1.0.0");
			}});
			put("prompts", new java.util.LinkedHashMap<String, Object>() {{
				put("general", "# System\n\nYou are an SEO slug generation function. You must only return a JSON object in the following format:\n{\"slug\": \"<url-slug>\", \"metaDescription\": \"<description>\", \"tags\": [\"<tag>\", ...]}\n\nDo not output Markdown, do not include any extra explanation, and do not add undeclared fields.\n\nRequirements:\n- Generate a URL-safe `slug` from the title: lowercase ASCII, words separated by hyphens, no special characters. Keep it concise (3-8 words).\n- If the title is in a non-Latin language (e.g. Chinese, Japanese), translate the core meaning into English for the slug.\n- Generate a `metaDescription` that is compelling and SEO-friendly, between 120 and 160 characters. It should summarize the content and encourage clicks.\n- Suggest 3-6 relevant `tags` for categorization and discoverability.\n- Tags should be lowercase and in the content's language unless the language hint suggests otherwise.\n- The meta description should be in the same language as the title unless the content language is ambiguous.\n\n# User\n\nTitle: {{title}}\n\nDescription: {{description}}\n\nLanguage: {{language}}\n");
			}});
			put("schemaVersion", "0.1.0");
		}};
}
