// Generated by aifn — do not edit manually.
// Package: generate-slug v1.0.0

package aifunc.generate_slug;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
public final class GenerateSlugTypes {

	private GenerateSlugTypes() {}

	public static final class GenerateSlugInput {
		/** The article or page title. */
		private final String title;
		/** Optional longer description to inform slug and meta generation. */
		private String description;
		/** Content language hint (e.g. 'en', 'zh-CN'). Slug will always be ASCII. */
		private String language;

		public GenerateSlugInput(String title, String description, String language) {
			this.title = title;
			this.description = description;
			this.language = language;
		}

		public String getTitle() { return title; }
		public String getDescription() { return description; }
		public void setDescription(String v) { this.description = v; }
		public String getLanguage() { return language; }
		public void setLanguage(String v) { this.language = v; }
	}

	public static final class GenerateSlugOutput {
		/** SEO meta description (120-160 characters recommended). */
		private final String metaDescription;
		/** URL-safe slug using lowercase ASCII letters, numbers, and hyphens. */
		private final String slug;
		/** Suggested tags or keywords for the content. */
		private final java.util.List<String> tags;

		public GenerateSlugOutput(String metaDescription, String slug, java.util.List<String> tags) {
			this.metaDescription = metaDescription;
			this.slug = slug;
			this.tags = tags;
		}

		public String getMetaDescription() { return metaDescription; }
		public String getSlug() { return slug; }
		public java.util.List<String> getTags() { return tags; }
	}
}
