// Generated by aifn -- do not edit manually.
// Package: extract-json v1.0.0

package extract_json

var artifactData = map[string]any{
	"api": map[string]any{
		"description": "Extract structured JSON from natural language text according to a user-defined field schema.",
		"input": map[string]any{
			"additionalProperties": false,
			"properties": map[string]any{
				"fields": map[string]any{
					"description": "Schema describing the fields to extract.",
					"items": map[string]any{
						"additionalProperties": false,
						"properties": map[string]any{
							"description": map[string]any{
								"description": "What this field represents, to guide extraction.",
								"type": "string",
							},
							"name": map[string]any{
								"description": "Field name (will be the key in the output JSON).",
								"minLength": 1,
								"type": "string",
							},
							"type": map[string]any{
								"description": "Expected value type.",
								"enum": []any{
									"string",
									"number",
									"boolean",
									"array",
									"object",
								},
								"type": "string",
							},
						},
						"required": []any{
							"name",
							"description",
							"type",
						},
						"type": "object",
					},
					"minItems": 1,
					"type": "array",
				},
				"text": map[string]any{
					"description": "The natural language text to extract information from.",
					"minLength": 1,
					"type": "string",
				},
			},
			"required": []any{
				"text",
				"fields",
			},
			"type": "object",
		},
		"name": "extract-json",
		"output": map[string]any{
			"additionalProperties": false,
			"properties": map[string]any{
				"extracted": map[string]any{
					"additionalProperties": true,
					"description": "Extracted key-value pairs matching the requested fields.",
					"type": "object",
				},
				"missing": map[string]any{
					"description": "Field names that could not be found in the text.",
					"items": map[string]any{
						"type": "string",
					},
					"type": "array",
				},
			},
			"required": []any{
				"extracted",
				"missing",
			},
			"type": "object",
		},
	},
	"artifactVersion": "0.1.0",
	"metadata": map[string]any{
		"contentHash": "sha256:9da2d18f5fb3a155da515c417aeb72b33f7f487601ae13723fb1d733ccda158d",
		"generatedAt": "2026-07-11T02:28:00Z",
		"sourcePackageVersion": "1.0.0",
	},
	"modelParams": map[string]any{
		"rules": []any{
			map[string]any{
				"match": map[string]any{
					"pattern": ".*",
				},
				"params": map[string]any{
					"maxTokens": 1024,
					"temperature": 0,
				},
			},
		},
		"schemaVersion": "0.1.0",
	},
	"package": map[string]any{
		"author": map[string]any{
			"name": "GildenEye",
		},
		"description": "Extract structured JSON data from natural language text based on a user-defined field schema.",
		"engine": "^0.1.0",
		"name": "extract-json",
		"type": "standalone",
		"version": "1.0.0",
	},
	"prompts": map[string]any{
		"general": "# System\n\nYou are a structured information extraction function. You must only return a JSON object in the following format:\n{\"extracted\": {<fieldName>: <value>, ...}, \"missing\": [<fieldName>, ...]}\n\nDo not output Markdown, do not include any extra explanation, and do not add undeclared fields.\n\nRequirements:\n- Extract information from the text based on the field definitions provided.\n- Each field has a `name`, `description` (what to look for), and `type` (the expected value type).\n- Place successfully extracted values in `extracted` using the field name as key.\n- Values must match the declared type: \"string\" -> string, \"number\" -> number, \"boolean\" -> true/false, \"array\" -> JSON array, \"object\" -> JSON object.\n- If a field's value cannot be determined from the text, do NOT guess — add the field name to the `missing` array and omit it from `extracted`.\n- Do not invent information that is not present or clearly implied in the text.\n- For \"array\" fields, extract all relevant items mentioned in the text.\n- For \"number\" fields, parse numeric values (e.g. \"five years\" -> 5).\n\n# User\n\nText:\n{{text}}\n\nFields to extract:\n{{fields}}\n",
	},
	"schemaVersion": "0.1.0",
}
