// Generated by aifn -- do not edit manually.
// Package: answer-question v1.0.0

import { execute } from '../_engine/typescript/v0.1.0/index';
import type { AIFuncArtifact, AIFuncConfig } from '../_engine/typescript/v0.1.0/index';
import artifact from './answer-question.aifunc';
import mockData from './answer-question.mock';
import type { AnswerQuestionInput, AnswerQuestionOutput } from './answer-question.types';

export type { AIFuncConfig, AnswerQuestionInput, AnswerQuestionOutput };

/** Answer a question based on provided context or general knowledge. */
export async function answerQuestion(config: AIFuncConfig = { mock: true }, input: AnswerQuestionInput): Promise<AnswerQuestionOutput> {
const _projectDefaults = {};

  const runtimeConfig: AIFuncConfig = config.mock && !config.mockData
    ? { ...config, mockData }
    : config;

  return execute<AnswerQuestionOutput>(
    artifact as AIFuncArtifact,
    input as unknown as Record<string, unknown>,
    runtimeConfig,
    _projectDefaults,
  );
}
