# Generated by aifn -- do not edit manually.

artifact = {
    "api": {
        "description": "Generate a concise summary of the input text.",
        "input": {
            "additionalProperties": False,
            "properties": {
                "maxLength": {
                    "default": 80,
                    "description": "Maximum word count for the summary. Defaults to 80.",
                    "maximum": 300,
                    "minimum": 20,
                    "type": "integer",
                },
                "text": {
                    "description": "The text to summarize.",
                    "minLength": 1,
                    "type": "string",
                },
            },
            "required": [
                "text",
            ],
            "type": "object",
        },
        "name": "summarize",
        "output": {
            "additionalProperties": False,
            "properties": {
                "summary": {
                    "description": "The generated summary.",
                    "type": "string",
                },
                "wordCount": {
                    "description": "Approximate word count of the summary.",
                    "minimum": 0,
                    "type": "integer",
                },
            },
            "required": [
                "summary",
                "wordCount",
            ],
            "type": "object",
        },
    },
    "artifactVersion": "0.1.0",
    "metadata": {
        "contentHash": "sha256:2b1e7439696465851cc4e8259aaf744dcc058d61d69aba494a40e34c5df46f9c",
        "generatedAt": "2026-07-15T13:20:50Z",
        "sourcePackageVersion": "1.0.0",
    },
    "modelParams": {
        "rules": [
            {
                "match": {
                    "pattern": ".*",
                },
                "params": {
                    "maxTokens": 300,
                    "temperature": 0.2,
                },
            },
        ],
        "schemaVersion": "0.1.0",
    },
    "package": {
        "author": {
            "name": "GildenEye",
        },
        "description": "Generate a concise summary of the input text.",
        "engine": "^0.2.0",
        "name": "summarize",
        "type": "standalone",
        "version": "1.0.0",
    },
    "prompts": {
        "general": "# System\n\nYou are a strict summarization function. You must only return a JSON object that conforms to the output schema. Do not output Markdown, do not include any extra explanation, and do not add undeclared fields.\n\nRequirements:\n- The summary language must match the language of the input text — do not translate.\n- The summary should be concise, accurate, and fluent.\n- Preserve the most essential information; do not fabricate anything not present in the original.\n- If the input covers multiple points, prioritize the most important 1 to 3.\n- `summary` must not exceed the word/character count specified by `maxLength`; default to 80 if not provided.\n- `wordCount` should reflect the approximate length of the summary.\n\n# User\n\nText:\n{{text}}\n\nMaximum length:\n{{maxLength}}\n",
    },
    "schemaVersion": "0.1.0",
}
