// Generated by aifn — do not edit manually.
// Package: generate-reply v1.0.0

package aifunc.generate_reply;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
@SuppressWarnings("serial")
final class GenerateReplyAifuncMock {

	private GenerateReplyAifuncMock() {}

	static final Object MOCK_DATA =
		new java.util.LinkedHashMap<String, Object>() {{
			put("cases", new java.util.ArrayList<Object>(java.util.Arrays.asList(
				new java.util.LinkedHashMap<String, Object>() {{
					put("description", "Generate a friendly reply to a customer message.");
					put("id", "friendly-reply");
					put("output", new java.util.LinkedHashMap<String, Object>() {{
						put("reply", "Thanks for reaching out! I completely understand your concern and I'm happy to help sort this out for you. Let me look into it right away.");
					}});
				}}
			)));
			put("delay", new java.util.LinkedHashMap<String, Object>() {{
				put("maxMs", 120L);
				put("minMs", 30L);
			}});
			put("random", new java.util.LinkedHashMap<String, Object>() {{
				put("enabled", false);
				put("seed", "generate-reply");
			}});
			put("version", "1.0.0");
		}};
}
