// Generated by aifn — do not edit manually.
// Package: generate-reply v1.0.0

package aifunc.generate_reply;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
public final class GenerateReplyTypes {

	private GenerateReplyTypes() {}

	public static final class GenerateReplyInput {
		/** The original message or comment to reply to. */
		private final String message;
		/** Background context to inform the reply (e.g. role, situation). */
		private String context;
		/** Reply language. If omitted, matches the input message language. */
		private String language;
		/** Desired tone: 'friendly', 'formal', 'empathetic', 'concise'. Default: 'friendly'. */
		private String tone;

		public GenerateReplyInput(String message, String context, String language, String tone) {
			this.message = message;
			this.context = context;
			this.language = language;
			this.tone = tone;
		}

		public String getMessage() { return message; }
		public String getContext() { return context; }
		public void setContext(String v) { this.context = v; }
		public String getLanguage() { return language; }
		public void setLanguage(String v) { this.language = v; }
		public String getTone() { return tone; }
		public void setTone(String v) { this.tone = v; }
	}

	public static final class GenerateReplyOutput {
		/** The generated reply text. */
		private final String reply;

		public GenerateReplyOutput(String reply) {
			this.reply = reply;
		}

		public String getReply() { return reply; }
	}
}
