// Generated by aifn — do not edit manually.
// Package: generate-post v1.0.0

package aifunc.generate_post;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
public final class GeneratePostTypes {

	private GeneratePostTypes() {}

	public static final class GeneratePostInput {
		/** The subject or key idea of the post. */
		private final String topic;
		/** Whether to append relevant hashtags. Default: false. */
		private Boolean includeHashtags;
		/** Maximum character count. */
		private Integer maxLength;
		/** Target platform: 'twitter', 'linkedin', 'instagram', 'general'. Default: 'general'. */
		private String platform;
		/** Desired tone (e.g. 'professional', 'casual', 'inspirational'). Default: 'casual'. */
		private String tone;

		public GeneratePostInput(String topic, Boolean includeHashtags, Integer maxLength, String platform, String tone) {
			this.topic = topic;
			this.includeHashtags = includeHashtags;
			this.maxLength = maxLength;
			this.platform = platform;
			this.tone = tone;
		}

		public String getTopic() { return topic; }
		public Boolean getIncludeHashtags() { return includeHashtags; }
		public void setIncludeHashtags(Boolean v) { this.includeHashtags = v; }
		public Integer getMaxLength() { return maxLength; }
		public void setMaxLength(Integer v) { this.maxLength = v; }
		public String getPlatform() { return platform; }
		public void setPlatform(String v) { this.platform = v; }
		public String getTone() { return tone; }
		public void setTone(String v) { this.tone = v; }
	}

	public static final class GeneratePostOutput {
		/** Character count of the generated post. */
		private final Integer charCount;
		/** Suggested hashtags (empty if includeHashtags is false). */
		private final java.util.List<String> hashtags;
		/** The generated post content. */
		private final String post;

		public GeneratePostOutput(Integer charCount, java.util.List<String> hashtags, String post) {
			this.charCount = charCount;
			this.hashtags = hashtags;
			this.post = post;
		}

		public Integer getCharCount() { return charCount; }
		public java.util.List<String> getHashtags() { return hashtags; }
		public String getPost() { return post; }
	}
}
