// Generated by aifn — do not edit manually.
// Package: generate-post v1.0.0

package aifunc.generate_post;

import aifunc.AIFuncConfig;
import aifunc._engine.java.v0_2_0.Runtime;
import aifunc._engine.java.v0_2_0.Artifact;
import aifunc._engine.java.v0_2_0.Types.AIFuncArtifact;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

/** Generate a social media post or short article from a topic or brief. */
/** Generated by aifn — do not edit manually. */
public final class GeneratePost {

	private GeneratePost() {}

	private static final Object MOCK_DATA = GeneratePostAifuncMock.MOCK_DATA;

	public static CompletableFuture<GeneratePostTypes.GeneratePostOutput> generatePost(AIFuncConfig config, GeneratePostTypes.GeneratePostInput input) {
		if (config == null) {
			config = AIFuncConfig.builder().mock(true).mockData(MOCK_DATA).build();
		} else if (config.isMock() && config.getMockData() == null) {
			config = config.toBuilder().mockData(MOCK_DATA).build();
		}

		AIFuncArtifact artifact = Artifact.fromMap(GeneratePostAifunc.ARTIFACT_DATA);
		Map<String, Object> inputMap = inputToMap(input);
		return Runtime.executeAsync(artifact, inputMap, config)
			.thenApply(GeneratePost::mapToOutput);
	}

	private static Map<String, Object> inputToMap(GeneratePostTypes.GeneratePostInput input) {
		Map<String, Object> m = new LinkedHashMap<>();
		if (input.getIncludeHashtags() != null) m.put("includeHashtags", input.getIncludeHashtags());
		if (input.getMaxLength() != null) m.put("maxLength", input.getMaxLength());
		if (input.getPlatform() != null) m.put("platform", input.getPlatform());
		if (input.getTone() != null) m.put("tone", input.getTone());
		m.put("topic", input.getTopic());
		return m;
	}

	@SuppressWarnings("unchecked")
	private static GeneratePostTypes.GeneratePostOutput mapToOutput(Map<String, Object> m) {
		Integer charCount = m.containsKey("charCount") ? (m.get("charCount") instanceof Number) ? ((Number) m.get("charCount")).intValue() : null : null;
		java.util.List<String> hashtags = m.containsKey("hashtags") ? (m.get("hashtags") instanceof java.util.List<?>) ? (java.util.List<String>) m.get("hashtags") : null : null;
		String post = m.containsKey("post") ? (m.get("post") instanceof String) ? (String) m.get("post") : String.valueOf(m.get("post")) : null;
		return new GeneratePostTypes.GeneratePostOutput(charCount, hashtags, post);
	}
}
