// Generated by aifn — do not edit manually.
// Package: generate-post v1.0.0

package aifunc.generate_post;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
@SuppressWarnings("serial")
final class GeneratePostAifuncMock {

	private GeneratePostAifuncMock() {}

	static final Object MOCK_DATA =
		new java.util.LinkedHashMap<String, Object>() {{
			put("cases", new java.util.ArrayList<Object>(java.util.Arrays.asList(
				new java.util.LinkedHashMap<String, Object>() {{
					put("description", "Generate a professional LinkedIn post.");
					put("id", "linkedin-post");
					put("output", new java.util.LinkedHashMap<String, Object>() {{
						put("charCount", 221L);
						put("hashtags", new java.util.ArrayList<Object>(java.util.Arrays.asList(
							"ProductLaunch",
							"TeamWork",
							"Growth"
						)));
						put("post", "Excited to share that our team just shipped a major product update — three months of work packed into one release. Proud of everyone involved. Growth is never a straight line, but this milestone proves consistency pays off.");
					}});
				}}
			)));
			put("delay", new java.util.LinkedHashMap<String, Object>() {{
				put("maxMs", 120L);
				put("minMs", 30L);
			}});
			put("random", new java.util.LinkedHashMap<String, Object>() {{
				put("enabled", false);
				put("seed", "generate-post");
			}});
			put("version", "1.0.0");
		}};
}
