// Generated by aifn — do not edit manually.
// Package: score-quality v1.0.0

namespace Aifunc.ScoreQuality;

using System.Collections.Generic;

public static class ScoreQualityTypes
{
	public sealed class ScoreQualityInput
	{
		/// <summary>The text content to evaluate.</summary>
		public string Text { get; }
		/// <summary>Maximum number of improvement suggestions to return.</summary>
		public int? MaxSuggestions { get; set; }
		/// <summary>Writing purpose (e.g. 'explanation', 'marketing', 'support', 'learning').</summary>
		public string? Purpose { get; set; }
		/// <summary>Evaluation strictness from 1 (lenient) to 5 (very strict).</summary>
		public int? Strictness { get; set; }
		/// <summary>Intended readers (e.g. 'developers', 'customers', 'students', 'executives').</summary>
		public string? TargetAudience { get; set; }

		public ScoreQualityInput(string text, int? maxSuggestions = null, string? purpose = null, int? strictness = null, string? targetAudience = null)
		{
			Text = text;
			MaxSuggestions = maxSuggestions;
			Purpose = purpose;
			Strictness = strictness;
			TargetAudience = targetAudience;
		}
	}

	public sealed class ScoreQualityOutput
	{
		/// <summary>How actionable and useful the text is, from 0 to 100.</summary>
		public int ActionabilityScore { get; }
		/// <summary>Clarity score from 0 to 100.</summary>
		public int ClarityScore { get; }
		/// <summary>Overall quality level.</summary>
		public string Level { get; }
		/// <summary>Overall quality score from 0 to 100.</summary>
		public int OverallScore { get; }
		/// <summary>Organization and logical structure score from 0 to 100.</summary>
		public int StructureScore { get; }
		/// <summary>Concise improvement suggestions, ordered by importance.</summary>
		public List<string> Suggestions { get; }
		/// <summary>One short sentence summarizing the evaluation.</summary>
		public string Summary { get; }
		/// <summary>Tone suitability score from 0 to 100.</summary>
		public int ToneScore { get; }

		public ScoreQualityOutput(int actionabilityScore, int clarityScore, string level, int overallScore, int structureScore, List<string> suggestions, string summary, int toneScore)
		{
			ActionabilityScore = actionabilityScore;
			ClarityScore = clarityScore;
			Level = level;
			OverallScore = overallScore;
			StructureScore = structureScore;
			Suggestions = suggestions;
			Summary = summary;
			ToneScore = toneScore;
		}
	}
}
