// Generated by aifn — do not edit manually.
// Package: score-quality v1.0.0

namespace Aifunc.ScoreQuality;

using System.Collections.Generic;

internal static class ScoreQualityAifunc
{
	internal static readonly Dictionary<string, object?> ARTIFACT_DATA =
		new Dictionary<string, object?>
		{
			["api"] = new Dictionary<string, object?>
			{
				["description"] = "Evaluate text quality across multiple dimensions and return structured scores with improvement advice.",
				["input"] = new Dictionary<string, object?>
				{
					["additionalProperties"] = false,
					["properties"] = new Dictionary<string, object?>
					{
						["maxSuggestions"] = new Dictionary<string, object?>
						{
							["default"] = (double)3,
							["description"] = "Maximum number of improvement suggestions to return.",
							["maximum"] = (double)10,
							["minimum"] = (double)1,
							["type"] = "integer",
						},
						["purpose"] = new Dictionary<string, object?>
						{
							["default"] = "general communication",
							["description"] = "Writing purpose (e.g. 'explanation', 'marketing', 'support', 'learning').",
							["type"] = "string",
						},
						["strictness"] = new Dictionary<string, object?>
						{
							["default"] = (double)3,
							["description"] = "Evaluation strictness from 1 (lenient) to 5 (very strict).",
							["maximum"] = (double)5,
							["minimum"] = (double)1,
							["type"] = "integer",
						},
						["targetAudience"] = new Dictionary<string, object?>
						{
							["default"] = "general readers",
							["description"] = "Intended readers (e.g. 'developers', 'customers', 'students', 'executives').",
							["type"] = "string",
						},
						["text"] = new Dictionary<string, object?>
						{
							["description"] = "The text content to evaluate.",
							["minLength"] = (double)1,
							["type"] = "string",
						},
					},
					["required"] = new List<object?>
					{
						"text",
					},
					["type"] = "object",
				},
				["name"] = "score-quality",
				["output"] = new Dictionary<string, object?>
				{
					["additionalProperties"] = false,
					["properties"] = new Dictionary<string, object?>
					{
						["actionabilityScore"] = new Dictionary<string, object?>
						{
							["description"] = "How actionable and useful the text is, from 0 to 100.",
							["maximum"] = (double)100,
							["minimum"] = (double)0,
							["type"] = "integer",
						},
						["clarityScore"] = new Dictionary<string, object?>
						{
							["description"] = "Clarity score from 0 to 100.",
							["maximum"] = (double)100,
							["minimum"] = (double)0,
							["type"] = "integer",
						},
						["level"] = new Dictionary<string, object?>
						{
							["description"] = "Overall quality level.",
							["enum"] = new List<object?>
							{
								"excellent",
								"good",
								"fair",
								"poor",
							},
							["type"] = "string",
						},
						["overallScore"] = new Dictionary<string, object?>
						{
							["description"] = "Overall quality score from 0 to 100.",
							["maximum"] = (double)100,
							["minimum"] = (double)0,
							["type"] = "integer",
						},
						["structureScore"] = new Dictionary<string, object?>
						{
							["description"] = "Organization and logical structure score from 0 to 100.",
							["maximum"] = (double)100,
							["minimum"] = (double)0,
							["type"] = "integer",
						},
						["suggestions"] = new Dictionary<string, object?>
						{
							["description"] = "Concise improvement suggestions, ordered by importance.",
							["items"] = new Dictionary<string, object?>
							{
								["type"] = "string",
							},
							["minItems"] = (double)0,
							["type"] = "array",
						},
						["summary"] = new Dictionary<string, object?>
						{
							["description"] = "One short sentence summarizing the evaluation.",
							["type"] = "string",
						},
						["toneScore"] = new Dictionary<string, object?>
						{
							["description"] = "Tone suitability score from 0 to 100.",
							["maximum"] = (double)100,
							["minimum"] = (double)0,
							["type"] = "integer",
						},
					},
					["required"] = new List<object?>
					{
						"overallScore",
						"clarityScore",
						"structureScore",
						"toneScore",
						"actionabilityScore",
						"level",
						"summary",
						"suggestions",
					},
					["type"] = "object",
				},
			},
			["artifactVersion"] = "0.1.0",
			["metadata"] = new Dictionary<string, object?>
			{
				["contentHash"] = "sha256:79d6f5a90194dede133d2c89da1e7e35c27718e490eea613107036895d42da73",
				["generatedAt"] = "2026-07-16T23:51:14Z",
				["sourcePackageVersion"] = "1.0.0",
			},
			["modelParams"] = new Dictionary<string, object?>
			{
				["rules"] = new List<object?>
				{
					new Dictionary<string, object?>
					{
						["match"] = new Dictionary<string, object?>
						{
							["pattern"] = ".*",
						},
						["params"] = new Dictionary<string, object?>
						{
							["maxTokens"] = (double)700,
							["temperature"] = 0.1,
							["topP"] = 0.9,
						},
					},
					new Dictionary<string, object?>
					{
						["match"] = new Dictionary<string, object?>
						{
							["models"] = new List<object?>
							{
								"gpt-4o-mini",
								"gpt-4o",
							},
						},
						["params"] = new Dictionary<string, object?>
						{
							["maxTokens"] = (double)650,
							["temperature"] = (double)0,
						},
						["providerParams"] = new Dictionary<string, object?>
						{
							["openai"] = new Dictionary<string, object?>
							{
								["reasoningEffort"] = "low",
							},
						},
					},
				},
				["schemaVersion"] = "0.1.0",
			},
			["package"] = new Dictionary<string, object?>
			{
				["author"] = new Dictionary<string, object?>
				{
					["name"] = "GildenEye",
				},
				["description"] = "Evaluate text quality across multiple dimensions and return structured scores with improvement advice.",
				["engine"] = "^0.2.0",
				["name"] = "score-quality",
				["type"] = "standalone",
				["version"] = "1.0.0",
			},
			["prompts"] = new Dictionary<string, object?>
			{
				["general"] = "# System\n\nYou are a strict text quality evaluation function. You must only return a JSON object in EXACTLY this format:\n{\"overallScore\": <0-100>, \"clarityScore\": <0-100>, \"structureScore\": <0-100>, \"toneScore\": <0-100>, \"actionabilityScore\": <0-100>, \"level\": \"<excellent|good|fair|poor>\", \"summary\": \"<one sentence>\", \"suggestions\": [\"...\"]}\n\nDo not output Markdown, do not include any extra explanation, and do not omit any fields.\n\nScoring dimensions:\n- overallScore: holistic usefulness and quality.\n- clarityScore: ease of understanding, precision, and lack of ambiguity.\n- structureScore: organization, flow, and logical sequencing.\n- toneScore: suitability for the target audience and purpose.\n- actionabilityScore: whether the reader can understand what to do or take away.\n\nLevel mapping:\n- excellent: overallScore >= 90\n- good: overallScore >= 75 and < 90\n- fair: overallScore >= 50 and < 75\n- poor: overallScore < 50\n\nsummary: one concise sentence summarizing the overall evaluation result.\n\nsuggestions: up to maxSuggestions concise, actionable improvement tips (default 3 if not specified).\n\n# User\n\nText to evaluate:\n{{text}}\n\nTarget audience:\n{{targetAudience}}\n\nPurpose:\n{{purpose}}\n\nMaximum suggestions:\n{{maxSuggestions}}\n\nStrictness from 1 to 5:\n{{strictness}}\n",
			},
			["schemaVersion"] = "0.1.0",
		};
}
