// Generated by aifn — do not edit manually.
// Package: generate-slug v1.0.0

namespace Aifunc.GenerateSlug;

using System.Collections.Generic;

internal static class GenerateSlugAifunc
{
	internal static readonly Dictionary<string, object?> ARTIFACT_DATA =
		new Dictionary<string, object?>
		{
			["api"] = new Dictionary<string, object?>
			{
				["description"] = "Generate an SEO-friendly URL slug, meta description, and tag suggestions from a title.",
				["input"] = new Dictionary<string, object?>
				{
					["additionalProperties"] = false,
					["properties"] = new Dictionary<string, object?>
					{
						["description"] = new Dictionary<string, object?>
						{
							["description"] = "Optional longer description to inform slug and meta generation.",
							["type"] = "string",
						},
						["language"] = new Dictionary<string, object?>
						{
							["description"] = "Content language hint (e.g. 'en', 'zh-CN'). Slug will always be ASCII.",
							["type"] = "string",
						},
						["title"] = new Dictionary<string, object?>
						{
							["description"] = "The article or page title.",
							["minLength"] = (double)1,
							["type"] = "string",
						},
					},
					["required"] = new List<object?>
					{
						"title",
					},
					["type"] = "object",
				},
				["name"] = "generate-slug",
				["output"] = new Dictionary<string, object?>
				{
					["additionalProperties"] = false,
					["properties"] = new Dictionary<string, object?>
					{
						["metaDescription"] = new Dictionary<string, object?>
						{
							["description"] = "SEO meta description (120-160 characters recommended).",
							["type"] = "string",
						},
						["slug"] = new Dictionary<string, object?>
						{
							["description"] = "URL-safe slug using lowercase ASCII letters, numbers, and hyphens.",
							["type"] = "string",
						},
						["tags"] = new Dictionary<string, object?>
						{
							["description"] = "Suggested tags or keywords for the content.",
							["items"] = new Dictionary<string, object?>
							{
								["type"] = "string",
							},
							["type"] = "array",
						},
					},
					["required"] = new List<object?>
					{
						"slug",
						"metaDescription",
						"tags",
					},
					["type"] = "object",
				},
			},
			["artifactVersion"] = "0.1.0",
			["metadata"] = new Dictionary<string, object?>
			{
				["contentHash"] = "sha256:0e508a60148b537c7c3e7f427f3d787db1bf8857add3c48eaae483496bdb9228",
				["generatedAt"] = "2026-07-12T14:20:06Z",
				["sourcePackageVersion"] = "1.0.0",
			},
			["modelParams"] = new Dictionary<string, object?>
			{
				["rules"] = new List<object?>
				{
					new Dictionary<string, object?>
					{
						["match"] = new Dictionary<string, object?>
						{
							["pattern"] = ".*",
						},
						["params"] = new Dictionary<string, object?>
						{
							["maxTokens"] = (double)400,
							["temperature"] = 0.3,
						},
					},
				},
				["schemaVersion"] = "0.1.0",
			},
			["package"] = new Dictionary<string, object?>
			{
				["author"] = new Dictionary<string, object?>
				{
					["name"] = "GildenEye",
				},
				["description"] = "Generate SEO-friendly URL slugs, meta descriptions, and tag suggestions from titles.",
				["engine"] = "^0.1.0",
				["name"] = "generate-slug",
				["type"] = "standalone",
				["version"] = "1.0.0",
			},
			["prompts"] = new Dictionary<string, object?>
			{
				["general"] = "# System\n\nYou are an SEO slug generation function. You must only return a JSON object in the following format:\n{\"slug\": \"<url-slug>\", \"metaDescription\": \"<description>\", \"tags\": [\"<tag>\", ...]}\n\nDo not output Markdown, do not include any extra explanation, and do not add undeclared fields.\n\nRequirements:\n- Generate a URL-safe `slug` from the title: lowercase ASCII, words separated by hyphens, no special characters. Keep it concise (3-8 words).\n- If the title is in a non-Latin language (e.g. Chinese, Japanese), translate the core meaning into English for the slug.\n- Generate a `metaDescription` that is compelling and SEO-friendly, between 120 and 160 characters. It should summarize the content and encourage clicks.\n- Suggest 3-6 relevant `tags` for categorization and discoverability.\n- Tags should be lowercase and in the content's language unless the language hint suggests otherwise.\n- The meta description should be in the same language as the title unless the content language is ambiguous.\n\n# User\n\nTitle: {{title}}\n\nDescription: {{description}}\n\nLanguage: {{language}}\n",
			},
			["schemaVersion"] = "0.1.0",
		};
}
