// Generated by aifn — do not edit manually.
// Package: article-stream v1.0.0

package aifunc.article_stream;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
@SuppressWarnings("serial")
final class ArticleStreamAifunc {

	private ArticleStreamAifunc() {}

	static final java.util.Map<String, Object> ARTIFACT_DATA =
		new java.util.LinkedHashMap<String, Object>() {{
			put("api", new java.util.LinkedHashMap<String, Object>() {{
				put("description", "Stream a full article from a title and optional outline. Returns plain text.");
				put("injectOutputSchema", false);
				put("input", new java.util.LinkedHashMap<String, Object>() {{
					put("additionalProperties", false);
					put("properties", new java.util.LinkedHashMap<String, Object>() {{
						put("audience", new java.util.LinkedHashMap<String, Object>() {{
							put("default", "general readers");
							put("description", "Target audience (e.g. 'general readers', 'developers', 'executives'). Default: 'general readers'.");
							put("type", "string");
						}});
						put("language", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Output language (e.g. 'English', 'Chinese'). If omitted, matches the title language.");
							put("type", "string");
						}});
						put("outline", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Optional outline or key points to cover, one per line or as free text.");
							put("type", "string");
						}});
						put("style", new java.util.LinkedHashMap<String, Object>() {{
							put("default", "informational");
							put("description", "Writing style or tone (e.g. 'informational', 'opinion', 'tutorial', 'news'). Default: 'informational'.");
							put("type", "string");
						}});
						put("title", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "The article title.");
							put("minLength", 1L);
							put("type", "string");
						}});
						put("wordCount", new java.util.LinkedHashMap<String, Object>() {{
							put("default", 600L);
							put("description", "Approximate target word count. Default: 600. Range: 200–3000.");
							put("maximum", 3000L);
							put("minimum", 200L);
							put("type", "integer");
						}});
					}});
					put("required", new java.util.ArrayList<Object>(java.util.Arrays.asList(
						"title"
					)));
					put("type", "object");
				}});
				put("name", "article_stream");
				put("output", new java.util.LinkedHashMap<String, Object>() {{
					put("description", "The generated article as plain text.");
					put("type", "string");
					put("x-delivery-mode", "stream");
				}});
			}});
			put("artifactVersion", "0.1.0");
			put("metadata", new java.util.LinkedHashMap<String, Object>() {{
				put("contentHash", "sha256:9a83ec7607ab16702eb54a265fb7d0a9a7f27b8db590992c798e3c381c5fa3f2");
				put("generatedAt", "2026-07-17T10:45:42Z");
				put("sourcePackageVersion", "1.0.0");
			}});
			put("modelParams", new java.util.LinkedHashMap<String, Object>() {{
				put("rules", new java.util.ArrayList<Object>(java.util.Arrays.asList(
					new java.util.LinkedHashMap<String, Object>() {{
						put("match", new java.util.LinkedHashMap<String, Object>() {{
							put("pattern", ".*");
						}});
						put("params", new java.util.LinkedHashMap<String, Object>() {{
							put("maxTokens", 4096L);
							put("temperature", 0.75);
						}});
					}}
				)));
				put("schemaVersion", "0.1.0");
			}});
			put("package", new java.util.LinkedHashMap<String, Object>() {{
				put("author", new java.util.LinkedHashMap<String, Object>() {{
					put("name", "GildenEye");
				}});
				put("description", "Stream a full article from a title and optional outline. Returns plain text.");
				put("engine", "^0.2.0");
				put("engineOptions", new java.util.LinkedHashMap<String, Object>() {{
					put("injectOutputSchema", false);
				}});
				put("name", "article-stream");
				put("type", "standalone");
				put("version", "1.0.0");
			}});
			put("prompts", new java.util.LinkedHashMap<String, Object>() {{
				put("general", "# System\n\nYou are a professional article writer. Your task is to write a complete, well-structured article based on the given title and optional outline.\n\n## Requirements\n\n- Write approximately {{input.wordCount}} words of article prose.\n- Style: {{input.style}} — match the appropriate tone and structure for this style.\n- Target audience: {{input.audience}} — calibrate vocabulary, depth, and assumed knowledge accordingly.\n- If an outline is provided, follow it as the structural backbone. If not, devise a logical structure yourself.\n- Begin directly with the article body. Do not include a title header, preamble, or any meta-commentary.\n- Output plain text only — no Markdown formatting, no JSON, no labels.\n- If a language is specified, write in that language. Otherwise, match the language of the title.\n- The article must be coherent, informative, and flow naturally from introduction to conclusion.\n\n## Input\n\nTitle: {{input.title}}\n\nOutline: {{input.outline}}\n\nStyle: {{input.style}}\n\nAudience: {{input.audience}}\n\nLanguage: {{input.language}}\n\nWord count target: {{input.wordCount}}\n");
			}});
			put("schemaVersion", "0.1.0");
		}};
}
