// Generated by aifn — do not edit manually.
// Package: article-stream v1.0.0

package aifunc.article_stream;

import aifunc.AIFuncConfig;
import aifunc._engine.java.v0_2_0.Runtime;
import aifunc._engine.java.v0_2_0.Artifact;
import aifunc._engine.java.v0_2_0.Types.AIFuncArtifact;
import java.util.LinkedHashMap;
import java.util.Map;

/** Stream a full article from a title and optional outline. Returns plain text. */
/** Generated by aifn — do not edit manually. */
public final class ArticleStream {

	private ArticleStream() {}

	/**
	 * Stream tokens from the model.
	 * Returns a {@link ArticleStreamTypes.TokenStream} — use it in a try-with-resources block;
	 * {@code break} automatically cancels the stream and frees the background thread.
	 */
	public static ArticleStreamTypes.TokenStream articleStream(AIFuncConfig config, ArticleStreamTypes.ArticleStreamInput input) {
		if (config == null) config = AIFuncConfig.builder().build();

		AIFuncArtifact artifact = Artifact.fromMap(ArticleStreamAifunc.ARTIFACT_DATA);
		Map<String, Object> inputMap = inputToMap(input);
		return new ArticleStreamTypes.TokenStream(Runtime.executeStream(artifact, inputMap, config));
	}

	private static Map<String, Object> inputToMap(ArticleStreamTypes.ArticleStreamInput input) {
		Map<String, Object> m = new LinkedHashMap<>();
		if (input.getAudience() != null) m.put("audience", input.getAudience());
		if (input.getLanguage() != null) m.put("language", input.getLanguage());
		if (input.getOutline() != null) m.put("outline", input.getOutline());
		if (input.getStyle() != null) m.put("style", input.getStyle());
		m.put("title", input.getTitle());
		if (input.getWordCount() != null) m.put("wordCount", input.getWordCount());
		return m;
	}
}

