// Generated by aifn — do not edit manually.
// Package: extract-keywords v1.0.0

namespace Aifunc.ExtractKeywords;

using System.Collections.Generic;

internal static class ExtractKeywordsAifunc
{
	internal static readonly Dictionary<string, object?> ARTIFACT_DATA =
		new Dictionary<string, object?>
		{
			["api"] = new Dictionary<string, object?>
			{
				["description"] = "Extract keywords and key phrases from text, ranked by relevance.",
				["input"] = new Dictionary<string, object?>
				{
					["additionalProperties"] = false,
					["properties"] = new Dictionary<string, object?>
					{
						["maxKeywords"] = new Dictionary<string, object?>
						{
							["default"] = (double)10,
							["description"] = "Maximum number of keywords to return. Defaults to 10.",
							["maximum"] = (double)50,
							["minimum"] = (double)1,
							["type"] = "integer",
						},
						["text"] = new Dictionary<string, object?>
						{
							["description"] = "The text to extract keywords from.",
							["minLength"] = (double)1,
							["type"] = "string",
						},
					},
					["required"] = new List<object?>
					{
						"text",
					},
					["type"] = "object",
				},
				["name"] = "extract-keywords",
				["output"] = new Dictionary<string, object?>
				{
					["additionalProperties"] = false,
					["properties"] = new Dictionary<string, object?>
					{
						["keywords"] = new Dictionary<string, object?>
						{
							["description"] = "Extracted keywords sorted by relevance (highest first).",
							["items"] = new Dictionary<string, object?>
							{
								["additionalProperties"] = false,
								["properties"] = new Dictionary<string, object?>
								{
									["relevance"] = new Dictionary<string, object?>
									{
										["description"] = "Relevance score between 0 and 1.",
										["maximum"] = (double)1,
										["minimum"] = (double)0,
										["type"] = "number",
									},
									["word"] = new Dictionary<string, object?>
									{
										["description"] = "The keyword or key phrase.",
										["type"] = "string",
									},
								},
								["required"] = new List<object?>
								{
									"word",
									"relevance",
								},
								["type"] = "object",
							},
							["type"] = "array",
						},
					},
					["required"] = new List<object?>
					{
						"keywords",
					},
					["type"] = "object",
				},
			},
			["artifactVersion"] = "0.1.0",
			["metadata"] = new Dictionary<string, object?>
			{
				["contentHash"] = "sha256:f9b675229aa079c3225565e76baef7270f03bc30e31ea6c4e17673afbe90ea90",
				["generatedAt"] = "2026-07-16T23:51:14Z",
				["sourcePackageVersion"] = "1.0.0",
			},
			["modelParams"] = new Dictionary<string, object?>
			{
				["rules"] = new List<object?>
				{
					new Dictionary<string, object?>
					{
						["match"] = new Dictionary<string, object?>
						{
							["pattern"] = ".*",
						},
						["params"] = new Dictionary<string, object?>
						{
							["maxTokens"] = (double)600,
							["temperature"] = 0.1,
						},
					},
				},
				["schemaVersion"] = "0.1.0",
			},
			["package"] = new Dictionary<string, object?>
			{
				["author"] = new Dictionary<string, object?>
				{
					["name"] = "GildenEye",
				},
				["description"] = "Extract keywords and key phrases from text with relevance scores.",
				["engine"] = "^0.2.0",
				["name"] = "extract-keywords",
				["type"] = "standalone",
				["version"] = "1.0.0",
			},
			["prompts"] = new Dictionary<string, object?>
			{
				["general"] = "# System\n\nYou are a keyword extraction function. You must only return a JSON object in the following format:\n{\"keywords\": [{\"word\": \"<keyword>\", \"relevance\": <0-1>}, ...]}\n\nDo not output Markdown, do not include any extra explanation, and do not add undeclared fields.\n\nRequirements:\n- Extract the most important keywords and key phrases from the input text.\n- Rank them by relevance to the text's core topics, with the most relevant first.\n- `relevance` should be a float between 0 and 1, where 1 means the keyword is central to the text.\n- Prefer concise phrases (1-3 words) over single characters or overly long phrases.\n- Do not return duplicates or near-duplicates (e.g. singular and plural forms of the same word).\n- Return at most `maxKeywords` results; if not specified, default to 10.\n- Keywords should be in the same language as the input text.\n\n# User\n\nText:\n{{text}}\n\nMaximum keywords: {{maxKeywords}}\n",
			},
			["schemaVersion"] = "0.1.0",
		};
}
