// Generated by aifn — do not edit manually.
// Package: extract-keywords v1.0.0

namespace Aifunc.ExtractKeywords;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Aifunc;
using Aifunc.Engine.Csharp.V0_1_0;

/// <summary>Extract keywords and key phrases from text, ranked by relevance.</summary>
public static class ExtractKeywords
{
	private static readonly object? MOCK_DATA = ExtractKeywordsAifuncMock.MOCK_DATA;

	public static async Task<ExtractKeywordsTypes.ExtractKeywordsOutput> ExtractKeywordsAsync(AIFuncConfig? config, ExtractKeywordsTypes.ExtractKeywordsInput input)
	{
		if (config is null)
			config = new AIFuncConfig { Mock = true, MockData = MOCK_DATA };
		else if (config.Mock && config.MockData is null)
			config = config.WithMockData(MOCK_DATA);


		var artifact = Artifact.FromMap(ExtractKeywordsAifunc.ARTIFACT_DATA);
		var inputMap = InputToMap(input);
		var result = await Runtime.ExecuteAsync(artifact, inputMap, config).ConfigureAwait(false);
		return MapToOutput(result);
	}

	private static Dictionary<string, object?> InputToMap(ExtractKeywordsTypes.ExtractKeywordsInput input)
	{
		var m = new Dictionary<string, object?>();
		if (input.MaxKeywords is not null) m["maxKeywords"] = input.MaxKeywords;
		m["text"] = input.Text;
		return m;
	}

	private static ExtractKeywordsTypes.ExtractKeywordsOutput MapToOutput(Dictionary<string, object?> m)
	{
		List<Dictionary<string, object?>> keywords;
		if (m.TryGetValue("keywords", out var _v0))
			keywords = _v0 is List<Dictionary<string, object?>> _l0 ? _l0 : new List<Dictionary<string, object?>>();
		else
			keywords = new List<Dictionary<string, object?>>();
		return new ExtractKeywordsTypes.ExtractKeywordsOutput(keywords);
	}
}
