// Generated by aifn — do not edit manually.
// Package: generate-reply v1.0.0

namespace Aifunc.GenerateReply;

using System.Collections.Generic;

public static class GenerateReplyTypes
{
	public sealed class GenerateReplyInput
	{
		/// <summary>The original message or comment to reply to.</summary>
		public string Message { get; }
		/// <summary>Background context to inform the reply (e.g. role, situation).</summary>
		public string? Context { get; set; }
		/// <summary>Reply language. If omitted, matches the input message language.</summary>
		public string? Language { get; set; }
		/// <summary>Desired tone: 'friendly', 'formal', 'empathetic', 'concise'. Default: 'friendly'.</summary>
		public string? Tone { get; set; }

		public GenerateReplyInput(string message, string? context = null, string? language = null, string? tone = null)
		{
			Message = message;
			Context = context;
			Language = language;
			Tone = tone;
		}
	}

	public sealed class GenerateReplyOutput
	{
		/// <summary>The generated reply text.</summary>
		public string Reply { get; }

		public GenerateReplyOutput(string reply)
		{
			Reply = reply;
		}
	}
}
