// Generated by aifn — do not edit manually.
// Package: extract-keywords v1.0.0

package aifunc.extract_keywords;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
@SuppressWarnings("serial")
final class ExtractKeywordsAifuncMock {

	private ExtractKeywordsAifuncMock() {}

	static final Object MOCK_DATA =
		new java.util.LinkedHashMap<String, Object>() {{
			put("cases", new java.util.ArrayList<Object>(java.util.Arrays.asList(
				new java.util.LinkedHashMap<String, Object>() {{
					put("description", "Keyword extraction from a tech article.");
					put("id", "tech-article");
					put("output", new java.util.LinkedHashMap<String, Object>() {{
						put("keywords", new java.util.ArrayList<Object>(java.util.Arrays.asList(
							new java.util.LinkedHashMap<String, Object>() {{
								put("relevance", 0.95);
								put("word", "machine learning");
							}},
							new java.util.LinkedHashMap<String, Object>() {{
								put("relevance", 0.88);
								put("word", "neural network");
							}},
							new java.util.LinkedHashMap<String, Object>() {{
								put("relevance", 0.82);
								put("word", "deep learning");
							}},
							new java.util.LinkedHashMap<String, Object>() {{
								put("relevance", 0.75);
								put("word", "training data");
							}},
							new java.util.LinkedHashMap<String, Object>() {{
								put("relevance", 0.7);
								put("word", "model accuracy");
							}}
						)));
					}});
				}}
			)));
			put("delay", new java.util.LinkedHashMap<String, Object>() {{
				put("maxMs", 100L);
				put("minMs", 30L);
			}});
			put("random", new java.util.LinkedHashMap<String, Object>() {{
				put("enabled", false);
				put("seed", "keyword-extract");
			}});
			put("version", "1.0.0");
		}};
}
