// Generated by aifn -- do not edit manually.
// Package: generate-slug v1.0.0

package generate_slug

import (
	"context"
	"fmt"

	engine "all-packages/aifunc/_engine/go/v0.2.0"
)

// AIFuncConfig controls the runtime mode and model connection.
type AIFuncConfig = engine.AIFuncConfig

// mockData contains the built-in offline test cases.
var mockData any = generate_slugMockData

// GenerateSlug Generate an SEO-friendly URL slug, meta description, and tag suggestions from a title.
func GenerateSlug(ctx context.Context, config *AIFuncConfig, input GenerateSlugInput) (GenerateSlugOutput, error) {
	if config == nil {
		config = &AIFuncConfig{Mock: true, MockData: mockData}
	}
	if config.Mock && config.MockData == nil {
		copy := *config
		copy.MockData = mockData
		config = &copy
	}

	artifact, err := engine.ArtifactFromMap(artifactData)
	if err != nil {
		return GenerateSlugOutput{}, fmt.Errorf("load artifact: %w", err)
	}

	inputMap := inputToMap(input)

	result, err := engine.Execute(ctx, artifact, inputMap, *config)
	if err != nil {
		return GenerateSlugOutput{}, err
	}

	return mapToOutput(result), nil
}

func inputToMap(input GenerateSlugInput) map[string]any {
	m := map[string]any{}
	if input.Description != nil { m["description"] = *input.Description }
	if input.Language != nil { m["language"] = *input.Language }
	m["title"] = input.Title
	return m
}

func mapToOutput(m map[string]any) GenerateSlugOutput {
	var out GenerateSlugOutput
	if v, ok := m["metaDescription"]; ok { out.MetaDescription = coerceString(v) }
	if v, ok := m["slug"]; ok { out.Slug = coerceString(v) }
	if v, ok := m["tags"]; ok { out.Tags = coerceSliceString(v) }
	return out
}

func coerceString(v any) string {
	if s, ok := v.(string); ok { return s }
	return fmt.Sprintf("%v", v)
}

func coerceSliceString(v any) []string {
	if s, ok := v.([]string); ok { return s }
	if s, ok := v.([]any); ok {
		out := make([]string, 0, len(s))
		for _, item := range s {
			if str, ok := item.(string); ok {
				out = append(out, str)
			} else {
				out = append(out, fmt.Sprintf("%v", item))
			}
		}
		return out
	}
	return nil
}

