// Generated by aifn — do not edit manually.
// Package: summarize v1.0.0

package aifunc.summarize;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
@SuppressWarnings("serial")
final class SummarizeAifuncMock {

	private SummarizeAifuncMock() {}

	static final Object MOCK_DATA =
		new java.util.LinkedHashMap<String, Object>() {{
			put("cases", new java.util.ArrayList<Object>(java.util.Arrays.asList(
				new java.util.LinkedHashMap<String, Object>() {{
					put("description", "Basic summary example.");
					put("id", "basic-summary");
					put("output", new java.util.LinkedHashMap<String, Object>() {{
						put("summary", "This article introduces a common AI function for generating concise summaries from input text.");
						put("wordCount", 16L);
					}});
				}}
			)));
			put("delay", new java.util.LinkedHashMap<String, Object>() {{
				put("maxMs", 100L);
				put("minMs", 30L);
			}});
			put("random", new java.util.LinkedHashMap<String, Object>() {{
				put("enabled", false);
				put("seed", "short-summary");
			}});
			put("version", "1.0.0");
		}};
}
