// Generated by aifn -- do not edit manually.
// Package: extract-json v1.0.0

package extract_json

// ExtractJsonInput holds the input parameters.
type ExtractJsonInput struct {
	// Schema describing the fields to extract.
	Fields []map[string]any
	// The natural language text to extract information from.
	Text string
}

// ExtractJsonOutput holds the function result.
type ExtractJsonOutput struct {
	// Extracted key-value pairs matching the requested fields.
	Extracted map[string]any
	// Field names that could not be found in the text.
	Missing []string
}
