// Generated by aifn -- do not edit manually.
// Package: analyze-sentiment v1.0.0

package analyze_sentiment

// AnalyzeSentimentInput holds the input parameters.
type AnalyzeSentimentInput struct {
	// The text to analyze sentiment for.
	Text string
	// Candidate sentiment labels. Defaults to ["positive", "negative", "neutral"].
	Labels []string
	// Return only the top K labels by score. If omitted, return all.
	TopK *int
}

// AnalyzeSentimentOutput holds the function result.
type AnalyzeSentimentOutput struct {
	// Confidence score of the top label, between 0 and 1.
	Confidence float64
	// The highest-scoring sentiment label.
	Label string
	// All labels ranked by score (highest first), limited by topK.
	Rankings []map[string]any
}
