// Generated by aifn — do not edit manually.
// Package: generate-title v1.0.0

package aifunc.generate_title;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
@SuppressWarnings("serial")
final class GenerateTitleAifuncMock {

	private GenerateTitleAifuncMock() {}

	static final Object MOCK_DATA =
		new java.util.LinkedHashMap<String, Object>() {{
			put("cases", new java.util.ArrayList<Object>(java.util.Arrays.asList(
				new java.util.LinkedHashMap<String, Object>() {{
					put("description", "Generate neutral title candidates for a blog post.");
					put("id", "blog-titles");
					put("output", new java.util.LinkedHashMap<String, Object>() {{
						put("titles", new java.util.ArrayList<Object>(java.util.Arrays.asList(
							"How to Build Better Habits That Actually Stick",
							"The Science Behind Lasting Habit Formation",
							"A Practical Guide to Changing Your Daily Routines"
						)));
					}});
				}}
			)));
			put("delay", new java.util.LinkedHashMap<String, Object>() {{
				put("maxMs", 120L);
				put("minMs", 30L);
			}});
			put("random", new java.util.LinkedHashMap<String, Object>() {{
				put("enabled", false);
				put("seed", "generate-title");
			}});
			put("version", "1.0.0");
		}};
}
