// Generated by aifn — do not edit manually.
// Package: generate-title v1.0.0

package aifunc.generate_title;

import aifunc.AIFuncConfig;
import aifunc._engine.java.v0_2_0.Runtime;
import aifunc._engine.java.v0_2_0.Artifact;
import aifunc._engine.java.v0_2_0.Types.AIFuncArtifact;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

/** Generate title or headline candidates for a piece of content. */
/** Generated by aifn — do not edit manually. */
public final class GenerateTitle {

	private GenerateTitle() {}

	private static final Object MOCK_DATA = GenerateTitleAifuncMock.MOCK_DATA;

	public static CompletableFuture<GenerateTitleTypes.GenerateTitleOutput> generateTitle(AIFuncConfig config, GenerateTitleTypes.GenerateTitleInput input) {
		if (config == null) {
			config = AIFuncConfig.builder().mock(true).mockData(MOCK_DATA).build();
		} else if (config.isMock() && config.getMockData() == null) {
			config = config.toBuilder().mockData(MOCK_DATA).build();
		}

		AIFuncArtifact artifact = Artifact.fromMap(GenerateTitleAifunc.ARTIFACT_DATA);
		Map<String, Object> inputMap = inputToMap(input);
		return Runtime.executeAsync(artifact, inputMap, config)
			.thenApply(GenerateTitle::mapToOutput);
	}

	private static Map<String, Object> inputToMap(GenerateTitleTypes.GenerateTitleInput input) {
		Map<String, Object> m = new LinkedHashMap<>();
		m.put("content", input.getContent());
		if (input.getCount() != null) m.put("count", input.getCount());
		if (input.getMaxLength() != null) m.put("maxLength", input.getMaxLength());
		if (input.getStyle() != null) m.put("style", input.getStyle());
		return m;
	}

	@SuppressWarnings("unchecked")
	private static GenerateTitleTypes.GenerateTitleOutput mapToOutput(Map<String, Object> m) {
		java.util.List<String> titles = m.containsKey("titles") ? (m.get("titles") instanceof java.util.List<?>) ? (java.util.List<String>) m.get("titles") : null : null;
		return new GenerateTitleTypes.GenerateTitleOutput(titles);
	}
}
