// Generated by aifn -- do not edit manually.
// Package: explain-stream v1.0.0

package explain_stream

// ExplainStreamInput holds the input parameters.
type ExplainStreamInput struct {
	// The concept, code snippet, or term to explain.
	Topic string
	// Target audience level (e.g. 'beginner', 'intermediate', 'expert', 'non-technical'). Default: 'intermediate'.
	Audience *string
	// Optional surrounding context (e.g. the file or system the code belongs to, or the domain the term is used in).
	Context *string
	// Explanation depth: 'brief' (2-3 sentences), 'standard' (1-2 paragraphs), 'detailed' (full breakdown with examples). Default: 'standard'.
	Depth *string
	// Output language. If omitted, matches the language of the topic.
	Language *string
}
