// Generated by aifn — do not edit manually.
// Package: classify v1.0.0

namespace Aifunc.Classify;

using System.Collections.Generic;

public static class ClassifyTypes
{
	public sealed class ClassifyInput
	{
		/// <summary>The text to classify.</summary>
		public string Text { get; }
		/// <summary>List of candidate categories to classify into.</summary>
		public List<string> Categories { get; }
		/// <summary>If true, the text can be assigned to multiple categories. Defaults to false.</summary>
		public bool? AllowMultiple { get; set; }

		public ClassifyInput(string text, List<string> categories, bool? allowMultiple = null)
		{
			Text = text;
			Categories = categories;
			AllowMultiple = allowMultiple;
		}
	}

	public sealed class ClassifyOutput
	{
		/// <summary>Classification results sorted by confidence (highest first).</summary>
		public List<Classification> Classifications { get; }

		public ClassifyOutput(List<Classification> classifications)
		{
			Classifications = classifications;
		}
	}

	public sealed class Classification
	{
		/// <summary>The category label.</summary>
		public string Category { get; }
		/// <summary>Confidence score between 0 and 1.</summary>
		public double Confidence { get; }

		public Classification(string category, double confidence)
		{
			Category = category;
			Confidence = confidence;
		}
	}
}
