// Generated by aifn — do not edit manually.
// Package: classify v1.0.0

namespace Aifunc.Classify;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Aifunc;
using Aifunc.Engine.Csharp.V0_2_0;

/// <summary>Classify text into user-defined categories with confidence scores.</summary>
public static class Classify
{
	private static readonly object? MOCK_DATA = ClassifyAifuncMock.MOCK_DATA;

	public static async Task<ClassifyTypes.ClassifyOutput> ClassifyAsync(AIFuncConfig? config, ClassifyTypes.ClassifyInput input)
	{
		if (config is null)
			config = new AIFuncConfig { Mock = true, MockData = MOCK_DATA };
		else if (config.Mock && config.MockData is null)
			config = config.WithMockData(MOCK_DATA);


		var artifact = Artifact.FromMap(ClassifyAifunc.ARTIFACT_DATA);
		var inputMap = InputToMap(input);
		var result = await Runtime.ExecuteAsync(artifact, inputMap, config).ConfigureAwait(false);
		return MapToOutput(result);
	}

	private static System.Collections.Generic.Dictionary<string, object?> InputToMap(ClassifyTypes.ClassifyInput input)
	{
		var m = new System.Collections.Generic.Dictionary<string, object?>();
		if (input.AllowMultiple is not null) m["allowMultiple"] = input.AllowMultiple;
		m["categories"] = input.Categories;
		m["text"] = input.Text;
		return m;
	}

	private static ClassifyTypes.ClassifyOutput MapToOutput(Dictionary<string, object?> m)
	{
		List<ClassifyTypes.Classification> classifications;
		if (m.TryGetValue("classifications", out var _v0))
			classifications = (_v0 is System.Collections.IEnumerable _en0
				? _en0.Cast<object?>().Select(_item0 =>
				{
					var _d0 = _item0 as Dictionary<string, object?> ?? new Dictionary<string, object?>();
					return new ClassifyTypes.Classification((_d0.TryGetValue("category", out var _nv0_0) ? _nv0_0 is string _s0 ? _s0 : (_nv0_0?.ToString() ?? "") : ""), (_d0.TryGetValue("confidence", out var _nv0_1) ? _nv0_1 is IConvertible _c1 ? Convert.ToDouble(_c1) : 0.0 : 0.0));
				}).ToList()
				: new List<ClassifyTypes.Classification>());
		else
			classifications = new List<ClassifyTypes.Classification>();
		return new ClassifyTypes.ClassifyOutput(classifications);
	}
}
