// Generated by aifn — do not edit manually.
// Package: classify v1.0.0

namespace Aifunc.Classify;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Aifunc;
using Aifunc.Engine.Csharp.V0_1_0;

/// <summary>Classify text into user-defined categories with confidence scores.</summary>
public static class Classify
{
	private static readonly object? MOCK_DATA = ClassifyAifuncMock.MOCK_DATA;

	public static async Task<ClassifyTypes.ClassifyOutput> ClassifyAsync(AIFuncConfig? config, ClassifyTypes.ClassifyInput input)
	{
		if (config is null)
			config = new AIFuncConfig { Mock = true, MockData = MOCK_DATA };
		else if (config.Mock && config.MockData is null)
			config = config.WithMockData(MOCK_DATA);


		var artifact = Artifact.FromMap(ClassifyAifunc.ARTIFACT_DATA);
		var inputMap = InputToMap(input);
		var result = await Runtime.ExecuteAsync(artifact, inputMap, config).ConfigureAwait(false);
		return MapToOutput(result);
	}

	private static Dictionary<string, object?> InputToMap(ClassifyTypes.ClassifyInput input)
	{
		var m = new Dictionary<string, object?>();
		if (input.AllowMultiple is not null) m["allowMultiple"] = input.AllowMultiple;
		m["categories"] = input.Categories;
		m["text"] = input.Text;
		return m;
	}

	private static ClassifyTypes.ClassifyOutput MapToOutput(Dictionary<string, object?> m)
	{
		List<Dictionary<string, object?>> classifications;
		if (m.TryGetValue("classifications", out var _v0))
			classifications = _v0 is List<Dictionary<string, object?>> _l0 ? _l0 : new List<Dictionary<string, object?>>();
		else
			classifications = new List<Dictionary<string, object?>>();
		return new ClassifyTypes.ClassifyOutput(classifications);
	}
}
