// Generated by aifn — do not edit manually.
// Package: translate-stream v1.0.0

package aifunc.translate_stream;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
@SuppressWarnings("serial")
final class TranslateStreamAifunc {

	private TranslateStreamAifunc() {}

	static final java.util.Map<String, Object> ARTIFACT_DATA =
		new java.util.LinkedHashMap<String, Object>() {{
			put("api", new java.util.LinkedHashMap<String, Object>() {{
				put("description", "Stream the translation of a long document or text. Returns plain text.");
				put("injectOutputSchema", false);
				put("input", new java.util.LinkedHashMap<String, Object>() {{
					put("additionalProperties", false);
					put("properties", new java.util.LinkedHashMap<String, Object>() {{
						put("domain", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Subject domain hint to improve terminology accuracy (e.g. 'legal', 'medical', 'technical', 'literary'). Optional.");
							put("type", "string");
						}});
						put("sourceLang", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Source language. If omitted, it is auto-detected.");
							put("type", "string");
						}});
						put("style", new java.util.LinkedHashMap<String, Object>() {{
							put("default", "natural");
							put("description", "Translation style: 'literal' (close to source), 'natural' (idiomatic), 'formal'. Default: 'natural'.");
							put("enum", new java.util.ArrayList<Object>(java.util.Arrays.asList(
								"literal",
								"natural",
								"formal"
							)));
							put("type", "string");
						}});
						put("targetLang", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Target language (e.g. 'Chinese', 'English', 'French', 'zh-CN').");
							put("minLength", 1L);
							put("type", "string");
						}});
						put("text", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "The text or document to translate.");
							put("minLength", 1L);
							put("type", "string");
						}});
					}});
					put("required", new java.util.ArrayList<Object>(java.util.Arrays.asList(
						"text",
						"targetLang"
					)));
					put("type", "object");
				}});
				put("name", "translate_stream");
				put("output", new java.util.LinkedHashMap<String, Object>() {{
					put("description", "The translated text as plain text.");
					put("type", "string");
					put("x-delivery-mode", "stream");
				}});
			}});
			put("artifactVersion", "0.1.0");
			put("metadata", new java.util.LinkedHashMap<String, Object>() {{
				put("contentHash", "sha256:a267da318ceb7823ce27f36b267848bc42c2320a0b3dcb98c15acc8a07a6a657");
				put("generatedAt", "2026-07-19T12:17:24Z");
				put("sourcePackageVersion", "1.0.0");
			}});
			put("modelParams", new java.util.LinkedHashMap<String, Object>() {{
				put("rules", new java.util.ArrayList<Object>(java.util.Arrays.asList(
					new java.util.LinkedHashMap<String, Object>() {{
						put("match", new java.util.LinkedHashMap<String, Object>() {{
							put("pattern", ".*");
						}});
						put("params", new java.util.LinkedHashMap<String, Object>() {{
							put("maxTokens", 8192L);
							put("temperature", 0.2);
						}});
					}}
				)));
				put("schemaVersion", "0.1.0");
			}});
			put("package", new java.util.LinkedHashMap<String, Object>() {{
				put("author", new java.util.LinkedHashMap<String, Object>() {{
					put("name", "GildenEye");
				}});
				put("description", "Stream the translation of a long document or text. Returns plain text.");
				put("engine", "^0.2.0");
				put("engineOptions", new java.util.LinkedHashMap<String, Object>() {{
					put("injectOutputSchema", false);
				}});
				put("name", "translate-stream");
				put("type", "standalone");
				put("version", "1.0.0");
			}});
			put("prompts", new java.util.LinkedHashMap<String, Object>() {{
				put("general", "# System\n\nYou are a professional translator. Your task is to translate the provided text into the target language accurately and fluently.\n\n## Requirements\n\n- Translate into: {{input.targetLang}}\n- Source language: {{input.sourceLang}} (if not specified, detect automatically)\n- Translation style: {{input.style}}\n  - \"literal\": stay close to the source structure and wording\n  - \"natural\": produce idiomatic, fluent prose that reads as if originally written in the target language\n  - \"formal\": use formal register and polished language appropriate for official or professional contexts\n- Domain: {{input.domain}} — if specified, apply domain-specific terminology conventions\n- Output only the translated text — no notes, no commentary, no labels, no original text\n- Preserve paragraph breaks and structural whitespace from the original\n- Do not translate proper names, brand names, or code identifiers unless there is a well-established target-language equivalent\n\n## Input\n\n{{input.text}}\n");
			}});
			put("schemaVersion", "0.1.0");
		}};
}
