// Generated by aifn -- do not edit manually.
// Package: write-stream v1.0.0

import { executeStream } from '../_engine/typescript/v0.2.0/index';
import type { AIFuncArtifact, AIFuncConfig } from '../_engine/typescript/v0.2.0/index';
import artifact from './write-stream.aifunc';
import type { WriteStreamInput, WriteStreamOutput } from './write-stream.types';

export type { AIFuncConfig, WriteStreamInput, WriteStreamOutput };

/** Stream long-form writing — articles, reports, or documents — from a prompt and optional structure. Returns plain text. */
export async function* writeStream(config: AIFuncConfig = {}, input: WriteStreamInput): AsyncIterable<WriteStreamOutput> {
  const _projectDefaults = {};

  const runtimeConfig: AIFuncConfig = config;

  yield* executeStream(
    artifact as AIFuncArtifact,
    input as unknown as Record<string, unknown>,
    runtimeConfig,
    _projectDefaults,
  );
}
