// Generated by aifn — do not edit manually.
// Package: generate-reply v1.0.0

package aifunc.generate_reply;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
@SuppressWarnings("serial")
final class GenerateReplyAifunc {

	private GenerateReplyAifunc() {}

	static final java.util.Map<String, Object> ARTIFACT_DATA =
		new java.util.LinkedHashMap<String, Object>() {{
			put("api", new java.util.LinkedHashMap<String, Object>() {{
				put("description", "Generate a contextually appropriate reply to a message or comment.");
				put("input", new java.util.LinkedHashMap<String, Object>() {{
					put("additionalProperties", false);
					put("properties", new java.util.LinkedHashMap<String, Object>() {{
						put("context", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Background context to inform the reply (e.g. role, situation).");
							put("type", "string");
						}});
						put("language", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Reply language. If omitted, matches the input message language.");
							put("type", "string");
						}});
						put("message", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "The original message or comment to reply to.");
							put("minLength", 1L);
							put("type", "string");
						}});
						put("tone", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Desired tone: 'friendly', 'formal', 'empathetic', 'concise'. Default: 'friendly'.");
							put("type", "string");
						}});
					}});
					put("required", new java.util.ArrayList<Object>(java.util.Arrays.asList(
						"message"
					)));
					put("type", "object");
				}});
				put("name", "generate-reply");
				put("output", new java.util.LinkedHashMap<String, Object>() {{
					put("additionalProperties", false);
					put("properties", new java.util.LinkedHashMap<String, Object>() {{
						put("reply", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "The generated reply text.");
							put("type", "string");
						}});
					}});
					put("required", new java.util.ArrayList<Object>(java.util.Arrays.asList(
						"reply"
					)));
					put("type", "object");
				}});
			}});
			put("artifactVersion", "0.1.0");
			put("metadata", new java.util.LinkedHashMap<String, Object>() {{
				put("contentHash", "sha256:bd15142db6ed0425bb35a1ae82edfeb3700680180b576b8592b4f74ce5b459f1");
				put("generatedAt", "2026-07-12T06:36:23Z");
				put("sourcePackageVersion", "1.0.0");
			}});
			put("modelParams", new java.util.LinkedHashMap<String, Object>() {{
				put("rules", new java.util.ArrayList<Object>(java.util.Arrays.asList(
					new java.util.LinkedHashMap<String, Object>() {{
						put("match", new java.util.LinkedHashMap<String, Object>() {{
							put("pattern", ".*");
						}});
						put("params", new java.util.LinkedHashMap<String, Object>() {{
							put("maxTokens", 1024L);
							put("temperature", 0.7);
						}});
					}}
				)));
				put("schemaVersion", "0.1.0");
			}});
			put("package", new java.util.LinkedHashMap<String, Object>() {{
				put("author", new java.util.LinkedHashMap<String, Object>() {{
					put("name", "GildenEye");
				}});
				put("description", "Generate a contextually appropriate reply to a message or comment.");
				put("engine", "^0.1.0");
				put("name", "generate-reply");
				put("type", "standalone");
				put("version", "1.0.0");
			}});
			put("prompts", new java.util.LinkedHashMap<String, Object>() {{
				put("general", "# System\n\nYou are a reply generation function. You must only return a JSON object in the following format:\n{\"reply\": \"<reply text>\"}\n\nDo not output Markdown, do not include any extra explanation, and do not add undeclared fields.\n\nRequirements:\n- Write a natural, contextually appropriate reply to the given message.\n- Apply the requested tone (default: friendly).\n- If context is provided, use it to tailor the reply.\n- Reply in the requested language; if not specified, match the language of the input message.\n- Keep the reply concise and focused.\n\n# User\n\nOriginal message:\n{{message}}\n\nTone: {{tone}}\n\nContext: {{context}}\n\nLanguage: {{language}}\n");
			}});
			put("schemaVersion", "0.1.0");
		}};
}
