// Generated by aifn — do not edit manually.
// Package: generate-email v1.0.0

package aifunc.generate_email;

import aifunc.AIFuncConfig;
import aifunc._engine.java.v0_1_0.Runtime;
import aifunc._engine.java.v0_1_0.Artifact;
import aifunc._engine.java.v0_1_0.Types.AIFuncArtifact;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

/** Generate a complete email from a brief description of intent and context. */
/** Generated by aifn — do not edit manually. */
public final class GenerateEmail {

	private GenerateEmail() {}

	private static final Object MOCK_DATA = GenerateEmailAifuncMock.MOCK_DATA;

	public static CompletableFuture<GenerateEmailTypes.GenerateEmailOutput> generateEmail(AIFuncConfig config, GenerateEmailTypes.GenerateEmailInput input) {
		if (config == null) {
			config = AIFuncConfig.builder().mock(true).mockData(MOCK_DATA).build();
		} else if (config.isMock() && config.getMockData() == null) {
			config = config.toBuilder().mockData(MOCK_DATA).build();
		}


		AIFuncArtifact artifact = Artifact.fromMap(GenerateEmailAifunc.ARTIFACT_DATA);
		Map<String, Object> inputMap = inputToMap(input);
		return Runtime.executeAsync(artifact, inputMap, config)
			.thenApply(GenerateEmail::mapToOutput);
	}

	private static Map<String, Object> inputToMap(GenerateEmailTypes.GenerateEmailInput input) {
		Map<String, Object> m = new LinkedHashMap<>();
		m.put("intent", input.getIntent());
		if (input.getKeyPoints() != null) m.put("keyPoints", input.getKeyPoints());
		if (input.getLanguage() != null) m.put("language", input.getLanguage());
		if (input.getRecipientName() != null) m.put("recipientName", input.getRecipientName());
		if (input.getSenderName() != null) m.put("senderName", input.getSenderName());
		if (input.getTone() != null) m.put("tone", input.getTone());
		return m;
	}

	private static GenerateEmailTypes.GenerateEmailOutput mapToOutput(Map<String, Object> m) {
		String body = m.containsKey("body") ? (m.get("body") instanceof String) ? (String) m.get("body") : String.valueOf(m.get("body")) : null;
		String subject = m.containsKey("subject") ? (m.get("subject") instanceof String) ? (String) m.get("subject") : String.valueOf(m.get("subject")) : null;
		return new GenerateEmailTypes.GenerateEmailOutput(body, subject);
	}
}
