// Generated by aifn -- do not edit manually.
// Package: translate-stream v1.0.0

package translate_stream

// TranslateStreamInput holds the input parameters.
type TranslateStreamInput struct {
	// Target language (e.g. 'Chinese', 'English', 'French', 'zh-CN').
	TargetLang string
	// The text or document to translate.
	Text string
	// Subject domain hint to improve terminology accuracy (e.g. 'legal', 'medical', 'technical', 'literary'). Optional.
	Domain *string
	// Source language. If omitted, it is auto-detected.
	SourceLang *string
	// Translation style: 'literal' (close to source), 'natural' (idiomatic), 'formal'. Default: 'natural'.
	Style *string
}
