// Generated by aifn — do not edit manually.
// Package: translate v1.0.0

namespace Aifunc.Translate;

using System.Collections.Generic;

internal static class TranslateAifunc
{
	internal static readonly Dictionary<string, object?> ARTIFACT_DATA =
		new Dictionary<string, object?>
		{
			["api"] = new Dictionary<string, object?>
			{
				["description"] = "Translate text into a specified target language with automatic source language detection.",
				["input"] = new Dictionary<string, object?>
				{
					["additionalProperties"] = false,
					["properties"] = new Dictionary<string, object?>
					{
						["sourceLang"] = new Dictionary<string, object?>
						{
							["description"] = "Source language. If omitted, it will be auto-detected.",
							["type"] = "string",
						},
						["targetLang"] = new Dictionary<string, object?>
						{
							["description"] = "Target language (e.g. 'English', '日本語', 'zh-CN').",
							["minLength"] = (double)1,
							["type"] = "string",
						},
						["text"] = new Dictionary<string, object?>
						{
							["description"] = "The text to be translated.",
							["minLength"] = (double)1,
							["type"] = "string",
						},
					},
					["required"] = new List<object?>
					{
						"text",
						"targetLang",
					},
					["type"] = "object",
				},
				["name"] = "translate",
				["output"] = new Dictionary<string, object?>
				{
					["additionalProperties"] = false,
					["properties"] = new Dictionary<string, object?>
					{
						["sourceLang"] = new Dictionary<string, object?>
						{
							["description"] = "The source language (auto-detected if sourceLang was not provided).",
							["type"] = "string",
						},
						["translation"] = new Dictionary<string, object?>
						{
							["description"] = "The translated text.",
							["type"] = "string",
						},
					},
					["required"] = new List<object?>
					{
						"translation",
						"sourceLang",
					},
					["type"] = "object",
				},
			},
			["artifactVersion"] = "0.1.0",
			["metadata"] = new Dictionary<string, object?>
			{
				["contentHash"] = "sha256:d6549eabd59eb0977b11b08ae27ab309b88ad6546e62f7eadcc8f40243b56df5",
				["generatedAt"] = "2026-07-12T14:20:06Z",
				["sourcePackageVersion"] = "1.0.0",
			},
			["modelParams"] = new Dictionary<string, object?>
			{
				["rules"] = new List<object?>
				{
					new Dictionary<string, object?>
					{
						["match"] = new Dictionary<string, object?>
						{
							["pattern"] = ".*",
						},
						["params"] = new Dictionary<string, object?>
						{
							["maxTokens"] = (double)2048,
							["temperature"] = 0.3,
						},
					},
				},
				["schemaVersion"] = "0.1.0",
			},
			["package"] = new Dictionary<string, object?>
			{
				["author"] = new Dictionary<string, object?>
				{
					["name"] = "GildenEye",
				},
				["description"] = "Translate text into a specified target language with automatic source language detection.",
				["engine"] = "^0.1.0",
				["name"] = "translate",
				["type"] = "standalone",
				["version"] = "1.0.0",
			},
			["prompts"] = new Dictionary<string, object?>
			{
				["general"] = "# System\n\nYou are a professional multilingual translation function. You must only return a JSON object in the following format:\n{\"translation\": \"<translated text>\", \"sourceLang\": \"<language code>\"}\n\nDo not output Markdown, do not include any extra explanation, and do not add undeclared fields.\n\nRequirements:\n- Accurately translate the source text into the target language, preserving the original semantics and tone.\n- If the user specifies a source language, interpret the text in that language; otherwise, auto-detect the source language.\n- `sourceLang` should use a short language identifier (e.g. zh-CN, en, ja, ko, fr, de).\n- The translation should be natural and fluent, following the conventions of the target language. Avoid stiff word-for-word translation.\n- Preserve proper nouns, brand names, and other content that should not be translated.\n- If the source language is the same as the target language, return the original text as the translation result.\n\n# User\n\nText to translate:\n{{text}}\n\nTarget language: {{targetLang}}\n\nSource language: {{sourceLang}}\n",
			},
			["schemaVersion"] = "0.1.0",
		};
}
