// Generated by aifn — do not edit manually.
// Package: translate v1.0.0

namespace Aifunc.Translate;

using System.Collections.Generic;

internal static class TranslateAifuncMock
{
	internal static readonly object? MOCK_DATA =
		new Dictionary<string, object?>
		{
			["cases"] = new List<object?>
			{
				new Dictionary<string, object?>
				{
					["description"] = "Translate Chinese text to English with auto-detected source language.",
					["id"] = "zh-to-en",
					["output"] = new Dictionary<string, object?>
					{
						["sourceLang"] = "zh-CN",
						["translation"] = "Artificial intelligence is changing the way we work and live.",
					},
				},
			},
			["delay"] = new Dictionary<string, object?>
			{
				["maxMs"] = (double)120,
				["minMs"] = (double)30,
			},
			["random"] = new Dictionary<string, object?>
			{
				["enabled"] = false,
				["seed"] = "translate",
			},
			["version"] = "1.0.0",
		};
}
