// Generated by aifn — do not edit manually.
// Package: translate v1.0.0

namespace Aifunc.Translate;

using System.Collections.Generic;

public static class TranslateTypes
{
	public sealed class TranslateInput
	{
		/// <summary>The text to be translated.</summary>
		public string Text { get; }
		/// <summary>Target language (e.g. 'English', '日本語', 'zh-CN').</summary>
		public string TargetLang { get; }
		/// <summary>Source language. If omitted, it will be auto-detected.</summary>
		public string? SourceLang { get; set; }

		public TranslateInput(string text, string targetLang, string? sourceLang = null)
		{
			Text = text;
			TargetLang = targetLang;
			SourceLang = sourceLang;
		}
	}

	public sealed class TranslateOutput
	{
		/// <summary>The translated text.</summary>
		public string Translation { get; }
		/// <summary>The source language (auto-detected if sourceLang was not provided).</summary>
		public string SourceLang { get; }

		public TranslateOutput(string translation, string sourceLang)
		{
			Translation = translation;
			SourceLang = sourceLang;
		}
	}
}
