# Generated by aifn -- do not edit manually.
# Package: chat-stream v1.0.0

from typing import Any, Optional
from dataclasses import dataclass


@dataclass
class ChatStreamInput:
    message: str  # The user message.
    context: Optional[str] = None  # Optional conversation history or other background text the reply should take into account.

