// Generated by aifn -- do not edit manually.
// Package: article-stream v1.0.0

export interface ArticleStreamInput {
  /** Target audience (e.g. 'general readers', 'developers', 'executives'). Default: 'general readers'. */
  audience?: string;
  /** Output language (e.g. 'English', 'Chinese'). If omitted, matches the title language. */
  language?: string;
  /** Optional outline or key points to cover, one per line or as free text. */
  outline?: string;
  /** Writing style or tone (e.g. 'informational', 'opinion', 'tutorial', 'news'). Default: 'informational'. */
  style?: string;
  /** The article title. */
  title: string;
  /** Approximate target word count. Default: 600. Range: 200–3000. */
  wordCount?: number;
}

export type ArticleStreamOutput = string;
