// Generated by aifn -- do not edit manually.
// Package: article-stream v1.0.0

import { executeStream } from '../_engine/typescript/v0.2.0/index';
import type { AIFuncArtifact, AIFuncConfig } from '../_engine/typescript/v0.2.0/index';
import artifact from './article-stream.aifunc';
import type { ArticleStreamInput, ArticleStreamOutput } from './article-stream.types';

export type { AIFuncConfig, ArticleStreamInput, ArticleStreamOutput };

/** Stream a full article from a title and optional outline. Returns plain text. */
export async function* articleStream(config: AIFuncConfig = {}, input: ArticleStreamInput): AsyncIterable<ArticleStreamOutput> {
  const _projectDefaults = {};

  const runtimeConfig: AIFuncConfig = config;

  yield* executeStream(
    artifact as AIFuncArtifact,
    input as unknown as Record<string, unknown>,
    runtimeConfig,
    _projectDefaults,
  );
}
