// Generated by aifn -- do not edit manually.
// Package: rewrite v1.0.0

package rewrite

import (
	"context"
	"fmt"

	engine "all-packages/aifunc/_engine/go/v0.1.0"
)

// AIFuncConfig controls the runtime mode and model connection.
type AIFuncConfig = engine.AIFuncConfig

// mockData contains the built-in offline test cases.
var mockData any = rewriteMockData

// Rewrite Rewrite text according to a specified style or instruction while preserving the original meaning.
func Rewrite(ctx context.Context, config *AIFuncConfig, input RewriteInput) (RewriteOutput, error) {
	if config == nil {
		config = &AIFuncConfig{Mock: true, MockData: mockData}
	}
	if config.Mock && config.MockData == nil {
		copy := *config
		copy.MockData = mockData
		config = &copy
	}

	artifact, err := engine.ArtifactFromMap(artifactData)
	if err != nil {
		return RewriteOutput{}, fmt.Errorf("load artifact: %w", err)
	}

	inputMap := inputToMap(input)

	result, err := engine.Execute(ctx, artifact, inputMap, *config)
	if err != nil {
		return RewriteOutput{}, err
	}

	return mapToOutput(result), nil
}

func inputToMap(input RewriteInput) map[string]any {
	m := map[string]any{}
	if input.Instructions != nil { m["instructions"] = *input.Instructions }
	m["style"] = input.Style
	m["text"] = input.Text
	return m
}

func mapToOutput(m map[string]any) RewriteOutput {
	var out RewriteOutput
	if v, ok := m["rewritten"]; ok { out.Rewritten = coerceString(v) }
	return out
}

func coerceString(v any) string {
	if s, ok := v.(string); ok { return s }
	return fmt.Sprintf("%v", v)
}

