// Generated by aifn -- do not edit manually.
// Package: rewrite v1.0.0

package rewrite

// RewriteInput holds the input parameters.
type RewriteInput struct {
	// Target style or tone (e.g. 'formal', 'casual', 'concise', 'expanded', 'academic', 'humorous').
	Style string
	// The original text to rewrite.
	Text string
	// Additional rewriting instructions or constraints.
	Instructions *string
}

// RewriteOutput holds the function result.
type RewriteOutput struct {
	// The rewritten text.
	Rewritten string
}
