# Generated by aifn -- do not edit manually.
# Package: summarize v1.0.0

from typing import Any, Optional
from dataclasses import dataclass


@dataclass
class SummarizeInput:
    text: str  # The text to summarize.
    max_length: Optional[int] = None  # Maximum word count for the summary. Defaults to 80.


@dataclass
class SummarizeOutput:
    summary: str  # The generated summary.
    word_count: int  # Approximate word count of the summary.

