// Generated by aifn — do not edit manually.
// Package: answer-stream v1.0.0

namespace Aifunc.AnswerStream;

using System.Collections.Generic;

public static class AnswerStreamTypes
{
	public sealed class AnswerStreamInput
	{
		/// <summary>The question to answer.</summary>
		public string Question { get; }
		/// <summary>Target audience (e.g. 'general', 'technical', 'expert'). Default: 'general'.</summary>
		public string? Audience { get; set; }
		/// <summary>Optional source text, documents, or retrieved passages to ground the answer in. If provided, the answer must be based on this context.</summary>
		public string? Context { get; set; }
		/// <summary>Answer depth: 'concise' (1-2 paragraphs), 'detailed' (thorough explanation with examples). Default: 'detailed'.</summary>
		public string? Depth { get; set; }
		/// <summary>Answer language. If omitted, matches the language of the question.</summary>
		public string? Language { get; set; }

		public AnswerStreamInput(string question, string? audience = null, string? context = null, string? depth = null, string? language = null)
		{
			Question = question;
			Audience = audience;
			Context = context;
			Depth = depth;
			Language = language;
		}
	}
}
