// Generated by aifn — do not edit manually.
// Package: explain-stream v1.0.0

namespace Aifunc.ExplainStream;

using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading;
using Aifunc;
using Aifunc.Engine.Csharp.V0_2_0;

/// <summary>Stream a clear explanation of a concept, code snippet, or term. Returns plain text.</summary>
public static class ExplainStream
{
	/// <summary>
	/// Stream a clear explanation of a concept, code snippet, or term. Returns plain text.
	/// </summary>
	/// <remarks>
	/// Pass a <see cref="CancellationToken"/> to cancel the stream at any time.
	/// <code>
	/// using var cts = new CancellationTokenSource();
	/// await foreach (var token in ExplainStreamAsync(config, input, cts.Token))
	///     Console.Write(token);
	/// </code>
	/// </remarks>
	public static async IAsyncEnumerable<string> ExplainStreamAsync(
		AIFuncConfig? config,
		ExplainStreamTypes.ExplainStreamInput input,
		[EnumeratorCancellation] CancellationToken cancellationToken = default)
	{
		if (config is null)
			config = new AIFuncConfig();


		var artifact = Artifact.FromMap(ExplainStreamAifunc.ARTIFACT_DATA);
		var inputMap = InputToMap(input);
		await foreach (var token in Runtime.ExecuteStreamAsync(
			artifact, inputMap, config, cancellationToken))
		{
			yield return token;
		}
	}

	private static System.Collections.Generic.Dictionary<string, object?> InputToMap(ExplainStreamTypes.ExplainStreamInput input)
	{
		var m = new System.Collections.Generic.Dictionary<string, object?>();
		if (input.Audience is not null) m["audience"] = input.Audience;
		if (input.Context is not null) m["context"] = input.Context;
		if (input.Depth is not null) m["depth"] = input.Depth;
		if (input.Language is not null) m["language"] = input.Language;
		m["topic"] = input.Topic;
		return m;
	}

}
