// Generated by aifn — do not edit manually.
// Package: summarize v1.0.0

package aifunc.summarize;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
public final class SummarizeTypes {

	private SummarizeTypes() {}

	public static final class SummarizeInput {
		/** The text to summarize. */
		private final String text;
		/** Maximum word count for the summary. Defaults to 80. */
		private Integer maxLength;

		public SummarizeInput(String text, Integer maxLength) {
			this.text = text;
			this.maxLength = maxLength;
		}

		public String getText() { return text; }
		public Integer getMaxLength() { return maxLength; }
		public void setMaxLength(Integer v) { this.maxLength = v; }
	}

	public static final class SummarizeOutput {
		/** The generated summary. */
		private final String summary;
		/** Approximate word count of the summary. */
		private final Integer wordCount;

		public SummarizeOutput(String summary, Integer wordCount) {
			this.summary = summary;
			this.wordCount = wordCount;
		}

		public String getSummary() { return summary; }
		public Integer getWordCount() { return wordCount; }
	}
}
