// Generated by aifn — do not edit manually.
// Package: summarize v1.0.0

package aifunc.summarize;

import aifunc.AIFuncConfig;
import aifunc._engine.java.v0_2_0.Runtime;
import aifunc._engine.java.v0_2_0.Artifact;
import aifunc._engine.java.v0_2_0.Types.AIFuncArtifact;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

/** Generate a concise summary of the input text. */
/** Generated by aifn — do not edit manually. */
public final class Summarize {

	private Summarize() {}

	private static final Object MOCK_DATA = SummarizeAifuncMock.MOCK_DATA;

	public static CompletableFuture<SummarizeTypes.SummarizeOutput> summarize(AIFuncConfig config, SummarizeTypes.SummarizeInput input) {
		if (config == null) {
			config = AIFuncConfig.builder().mock(true).mockData(MOCK_DATA).build();
		} else if (config.isMock() && config.getMockData() == null) {
			config = config.toBuilder().mockData(MOCK_DATA).build();
		}

		AIFuncArtifact artifact = Artifact.fromMap(SummarizeAifunc.ARTIFACT_DATA);
		Map<String, Object> inputMap = inputToMap(input);
		return Runtime.executeAsync(artifact, inputMap, config)
			.thenApply(Summarize::mapToOutput);
	}

	private static Map<String, Object> inputToMap(SummarizeTypes.SummarizeInput input) {
		Map<String, Object> m = new LinkedHashMap<>();
		if (input.getMaxLength() != null) m.put("maxLength", input.getMaxLength());
		m.put("text", input.getText());
		return m;
	}

	private static SummarizeTypes.SummarizeOutput mapToOutput(Map<String, Object> m) {
		String summary = m.containsKey("summary") ? (m.get("summary") instanceof String) ? (String) m.get("summary") : String.valueOf(m.get("summary")) : null;
		Integer wordCount = m.containsKey("wordCount") ? (m.get("wordCount") instanceof Number) ? ((Number) m.get("wordCount")).intValue() : null : null;
		return new SummarizeTypes.SummarizeOutput(summary, wordCount);
	}
}
