// Generated by aifn — do not edit manually.
// Package: extract-json v1.0.0

package aifunc.extract_json;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
public final class ExtractJsonTypes {

	private ExtractJsonTypes() {}

	public static final class ExtractJsonInput {
		/** Schema describing the fields to extract. */
		private final java.util.List<java.util.Map<String, Object>> fields;
		/** The natural language text to extract information from. */
		private final String text;

		public ExtractJsonInput(java.util.List<java.util.Map<String, Object>> fields, String text) {
			this.fields = fields;
			this.text = text;
		}

		public java.util.List<java.util.Map<String, Object>> getFields() { return fields; }
		public String getText() { return text; }
	}

	public static final class ExtractJsonOutput {
		/** Extracted key-value pairs matching the requested fields. */
		private final java.util.Map<String, Object> extracted;
		/** Field names that could not be found in the text. */
		private final java.util.List<String> missing;

		public ExtractJsonOutput(java.util.Map<String, Object> extracted, java.util.List<String> missing) {
			this.extracted = extracted;
			this.missing = missing;
		}

		public java.util.Map<String, Object> getExtracted() { return extracted; }
		public java.util.List<String> getMissing() { return missing; }
	}
}
