# Generated by aifn -- do not edit manually.

artifact = {
    "api": {
        "description": "Stream a full article from a title and optional outline. Returns plain text.",
        "injectOutputSchema": False,
        "input": {
            "additionalProperties": False,
            "properties": {
                "audience": {
                    "default": "general readers",
                    "description": "Target audience (e.g. 'general readers', 'developers', 'executives'). Default: 'general readers'.",
                    "type": "string",
                },
                "language": {
                    "description": "Output language (e.g. 'English', 'Chinese'). If omitted, matches the title language.",
                    "type": "string",
                },
                "outline": {
                    "description": "Optional outline or key points to cover, one per line or as free text.",
                    "type": "string",
                },
                "style": {
                    "default": "informational",
                    "description": "Writing style or tone (e.g. 'informational', 'opinion', 'tutorial', 'news'). Default: 'informational'.",
                    "type": "string",
                },
                "title": {
                    "description": "The article title.",
                    "minLength": 1,
                    "type": "string",
                },
                "wordCount": {
                    "default": 600,
                    "description": "Approximate target word count. Default: 600. Range: 200–3000.",
                    "maximum": 3000,
                    "minimum": 200,
                    "type": "integer",
                },
            },
            "required": [
                "title",
            ],
            "type": "object",
        },
        "name": "article_stream",
        "output": {
            "description": "The generated article as plain text.",
            "type": "string",
            "x-delivery-mode": "stream",
        },
    },
    "artifactVersion": "0.1.0",
    "metadata": {
        "contentHash": "sha256:9a83ec7607ab16702eb54a265fb7d0a9a7f27b8db590992c798e3c381c5fa3f2",
        "generatedAt": "2026-07-19T11:46:30Z",
        "sourcePackageVersion": "1.0.0",
    },
    "modelParams": {
        "rules": [
            {
                "match": {
                    "pattern": ".*",
                },
                "params": {
                    "maxTokens": 4096,
                    "temperature": 0.75,
                },
            },
        ],
        "schemaVersion": "0.1.0",
    },
    "package": {
        "author": {
            "name": "GildenEye",
        },
        "description": "Stream a full article from a title and optional outline. Returns plain text.",
        "engine": "^0.2.0",
        "engineOptions": {
            "injectOutputSchema": False,
        },
        "name": "article-stream",
        "type": "standalone",
        "version": "1.0.0",
    },
    "prompts": {
        "general": "# System\n\nYou are a professional article writer. Your task is to write a complete, well-structured article based on the given title and optional outline.\n\n## Requirements\n\n- Write approximately {{input.wordCount}} words of article prose.\n- Style: {{input.style}} — match the appropriate tone and structure for this style.\n- Target audience: {{input.audience}} — calibrate vocabulary, depth, and assumed knowledge accordingly.\n- If an outline is provided, follow it as the structural backbone. If not, devise a logical structure yourself.\n- Begin directly with the article body. Do not include a title header, preamble, or any meta-commentary.\n- Output plain text only — no Markdown formatting, no JSON, no labels.\n- If a language is specified, write in that language. Otherwise, match the language of the title.\n- The article must be coherent, informative, and flow naturally from introduction to conclusion.\n\n## Input\n\nTitle: {{input.title}}\n\nOutline: {{input.outline}}\n\nStyle: {{input.style}}\n\nAudience: {{input.audience}}\n\nLanguage: {{input.language}}\n\nWord count target: {{input.wordCount}}\n",
    },
    "schemaVersion": "0.1.0",
}
