// Copyright 2026 GildenEye
// SPDX-License-Identifier: Apache-2.0

package java

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"aifunc/cli/internal/types"
)

const (
	javaIndent = "\t"
	filePerm   = 0644
	dirPerm    = 0755
)

// isStreamOutput reports whether the artifact's output schema has x-delivery-mode: stream.
func isStreamOutput(artifact *types.CompiledArtifact) bool {
	mode, _ := artifact.API.Output["x-delivery-mode"].(string)
	return mode == "stream"
}

// Generate writes <Name>Types.java, <Name>Aifunc.java, <Name>AifuncMock.java,
// and <Name>.java for the given compiled artifact into outputDir.
// javaPackageRoot is the root Java package prefix (e.g. "aifunc").
func Generate(artifact *types.CompiledArtifact, outputDir string, hasMock bool, engineVersion string, cfg types.AifuncConfig, javaPackageRoot string) error {
	if err := os.MkdirAll(outputDir, dirPerm); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	baseName := toPascalCase(artifact.Package.Name)
	pkgName := sanitizePackageName(artifact.Package.Name)
	engineVer := "v" + strings.ReplaceAll(engineVersion, ".", "_")
	enginePkg := javaPackageRoot + "._engine.java." + engineVer

	type fileSpec struct {
		name      string
		generator func() (string, error)
	}

	files := []fileSpec{
		{baseName + "Types.java", func() (string, error) {
			return generateTypes(artifact, pkgName, javaPackageRoot, enginePkg)
		}},
		{baseName + "Aifunc.java", func() (string, error) {
			return generateArtifact(artifact, pkgName, javaPackageRoot)
		}},
	}

	if hasMock {
		files = append(files, fileSpec{baseName + "AifuncMock.java", func() (string, error) {
			return generateMockStub(artifact, pkgName, javaPackageRoot)
		}})
	}

	files = append(files, fileSpec{baseName + ".java", func() (string, error) {
		return generateEntry(artifact, pkgName, baseName, hasMock, enginePkg, cfg, javaPackageRoot)
	}})

	for _, f := range files {
		content, err := f.generator()
		if err != nil {
			return fmt.Errorf("generate %s: %w", f.name, err)
		}
		if err := os.WriteFile(filepath.Join(outputDir, f.name), []byte(content), filePerm); err != nil {
			return fmt.Errorf("write %s: %w", f.name, err)
		}
	}
	return nil
}

// GenerateRootTypes writes AIFuncConfig.java and AIFuncException.java to the
// output root directory (package "aifunc" or whatever javaPackageRoot is).
// These are shared across all installed packages.
func GenerateRootTypes(outputDir string, javaPackageRoot string) error {
	if err := os.MkdirAll(outputDir, dirPerm); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	cfgContent := generateAIFuncConfig(javaPackageRoot)
	if err := os.WriteFile(filepath.Join(outputDir, "AIFuncConfig.java"), []byte(cfgContent), filePerm); err != nil {
		return fmt.Errorf("write AIFuncConfig.java: %w", err)
	}

	excContent := generateAIFuncException(javaPackageRoot)
	if err := os.WriteFile(filepath.Join(outputDir, "AIFuncException.java"), []byte(excContent), filePerm); err != nil {
		return fmt.Errorf("write AIFuncException.java: %w", err)
	}
	return nil
}

func generateAIFuncConfig(rootPkg string) string {
	return `// Generated by aifn — do not edit manually.

package ` + rootPkg + `;

public final class AIFuncConfig {

    private final String  baseUrl;
    private final String  apiKey;
    private final String  model;
    private final Double  temperature;
    private final Double  topP;
    private final Integer maxTokens;
    private final int timeoutMs;
    private final int maxRetries;
    private final boolean mock;
    private final Object mockData;

    private AIFuncConfig(Builder b) {
        this.baseUrl     = b.baseUrl;
        this.apiKey      = b.apiKey;
        this.model       = b.model;
        this.temperature = b.temperature;
        this.topP        = b.topP;
        this.maxTokens   = b.maxTokens;
        this.timeoutMs   = b.timeoutMs;
        this.maxRetries  = b.maxRetries;
        this.mock        = b.mock;
        this.mockData    = b.mockData;
    }

    public String  getBaseUrl()     { return baseUrl;     }
    public String  getApiKey()      { return apiKey;      }
    public String  getModel()       { return model;       }
    public Double  getTemperature() { return temperature; }
    public Double  getTopP()        { return topP;        }
    public Integer getMaxTokens()   { return maxTokens;   }
    public int     getTimeoutMs()   { return timeoutMs;   }
    public int     getMaxRetries()  { return maxRetries;  }
    public boolean isMock()         { return mock;        }
    public Object  getMockData()    { return mockData;    }

    public Builder toBuilder() {
        return new Builder().baseUrl(baseUrl).apiKey(apiKey).model(model)
                .temperature(temperature).topP(topP).maxTokens(maxTokens)
                .timeoutMs(timeoutMs).maxRetries(maxRetries).mock(mock).mockData(mockData);
    }

    public static Builder builder() { return new Builder(); }

    public static final class Builder {
        private String  baseUrl;
        private String  apiKey;
        private String  model;
        private Double  temperature;
        private Double  topP;
        private Integer maxTokens;
        private int     timeoutMs  = 0;
        private int     maxRetries = 0;
        private boolean mock       = false;
        private Object  mockData;

        private Builder() {}

        public Builder baseUrl(String v)     { this.baseUrl     = v; return this; }
        public Builder apiKey(String v)      { this.apiKey      = v; return this; }
        public Builder model(String v)       { this.model       = v; return this; }
        public Builder temperature(Double v) { this.temperature = v; return this; }
        public Builder topP(Double v)        { this.topP        = v; return this; }
        public Builder maxTokens(Integer v)  { this.maxTokens   = v; return this; }
        public Builder timeoutMs(int v)      { this.timeoutMs   = v; return this; }
        public Builder maxRetries(int v)     { this.maxRetries  = v; return this; }
        public Builder mock(boolean v)       { this.mock        = v; return this; }
        public Builder mockData(Object v)    { this.mockData    = v; return this; }

        public AIFuncConfig build() { return new AIFuncConfig(this); }
    }
}
`
}

func generateAIFuncException(rootPkg string) string {
	return `// Generated by aifn — do not edit manually.

package ` + rootPkg + `;

public final class AIFuncException extends RuntimeException {
    public AIFuncException(String message) { super(message); }
    public AIFuncException(String message, Throwable cause) { super(message, cause); }
}
`
}

// ---- Types file ----

func generateTypes(artifact *types.CompiledArtifact, pkgName, rootPkg, enginePkg string) (string, error) {
	var b strings.Builder
	writeJavaHeader(&b, artifact)
	fmt.Fprintf(&b, "package %s.%s;\n\n", rootPkg, pkgName)
	// Import engine Types by simple name so the stream delegate can refer to
	// Types.TokenStream. A fully-qualified nested name
	// (…Types.TokenStream) is mis-resolved by Eclipse JDT when the package
	// path contains a "java" segment (aifunc._engine.java.…).
	if isStreamOutput(artifact) {
		fmt.Fprintf(&b, "import %s.Types;\n", enginePkg)
	}
	b.WriteString("import java.util.List;\nimport java.util.Map;\n\n")
	b.WriteString("/** Generated by aifn — do not edit manually. */\n")
	fmt.Fprintf(&b, "public final class %sTypes {\n\n", toPascalCase(artifact.Package.Name))
	fmt.Fprintf(&b, "%sprivate %sTypes() {}\n\n", javaIndent, toPascalCase(artifact.Package.Name))

	baseName := toPascalCase(artifact.API.Name)
	writeJavaPojo(&b, baseName+"Input", artifact.API.Input)
	b.WriteString("\n")
	if isStreamOutput(artifact) {
		writeTokenStreamDelegate(&b)
	} else {
		writeJavaPojo(&b, baseName+"Output", artifact.API.Output)
	}
	b.WriteString("}\n")
	return b.String(), nil
}

func writeJavaPojo(b *strings.Builder, className string, schema map[string]any) {
	props, _ := schema["properties"].(map[string]any)
	required := requiredSet(schema)

	// required fields first, then optional — determines constructor parameter order
	var reqKeys, optKeys []string
	for _, k := range sortedKeys(props) {
		if required[k] {
			reqKeys = append(reqKeys, k)
		} else {
			optKeys = append(optKeys, k)
		}
	}
	allKeys := append(reqKeys, optKeys...)

	fmt.Fprintf(b, "%spublic static final class %s {\n", javaIndent, className)

	for _, key := range allKeys {
		prop, ok := props[key].(map[string]any)
		if !ok {
			continue
		}
		desc, _ := prop["description"].(string)
		jType := jsonSchemaToJavaType(prop)
		field := toCamelCase(key)
		if desc != "" {
			fmt.Fprintf(b, "%s%s/** %s */\n", javaIndent, javaIndent, desc)
		}
		if required[key] {
			fmt.Fprintf(b, "%s%sprivate final %s %s;\n", javaIndent, javaIndent, jType, field)
		} else {
			fmt.Fprintf(b, "%s%sprivate %s %s;\n", javaIndent, javaIndent, jType, field)
		}
	}
	b.WriteString("\n")

	// all-arg constructor: required params first, then optional
	var params []string
	for _, key := range allKeys {
		if prop, ok := props[key].(map[string]any); ok {
			params = append(params, jsonSchemaToJavaType(prop)+" "+toCamelCase(key))
		}
	}

	// No-arg constructor is only legal in Java when there are no final (required)
	// fields — every final must be assigned in every constructor.
	if len(reqKeys) == 0 {
		fmt.Fprintf(b, "%s%spublic %s() {}\n\n", javaIndent, javaIndent, className)
	}

	// Skip a second empty constructor when we already emitted no-arg above.
	if len(params) > 0 || len(reqKeys) > 0 {
		fmt.Fprintf(b, "%s%spublic %s(%s) {\n", javaIndent, javaIndent, className, strings.Join(params, ", "))
		for _, key := range allKeys {
			if _, ok := props[key].(map[string]any); !ok {
				continue
			}
			field := toCamelCase(key)
			fmt.Fprintf(b, "%s%s%sthis.%s = %s;\n", javaIndent, javaIndent, javaIndent, field, field)
		}
		fmt.Fprintf(b, "%s%s}\n\n", javaIndent, javaIndent)
	}

	// getters / setters
	for _, key := range allKeys {
		prop, ok := props[key].(map[string]any)
		if !ok {
			continue
		}
		jType := jsonSchemaToJavaType(prop)
		field := toCamelCase(key)
		cap := strings.ToUpper(field[:1]) + field[1:]
		fmt.Fprintf(b, "%s%spublic %s get%s() { return %s; }\n", javaIndent, javaIndent, jType, cap, field)
		if !required[key] {
			fmt.Fprintf(b, "%s%spublic void set%s(%s v) { this.%s = v; }\n", javaIndent, javaIndent, cap, jType, field)
		}
	}
	fmt.Fprintf(b, "%s}\n", javaIndent)
}


// writeTokenStreamDelegate emits a public TokenStream class inside the *Types
// outer class. It wraps the engine-internal TokenStream so callers only need to
// import from the package-level types file (e.g. ChatStreamTypes.TokenStream)
// and never from the _engine internal package.
//
// Relies on a file-level `import …Types` (see generateTypes) and refers to the
// engine type as Types.TokenStream — not a fully-qualified nested name.
func writeTokenStreamDelegate(b *strings.Builder) {
	fmt.Fprintf(b, "%s/**\n", javaIndent)
	fmt.Fprintf(b, "%s * A blocking token iterator returned by this package's stream method.\n", javaIndent)
	fmt.Fprintf(b, "%s * Use it in a try-with-resources block; a {@code break} cancels the\n", javaIndent)
	fmt.Fprintf(b, "%s * stream automatically and frees the background thread.\n", javaIndent)
	fmt.Fprintf(b, "%s */\n", javaIndent)
	fmt.Fprintf(b, "%spublic static final class TokenStream implements java.util.Iterator<String>, AutoCloseable {\n", javaIndent)
	fmt.Fprintf(b, "%s%sprivate final Types.TokenStream delegate;\n\n", javaIndent, javaIndent)
	fmt.Fprintf(b, "%s%spublic TokenStream(Types.TokenStream delegate) { this.delegate = delegate; }\n", javaIndent, javaIndent)
	fmt.Fprintf(b, "%s%spublic TokenStream(java.util.Iterator<String> iterator, Runnable cancelFn) { this.delegate = new Types.TokenStream(iterator, cancelFn); }\n\n", javaIndent, javaIndent)
	fmt.Fprintf(b, "%s%s@Override public boolean hasNext() { return delegate.hasNext(); }\n", javaIndent, javaIndent)
	fmt.Fprintf(b, "%s%s@Override public String  next()    { return delegate.next();    }\n", javaIndent, javaIndent)
	fmt.Fprintf(b, "%s%s/** Cancels the stream. Idempotent. */\n", javaIndent, javaIndent)
	fmt.Fprintf(b, "%s%spublic void cancel()               { delegate.cancel();         }\n", javaIndent, javaIndent)
	fmt.Fprintf(b, "%s%s@Override public void close()      { delegate.close();          }\n", javaIndent, javaIndent)
	fmt.Fprintf(b, "%s}\n", javaIndent)
}
// ---- Artifact data file ----

func generateArtifact(artifact *types.CompiledArtifact, pkgName, rootPkg string) (string, error) {
	var b strings.Builder
	writeJavaHeader(&b, artifact)
	fmt.Fprintf(&b, "package %s.%s;\n\nimport java.util.List;\nimport java.util.Map;\n\n", rootPkg, pkgName)
	b.WriteString("/** Generated by aifn — do not edit manually. */\n")
	b.WriteString("@SuppressWarnings(\"serial\")\n")
	fmt.Fprintf(&b, "final class %sAifunc {\n\n%sprivate %sAifunc() {}\n\n", toPascalCase(artifact.Package.Name), javaIndent, toPascalCase(artifact.Package.Name))
	b.WriteString(javaIndent + "static final java.util.Map<String, Object> ARTIFACT_DATA =\n")
	b.WriteString(javaIndent + javaIndent + ToJavaMap(artifact, 2) + ";\n}\n")
	return b.String(), nil
}

// ---- Mock stub (overwritten later with real data) ----

func generateMockStub(artifact *types.CompiledArtifact, pkgName, rootPkg string) (string, error) {
	var b strings.Builder
	writeJavaHeader(&b, artifact)
	basePascal := toPascalCase(artifact.Package.Name)
	fmt.Fprintf(&b, "package %s.%s;\n\nimport java.util.List;\nimport java.util.Map;\n\n", rootPkg, pkgName)
	b.WriteString("/** Generated by aifn — do not edit manually. */\n")
	b.WriteString("@SuppressWarnings(\"serial\")\n")
	fmt.Fprintf(&b, "final class %sAifuncMock {\n\n%sprivate %sAifuncMock() {}\n\n", basePascal, javaIndent, basePascal)
	b.WriteString(javaIndent + "static final Object MOCK_DATA = null;\n}\n")
	return b.String(), nil
}

// WriteMockFile writes the mock data Java file from parsed mock.json content.
func WriteMockFile(mockRaw any, artifact *types.CompiledArtifact, pkgOutputDir, pkgName, rootPkg string) error {
	basePascal := toPascalCase(artifact.Package.Name)
	var b strings.Builder
	writeJavaHeader(&b, artifact)
	fmt.Fprintf(&b, "package %s.%s;\n\nimport java.util.List;\nimport java.util.Map;\n\n", rootPkg, pkgName)
	b.WriteString("/** Generated by aifn — do not edit manually. */\n")
	b.WriteString("@SuppressWarnings(\"serial\")\n")
	fmt.Fprintf(&b, "final class %sAifuncMock {\n\n%sprivate %sAifuncMock() {}\n\n", basePascal, javaIndent, basePascal)
	b.WriteString(javaIndent + "static final Object MOCK_DATA =\n")
	b.WriteString(javaIndent + javaIndent + ToJavaMap(mockRaw, 2) + ";\n}\n")
	return os.WriteFile(filepath.Join(pkgOutputDir, basePascal+"AifuncMock.java"), []byte(b.String()), filePerm)
}

// ---- Entry file ----

// generateEntry dispatches to the streaming or non-streaming entry generator.
func generateEntry(artifact *types.CompiledArtifact, pkgName, baseName string, hasMock bool, enginePkg string, cfg types.AifuncConfig, rootPkg string) (string, error) {
	if isStreamOutput(artifact) {
		return generateStreamEntry(artifact, pkgName, baseName, hasMock, enginePkg, cfg, rootPkg)
	}
	return generateNonStreamEntry(artifact, pkgName, baseName, hasMock, enginePkg, cfg, rootPkg)
}

// generateStreamEntry generates the entry class for a streaming package.
// The exported method returns a TokenStream (Iterator<String> + AutoCloseable).
func generateStreamEntry(artifact *types.CompiledArtifact, pkgName, baseName string, hasMock bool, enginePkg string, cfg types.AifuncConfig, rootPkg string) (string, error) {
	var b strings.Builder

	funcPascal := toPascalCase(artifact.API.Name)
	funcCamel  := toCamelCase(artifact.API.Name)
	inputName  := funcPascal + "Input"
	typeClass  := baseName + "Types"

	writeJavaHeader(&b, artifact)
	fmt.Fprintf(&b, "package %s.%s;\n\n", rootPkg, pkgName)
	fmt.Fprintf(&b, "import %s.AIFuncConfig;\n", rootPkg)
	fmt.Fprintf(&b, "import %s.Runtime;\n", enginePkg)
	fmt.Fprintf(&b, "import %s.Artifact;\n", enginePkg)
	fmt.Fprintf(&b, "import %s.Types.AIFuncArtifact;\n", enginePkg)
	b.WriteString("import java.util.LinkedHashMap;\nimport java.util.Map;\n\n")

	desc := artifact.API.Description
	if desc == "" {
		desc = artifact.Package.Description
	}
	if desc != "" {
		fmt.Fprintf(&b, "/** %s */\n", desc)
	}
	b.WriteString("/** Generated by aifn — do not edit manually. */\n")
	fmt.Fprintf(&b, "public final class %s {\n\n", baseName)
	fmt.Fprintf(&b, "%sprivate %s() {}\n\n", javaIndent, baseName)

	if hasMock {
		fmt.Fprintf(&b, "%sprivate static final Object MOCK_DATA = %sAifuncMock.MOCK_DATA;\n\n", javaIndent, baseName)
	}

	fmt.Fprintf(&b, "%s/**\n%s * Stream tokens from the model.\n", javaIndent, javaIndent)
	fmt.Fprintf(&b, "%s * Returns a {@link %s.TokenStream} — use it in a try-with-resources block;\n", javaIndent, typeClass)
	fmt.Fprintf(&b, "%s * {@code break} automatically cancels the stream and frees the background thread.\n%s */\n", javaIndent, javaIndent)
	fmt.Fprintf(&b, "%spublic static %s.TokenStream %s(AIFuncConfig config, %s.%s input) {\n", javaIndent, typeClass, funcCamel, typeClass, inputName)
	writeConfigWiring(&b, hasMock, cfg, baseName)
	fmt.Fprintf(&b, "%s%sAIFuncArtifact artifact = Artifact.fromMap(%sAifunc.ARTIFACT_DATA);\n", javaIndent, javaIndent, baseName)
	fmt.Fprintf(&b, "%s%sMap<String, Object> inputMap = inputToMap(input);\n", javaIndent, javaIndent)
	fmt.Fprintf(&b, "%s%sreturn new %s.TokenStream(Runtime.executeStream(artifact, inputMap, config));\n", javaIndent, javaIndent, typeClass)
	fmt.Fprintf(&b, "%s}\n\n", javaIndent)

	fmt.Fprintf(&b, "%sprivate static Map<String, Object> inputToMap(%s.%s input) {\n", javaIndent, typeClass, inputName)
	fmt.Fprintf(&b, "%s%sMap<String, Object> m = new LinkedHashMap<>();\n", javaIndent, javaIndent)
	inputProps, _ := artifact.API.Input["properties"].(map[string]any)
	for _, key := range sortedKeys(inputProps) {
		field := toCamelCase(key)
		getter := "get" + strings.ToUpper(field[:1]) + field[1:]
		if isRequired(key, artifact.API.Input) {
			fmt.Fprintf(&b, "%s%sm.put(%q, input.%s());\n", javaIndent, javaIndent, key, getter)
		} else {
			fmt.Fprintf(&b, "%s%sif (input.%s() != null) m.put(%q, input.%s());\n", javaIndent, javaIndent, getter, key, getter)
		}
	}
	fmt.Fprintf(&b, "%s%sreturn m;\n%s}\n}\n\n", javaIndent, javaIndent, javaIndent)

	return b.String(), nil
}


// buildConfigWiring is a no-op placeholder used to avoid unused-variable warnings.
func buildConfigWiring(_ *strings.Builder, _ bool, _ types.AifuncConfig, _ string) string {
	return ""
}

// writeConfigWiring emits the null-config / mock-data wiring block.
func writeConfigWiring(b *strings.Builder, hasMock bool, cfg types.AifuncConfig, baseName string) {
	if hasMock {
		fmt.Fprintf(b, "%s%sif (config == null) {\n", javaIndent, javaIndent)
		fmt.Fprintf(b, "%s%s%sconfig = AIFuncConfig.builder().mock(true).mockData(MOCK_DATA).build();\n", javaIndent, javaIndent, javaIndent)
		fmt.Fprintf(b, "%s%s} else if (config.isMock() && config.getMockData() == null) {\n", javaIndent, javaIndent)
		fmt.Fprintf(b, "%s%s%sconfig = config.toBuilder().mockData(MOCK_DATA).build();\n", javaIndent, javaIndent, javaIndent)
		fmt.Fprintf(b, "%s%s}\n", javaIndent, javaIndent)
	} else {
		fmt.Fprintf(b, "%s%sif (config == null) config = AIFuncConfig.builder().build();\n", javaIndent, javaIndent)
	}
	if cfg.Timeout != nil {
		fmt.Fprintf(b, "%s%sif (config.getTimeoutMs() == 0) config = config.toBuilder().timeoutMs(%d).build();\n", javaIndent, javaIndent, *cfg.Timeout)
	}
	if cfg.MaxRetries != nil {
		fmt.Fprintf(b, "%s%sif (config.getMaxRetries() == 0) config = config.toBuilder().maxRetries(%d).build();\n", javaIndent, javaIndent, *cfg.MaxRetries)
	}
	fmt.Fprintf(b, "\n")
}
// generateNonStreamEntry generates the entry class for a standard (non-streaming) package.
func generateNonStreamEntry(artifact *types.CompiledArtifact, pkgName, baseName string, hasMock bool, enginePkg string, cfg types.AifuncConfig, rootPkg string) (string, error) {
	var b strings.Builder

	funcPascal := toPascalCase(artifact.API.Name)
	inputName  := funcPascal + "Input"
	outputName := funcPascal + "Output"
	typeClass  := baseName + "Types"

	writeJavaHeader(&b, artifact)
	fmt.Fprintf(&b, "package %s.%s;\n\n", rootPkg, pkgName)
	fmt.Fprintf(&b, "import %s.AIFuncConfig;\n", rootPkg)
	fmt.Fprintf(&b, "import %s.Runtime;\n", enginePkg)
	fmt.Fprintf(&b, "import %s.Artifact;\n", enginePkg)
	fmt.Fprintf(&b, "import %s.Types.AIFuncArtifact;\n", enginePkg)
	b.WriteString("import java.util.LinkedHashMap;\nimport java.util.Map;\nimport java.util.concurrent.CompletableFuture;\n\n")

	desc := artifact.API.Description
	if desc == "" {
		desc = artifact.Package.Description
	}
	if desc != "" {
		fmt.Fprintf(&b, "/** %s */\n", desc)
	}
	b.WriteString("/** Generated by aifn — do not edit manually. */\n")
	fmt.Fprintf(&b, "public final class %s {\n\n", baseName)
	fmt.Fprintf(&b, "%sprivate %s() {}\n\n", javaIndent, baseName)

	if hasMock {
		fmt.Fprintf(&b, "%sprivate static final Object MOCK_DATA = %sAifuncMock.MOCK_DATA;\n\n", javaIndent, baseName)
	}

	funcCamel := toCamelCase(artifact.API.Name)
	fmt.Fprintf(&b, "%spublic static CompletableFuture<%s.%s> %s(AIFuncConfig config, %s.%s input) {\n",
		javaIndent, typeClass, outputName, funcCamel, typeClass, inputName)

	writeConfigWiring(&b, hasMock, cfg, baseName)

	fmt.Fprintf(&b, "%s%sAIFuncArtifact artifact = Artifact.fromMap(%sAifunc.ARTIFACT_DATA);\n", javaIndent, javaIndent, baseName)
	fmt.Fprintf(&b, "%s%sMap<String, Object> inputMap = inputToMap(input);\n", javaIndent, javaIndent)
	fmt.Fprintf(&b, "%s%sreturn Runtime.executeAsync(artifact, inputMap, config)\n", javaIndent, javaIndent)
	fmt.Fprintf(&b, "%s%s%s.thenApply(%s::mapToOutput);\n", javaIndent, javaIndent, javaIndent, baseName)
	fmt.Fprintf(&b, "%s}\n\n", javaIndent)

	// inputToMap
	fmt.Fprintf(&b, "%sprivate static Map<String, Object> inputToMap(%s.%s input) {\n", javaIndent, typeClass, inputName)
	fmt.Fprintf(&b, "%s%sMap<String, Object> m = new LinkedHashMap<>();\n", javaIndent, javaIndent)
	inputProps, _ := artifact.API.Input["properties"].(map[string]any)
	for _, key := range sortedKeys(inputProps) {
		field := toCamelCase(key)
		getter := "get" + strings.ToUpper(field[:1]) + field[1:]
		if isRequired(key, artifact.API.Input) {
			fmt.Fprintf(&b, "%s%sm.put(%q, input.%s());\n", javaIndent, javaIndent, key, getter)
		} else {
			fmt.Fprintf(&b, "%s%sif (input.%s() != null) m.put(%q, input.%s());\n", javaIndent, javaIndent, getter, key, getter)
		}
	}
	fmt.Fprintf(&b, "%s%sreturn m;\n%s}\n\n", javaIndent, javaIndent, javaIndent)

	// mapToOutput
	outputProps, _ := artifact.API.Output["properties"].(map[string]any)
	outputRequired := requiredSet(artifact.API.Output)
	var reqOutKeys, optOutKeys []string
	for _, k := range sortedKeys(outputProps) {
		if outputRequired[k] { reqOutKeys = append(reqOutKeys, k) } else { optOutKeys = append(optOutKeys, k) }
	}
	allOutKeys := append(reqOutKeys, optOutKeys...)

	needsUnchecked := false
	for _, key := range allOutKeys {
		prop, ok := outputProps[key].(map[string]any)
		if !ok { continue }
		if javaTypeNeedsUncheckedCast(jsonSchemaToJavaType(prop)) {
			needsUnchecked = true
			break
		}
	}
	if needsUnchecked {
		fmt.Fprintf(&b, "%s@SuppressWarnings(\"unchecked\")\n", javaIndent)
	}
	fmt.Fprintf(&b, "%sprivate static %s.%s mapToOutput(Map<String, Object> m) {\n", javaIndent, typeClass, outputName)
	for _, key := range allOutKeys {
		prop, ok := outputProps[key].(map[string]any)
		if !ok { continue }
		jType := jsonSchemaToJavaType(prop)
		field := toCamelCase(key)
		coerce := javaCoerceExpr(jType, fmt.Sprintf("m.get(%q)", key))
		fmt.Fprintf(&b, "%s%s%s %s = m.containsKey(%q) ? %s : null;\n", javaIndent, javaIndent, jType, field, key, coerce)
	}
	var ctorArgs []string
	for _, key := range allOutKeys {
		if _, ok := outputProps[key].(map[string]any); ok {
			ctorArgs = append(ctorArgs, toCamelCase(key))
		}
	}
	fmt.Fprintf(&b, "%s%sreturn new %s.%s(%s);\n%s}\n}\n", javaIndent, javaIndent, typeClass, outputName, strings.Join(ctorArgs, ", "), javaIndent)

	return b.String(), nil
}
// ---- Java literal serializer ----

// ToJavaMap serialises any value to a Java initializer expression using
// anonymous-subclass-style LinkedHashMap and ArrayList so ordering is preserved
// and there is no 10-key limit.
func ToJavaMap(v any, indent int) string {
	switch val := v.(type) {
	case nil:
		return "null"
	case bool:
		if val {
			return "true"
		}
		return "false"
	case float64:
		if val == float64(int64(val)) {
			return fmt.Sprintf("%dL", int64(val))
		}
		return fmt.Sprintf("%g", val)
	case string:
		return fmt.Sprintf("%q", val)
	case []any:
		return sliceToJava(val, indent)
	case map[string]any:
		return mapToJava(val, indent)
	default:
		data, _ := json.Marshal(val)
		var parsed any
		_ = json.Unmarshal(data, &parsed)
		return ToJavaMap(parsed, indent)
	}
}

func mapToJava(m map[string]any, indent int) string {
	if len(m) == 0 {
		return "java.util.Collections.emptyMap()"
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	prefix  := strings.Repeat(javaIndent, indent+1)
	closing := strings.Repeat(javaIndent, indent)

	var b strings.Builder
	b.WriteString("new java.util.LinkedHashMap<String, Object>() {{\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "%sput(%q, %s);\n", prefix, k, ToJavaMap(m[k], indent+1))
	}
	b.WriteString(closing + "}}")
	return b.String()
}

func sliceToJava(arr []any, indent int) string {
	if len(arr) == 0 {
		return "java.util.Collections.emptyList()"
	}
	prefix  := strings.Repeat(javaIndent, indent+1)
	closing := strings.Repeat(javaIndent, indent)

	var b strings.Builder
	b.WriteString("new java.util.ArrayList<Object>(java.util.Arrays.asList(\n")
	for i, val := range arr {
		b.WriteString(prefix + ToJavaMap(val, indent+1))
		if i < len(arr)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString(closing + "))")
	return b.String()
}

// ---- Helpers ----

func writeJavaHeader(b *strings.Builder, artifact *types.CompiledArtifact) {
	b.WriteString("// Generated by aifn — do not edit manually.\n")
	fmt.Fprintf(b, "// Package: %s v%s\n\n", artifact.Package.Name, artifact.Package.Version)
}

func jsonSchemaToJavaType(prop map[string]any) string {
	t, _ := prop["type"].(string)
	switch t {
	case "string":
		return "String"
	case "boolean":
		return "Boolean"
	case "integer":
		return "Integer"
	case "number":
		return "Double"
	case "array":
		if items, ok := prop["items"].(map[string]any); ok {
			return "java.util.List<" + jsonSchemaToJavaType(items) + ">"
		}
		return "java.util.List<Object>"
	case "object":
		return "java.util.Map<String, Object>"
	default:
		return "Object"
	}
}

func javaCoerceExpr(jType, valExpr string) string {
	switch jType {
	case "String":
		return fmt.Sprintf("(%s instanceof String) ? (String) %s : String.valueOf(%s)", valExpr, valExpr, valExpr)
	case "Integer":
		return fmt.Sprintf("(%s instanceof Number) ? ((Number) %s).intValue() : null", valExpr, valExpr)
	case "Double":
		return fmt.Sprintf("(%s instanceof Number) ? ((Number) %s).doubleValue() : null", valExpr, valExpr)
	case "Boolean":
		return fmt.Sprintf("(%s instanceof Boolean) ? (Boolean) %s : null", valExpr, valExpr)
	case "java.util.Map<String, Object>":
		return fmt.Sprintf("(%s instanceof java.util.Map<?,?>) ? (java.util.Map<String, Object>) %s : null", valExpr, valExpr)
	default:
		if strings.HasPrefix(jType, "java.util.List<") {
			return fmt.Sprintf("(%s instanceof java.util.List<?>) ? (%s) %s : null", valExpr, jType, valExpr)
		}
		return fmt.Sprintf("(%s) %s", jType, valExpr)
	}
}

func javaTypeNeedsUncheckedCast(jType string) bool {
	return jType == "java.util.Map<String, Object>" || strings.HasPrefix(jType, "java.util.List<")
}

func toPascalCase(s string) string {
	parts := splitIdentifier(s)
	var b strings.Builder
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + strings.ToLower(p[1:]))
	}
	return b.String()
}

func toCamelCase(s string) string {
	// If the key already has uppercase letters it is already camelCase — preserve it.
	if strings.ContainsAny(s, "ABCDEFGHIJKLMNOPQRSTUVWXYZ") {
		return s
	}
	parts := splitIdentifier(s)
	var b strings.Builder
	for i, p := range parts {
		if len(p) == 0 {
			continue
		}
		if i == 0 {
			b.WriteString(strings.ToLower(p))
		} else {
			b.WriteString(strings.ToUpper(p[:1]) + strings.ToLower(p[1:]))
		}
	}
	return b.String()
}

func sanitizePackageName(name string) string {
	name = strings.TrimPrefix(name, "@")
	if idx := strings.LastIndex(name, "/"); idx >= 0 {
		name = name[idx+1:]
	}
	name = strings.ReplaceAll(name, "-", "_")
	return strings.ToLower(name)
}

func splitIdentifier(s string) []string {
	s = strings.TrimPrefix(s, "@")
	s = strings.ReplaceAll(s, "-", "_")
	if idx := strings.LastIndex(s, "/"); idx >= 0 {
		s = s[idx+1:]
	}
	return strings.Split(s, "_")
}

func sortedKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func requiredSet(schema map[string]any) map[string]bool {
	set := make(map[string]bool)
	arr, _ := schema["required"].([]any)
	for _, v := range arr {
		if s, ok := v.(string); ok {
			set[s] = true
		}
	}
	return set
}

func isRequired(key string, schema map[string]any) bool {
	return requiredSet(schema)[key]
}
