// Generated by aifn -- do not edit manually.
// Package: explain-stream v1.0.0

import { executeStream } from '../_engine/typescript/v0.2.0/index';
import type { AIFuncArtifact, AIFuncConfig } from '../_engine/typescript/v0.2.0/index';
import artifact from './explain-stream.aifunc';
import type { ExplainStreamInput, ExplainStreamOutput } from './explain-stream.types';

export type { AIFuncConfig, ExplainStreamInput, ExplainStreamOutput };

/** Stream a clear explanation of a concept, code snippet, or term. Returns plain text. */
export async function* explainStream(config: AIFuncConfig = {}, input: ExplainStreamInput): AsyncIterable<ExplainStreamOutput> {
  const _projectDefaults = {};

  const runtimeConfig: AIFuncConfig = config;

  yield* executeStream(
    artifact as AIFuncArtifact,
    input as unknown as Record<string, unknown>,
    runtimeConfig,
    _projectDefaults,
  );
}
