// Generated by aifn — do not edit manually.
// Package: chat-stream v1.0.0

namespace Aifunc.ChatStream;

using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading;
using Aifunc;
using Aifunc.Engine.Csharp.V0_2_0;

/// <summary>Send a message and stream a plain-text reply. Optionally include context such as prior turns.</summary>
public static class ChatStream
{
	/// <summary>
	/// Send a message and stream a plain-text reply. Optionally include context such as prior turns.
	/// </summary>
	/// <remarks>
	/// Pass a <see cref="CancellationToken"/> to cancel the stream at any time.
	/// <code>
	/// using var cts = new CancellationTokenSource();
	/// await foreach (var token in ChatStreamAsync(config, input, cts.Token))
	///     Console.Write(token);
	/// </code>
	/// </remarks>
	public static async IAsyncEnumerable<string> ChatStreamAsync(
		AIFuncConfig? config,
		ChatStreamTypes.ChatStreamInput input,
		[EnumeratorCancellation] CancellationToken cancellationToken = default)
	{
		if (config is null)
			config = new AIFuncConfig();


		var artifact = Artifact.FromMap(ChatStreamAifunc.ARTIFACT_DATA);
		var inputMap = InputToMap(input);
		await foreach (var token in Runtime.ExecuteStreamAsync(
			artifact, inputMap, config, cancellationToken))
		{
			yield return token;
		}
	}

	private static System.Collections.Generic.Dictionary<string, object?> InputToMap(ChatStreamTypes.ChatStreamInput input)
	{
		var m = new System.Collections.Generic.Dictionary<string, object?>();
		if (input.Context is not null) m["context"] = input.Context;
		m["message"] = input.Message;
		return m;
	}

}
