// Generated by aifn — do not edit manually.
// Package: chat-stream v1.0.0

package aifunc.chat_stream;

import aifunc.AIFuncConfig;
import aifunc._engine.java.v0_2_0.Runtime;
import aifunc._engine.java.v0_2_0.Artifact;
import aifunc._engine.java.v0_2_0.Types.AIFuncArtifact;
import java.util.LinkedHashMap;
import java.util.Map;

/** Send a message and stream a plain-text reply. Optionally include context such as prior turns. */
/** Generated by aifn — do not edit manually. */
public final class ChatStream {

	private ChatStream() {}

	/**
	 * Stream tokens from the model.
	 * Returns a {@link ChatStreamTypes.TokenStream} — use it in a try-with-resources block;
	 * {@code break} automatically cancels the stream and frees the background thread.
	 */
	public static ChatStreamTypes.TokenStream chatStream(AIFuncConfig config, ChatStreamTypes.ChatStreamInput input) {
		if (config == null) config = AIFuncConfig.builder().build();

		AIFuncArtifact artifact = Artifact.fromMap(ChatStreamAifunc.ARTIFACT_DATA);
		Map<String, Object> inputMap = inputToMap(input);
		return new ChatStreamTypes.TokenStream(Runtime.executeStream(artifact, inputMap, config));
	}

	private static Map<String, Object> inputToMap(ChatStreamTypes.ChatStreamInput input) {
		Map<String, Object> m = new LinkedHashMap<>();
		if (input.getContext() != null) m.put("context", input.getContext());
		m.put("message", input.getMessage());
		return m;
	}
}

