# Generated by aifn -- do not edit manually.
# Package: extract-keywords v1.0.0

from typing import Any, Optional
from dataclasses import dataclass


@dataclass
class ExtractKeywordsInput:
    text: str  # The text to extract keywords from.
    max_keywords: Optional[int] = None  # Maximum number of keywords to return. Defaults to 10.


@dataclass
class ExtractKeywordsOutput:
    keywords: list[dict[str, Any]]  # Extracted keywords sorted by relevance (highest first).

