// Copyright 2026 GildenEye
// SPDX-License-Identifier: Apache-2.0

package python

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"aifunc/cli/internal/types"
)

const (
	pythonIndent   = "    "
	filePerm       = 0644
	dirPerm        = 0755
	inputSuffix    = "Input"
	outputSuffix   = "Output"
)

// outputIsStream returns true when the output schema declares x-delivery-mode: stream.
func outputIsStream(schema map[string]any) bool {
	if mode, _ := schema["x-delivery-mode"].(string); mode == "stream" {
		return true
	}
	return false
}

// Generate writes __init__.py, <name>_types.py, and <name>_aifunc.py for the given compiled artifact into outputDir.
func Generate(artifact *types.CompiledArtifact, outputDir string, hasMock bool, engineVersion string, cfg types.AifuncConfig) error {
	if err := os.MkdirAll(outputDir, dirPerm); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	fileBase := sanitizeFileName(artifact.Package.Name)

	files := []struct {
		name      string
		generator func() (string, error)
	}{
		{fileBase + "_types.py", func() (string, error) { return generateTypes(artifact) }},
		{fileBase + "_aifunc.py", func() (string, error) { return generateArtifactModule(artifact) }},
		{"__init__.py", func() (string, error) { return generateInit(artifact, hasMock, engineVersion, cfg) }},
	}

	for _, f := range files {
		if err := writeFile(outputDir, f.name, f.generator); err != nil {
			return err
		}
	}

	return nil
}

func writeFile(dir, filename string, generator func() (string, error)) error {
	content, err := generator()
	if err != nil {
		return fmt.Errorf("generate %s: %w", filename, err)
	}
	if err := os.WriteFile(filepath.Join(dir, filename), []byte(content), filePerm); err != nil {
		return fmt.Errorf("write %s: %w", filename, err)
	}
	return nil
}

func generateTypes(artifact *types.CompiledArtifact) (string, error) {
	var b strings.Builder

	writeHeader(&b, artifact)
	isStream := outputIsStream(artifact.API.Output)

	b.WriteString("from typing import Any, Optional\nfrom dataclasses import dataclass\n\n\n")

	baseName := toPascalCase(artifact.API.Name)
	writeDataclass(&b, baseName+inputSuffix, schemaToDataclassFields(artifact.API.Input))

	if !isStream {
		b.WriteString("\n\n")
		writeDataclass(&b, baseName+outputSuffix, schemaToDataclassFields(artifact.API.Output))
	}
	b.WriteString("\n")

	return b.String(), nil
}

func writeHeader(b *strings.Builder, artifact *types.CompiledArtifact) {
	b.WriteString("# Generated by aifn -- do not edit manually.\n")
	b.WriteString(fmt.Sprintf("# Package: %s v%s\n\n", artifact.Package.Name, artifact.Package.Version))
}

func writeDataclass(b *strings.Builder, name, fields string) {
	b.WriteString("@dataclass\nclass ")
	b.WriteString(name)
	b.WriteString(":\n")
	if fields == "" {
		b.WriteString(pythonIndent)
		b.WriteString("pass\n")
	} else {
		b.WriteString(fields)
	}
}

func generateInit(artifact *types.CompiledArtifact, hasMock bool, engineVersion string, cfg types.AifuncConfig) (string, error) {
	isStream := outputIsStream(artifact.API.Output)
	if isStream {
		return generateInitStream(artifact, hasMock, engineVersion, cfg)
	}
	return generateInitNormal(artifact, hasMock, engineVersion, cfg)
}

func generateInitNormal(artifact *types.CompiledArtifact, hasMock bool, engineVersion string, cfg types.AifuncConfig) (string, error) {
	var b strings.Builder

	fileBase := sanitizeFileName(artifact.Package.Name)
	funcName := toSnakeCase(artifact.API.Name)
	baseName := toPascalCase(artifact.API.Name)
	inputName := baseName + inputSuffix
	outputName := baseName + outputSuffix

	writeHeader(&b, artifact)
	b.WriteString("from typing import Any, Optional, Union\nfrom dataclasses import asdict, replace\n\n")

	engineVer := strings.ReplaceAll(engineVersion, ".", "_")
	b.WriteString(fmt.Sprintf("from .._engine.python.v%s import execute, AIFuncConfig, AIFuncArtifact, ProjectDefaults\n", engineVer))
	b.WriteString(fmt.Sprintf("from .%s_aifunc import artifact\n", fileBase))
	if hasMock {
		b.WriteString(fmt.Sprintf("from .%s_mock import mock_data\n", fileBase))
	}
	b.WriteString(fmt.Sprintf("from .%s_types import %s, %s\n\n", fileBase, inputName, outputName))
	b.WriteString(fmt.Sprintf("__all__ = [\"AIFuncConfig\", \"%s\", \"%s\", \"%s\"]\n\n\n", inputName, outputName, funcName))

	b.WriteString(fmt.Sprintf("async def %s(config: Optional[AIFuncConfig], input_data: Union[%s, dict[str, Any]]) -> %s:\n", funcName, inputName, outputName))
	b.WriteString(fmt.Sprintf("    \"\"\"%s\"\"\"\n", artifact.API.Description))
	writeMockConfigBlock(&b, hasMock)

	b.WriteString("\n    _artifact = AIFuncArtifact.from_dict(artifact)\n")
	b.WriteString("    if isinstance(input_data, dict):\n")
	b.WriteString("        _input = input_data\n")
	b.WriteString("    else:\n")
	b.WriteString("        _input = _to_camel_dict(asdict(input_data))\n")
	projectDefaultsLiteral := buildProjectDefaultsLiteral(cfg)
	b.WriteString(fmt.Sprintf("    _project_defaults = %s\n", projectDefaultsLiteral))
	b.WriteString("    result = await execute(_artifact, _input, config, _project_defaults)\n")
	b.WriteString(fmt.Sprintf("    return %s(**_to_snake_dict(result))\n\n\n", outputName))

	writeHelpers(&b)
	return b.String(), nil
}

func generateInitStream(artifact *types.CompiledArtifact, hasMock bool, engineVersion string, cfg types.AifuncConfig) (string, error) {
	var b strings.Builder

	fileBase := sanitizeFileName(artifact.Package.Name)
	funcName := toSnakeCase(artifact.API.Name)
	baseName := toPascalCase(artifact.API.Name)
	inputName := baseName + inputSuffix

	writeHeader(&b, artifact)
	b.WriteString("from typing import Any, Optional, Union, AsyncGenerator\nfrom dataclasses import asdict, replace\n\n")

	engineVer := strings.ReplaceAll(engineVersion, ".", "_")
	b.WriteString(fmt.Sprintf("from .._engine.python.v%s import execute_stream, AIFuncConfig, AIFuncArtifact, ProjectDefaults\n", engineVer))
	b.WriteString(fmt.Sprintf("from .%s_aifunc import artifact\n", fileBase))
	if hasMock {
		b.WriteString(fmt.Sprintf("from .%s_mock import mock_data\n", fileBase))
	}
	b.WriteString(fmt.Sprintf("from .%s_types import %s\n\n", fileBase, inputName))
	b.WriteString(fmt.Sprintf("__all__ = [\"AIFuncConfig\", \"%s\", \"%s\"]\n\n\n", inputName, funcName))

	b.WriteString(fmt.Sprintf("async def %s(\n", funcName))
	b.WriteString(fmt.Sprintf("    config: Optional[AIFuncConfig],\n"))
	b.WriteString(fmt.Sprintf("    input_data: Union[%s, dict[str, Any]],\n", inputName))
	b.WriteString(fmt.Sprintf(") -> AsyncGenerator[str, None]:\n"))
	b.WriteString(fmt.Sprintf("    \"\"\"%s\"\"\"\n", artifact.API.Description))
	writeMockConfigBlock(&b, hasMock)
	b.WriteString("\n    _artifact = AIFuncArtifact.from_dict(artifact)\n")
	b.WriteString("    if isinstance(input_data, dict):\n")
	b.WriteString("        _input = input_data\n")
	b.WriteString("    else:\n")
	b.WriteString("        _input = _to_camel_dict(asdict(input_data))\n")
	projectDefaultsLiteral := buildProjectDefaultsLiteral(cfg)
	b.WriteString(fmt.Sprintf("    _project_defaults = %s\n", projectDefaultsLiteral))
	b.WriteString("    return await execute_stream(_artifact, _input, config, _project_defaults)\n\n\n")

	writeHelpers(&b)
	return b.String(), nil
}

func writeMockConfigBlock(b *strings.Builder, hasMock bool) {
	if hasMock {
		b.WriteString("    if config is None:\n")
		b.WriteString("        config = AIFuncConfig(mock=True, mock_data=mock_data)\n")
		b.WriteString("    elif config.mock and config.mock_data is None:\n")
		b.WriteString("        config = replace(config, mock_data=mock_data)\n")
	} else {
		b.WriteString("    if config is None:\n")
		b.WriteString("        config = AIFuncConfig()\n")
	}
}

func writeHelpers(b *strings.Builder) {
	b.WriteString("def _to_camel(name: str) -> str:\n")
	b.WriteString("    parts = name.split(\"_\")\n")
	b.WriteString("    return parts[0] + \"\".join(p.capitalize() for p in parts[1:])\n\n\n")
	b.WriteString("def _to_snake(name: str) -> str:\n")
	b.WriteString("    result = []\n")
	b.WriteString("    for ch in name:\n")
	b.WriteString("        if ch.isupper() and result:\n")
	b.WriteString("            result.append(\"_\")\n")
	b.WriteString("        result.append(ch.lower())\n")
	b.WriteString("    return \"\".join(result)\n\n\n")
	b.WriteString("def _to_camel_dict(d: dict) -> dict:\n")
	b.WriteString("    return {_to_camel(k): v for k, v in d.items() if v is not None}\n\n\n")
	b.WriteString("def _to_snake_dict(d: dict) -> dict:\n")
	b.WriteString("    return {_to_snake(k): v for k, v in d.items()}\n")
}

func generateArtifactModule(artifact *types.CompiledArtifact) (string, error) {
	var b strings.Builder
	b.WriteString("# Generated by aifn -- do not edit manually.\n\nartifact = ")
	b.WriteString(ToPython(artifact, 0))
	b.WriteString("\n")
	return b.String(), nil
}

func ToPython(v any, indent int) string {
	switch val := v.(type) {
	case nil:
		return "None"
	case bool:
		if val {
			return "True"
		}
		return "False"
	case float64:
		if val == float64(int64(val)) {
			return fmt.Sprintf("%d", int64(val))
		}
		return fmt.Sprintf("%g", val)
	case string:
		return fmt.Sprintf("%q", val)
	case []any:
		return listToPython(val, indent)
	case map[string]any:
		return dictToPython(val, indent)
	default:
		data, _ := json.Marshal(val)
		var parsed any
		json.Unmarshal(data, &parsed)
		return ToPython(parsed, indent)
	}
}

func dictToPython(m map[string]any, indent int) string {
	if len(m) == 0 {
		return "{}"
	}

	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("{\n")

	nextIndent := indent + 1
	prefix := strings.Repeat(pythonIndent, nextIndent)

	for _, k := range keys {
		v := m[k]
		b.WriteString(prefix)
		b.WriteString(fmt.Sprintf("%q: ", k))
		b.WriteString(ToPython(v, nextIndent))
		b.WriteString(",\n")
	}

	b.WriteString(strings.Repeat(pythonIndent, indent))
	b.WriteString("}")
	return b.String()
}

func listToPython(arr []any, indent int) string {
	if len(arr) == 0 {
		return "[]"
	}

	var b strings.Builder
	b.WriteString("[\n")

	nextIndent := indent + 1
	prefix := strings.Repeat(pythonIndent, nextIndent)

	for _, v := range arr {
		b.WriteString(prefix)
		b.WriteString(ToPython(v, nextIndent))
		b.WriteString(",\n")
	}

	b.WriteString(strings.Repeat(pythonIndent, indent))
	b.WriteString("]")
	return b.String()
}

func schemaToDataclassFields(schema map[string]any) string {
	schemaType, _ := schema["type"].(string)
	if schemaType != "object" {
		return ""
	}

	props, ok := schema["properties"].(map[string]any)
	if !ok || len(props) == 0 {
		return ""
	}

	required := requiredSet(schema)

	keys := make([]string, 0, len(props))
	for key := range props {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	var requiredFields, optionalFields []string

	for _, key := range keys {
		val := props[key]
		prop, ok := val.(map[string]any)
		if !ok {
			continue
		}

		pyType := jsonSchemaToPythonType(prop)
		desc, _ := prop["description"].(string)
		fieldName := camelToSnake(key)

		line := formatField(fieldName, pyType, desc, required[key])
		if required[key] {
			requiredFields = append(requiredFields, line)
		} else {
			optionalFields = append(optionalFields, line)
		}
	}

	var b strings.Builder
	for _, f := range requiredFields {
		b.WriteString(f)
	}
	for _, f := range optionalFields {
		b.WriteString(f)
	}
	return b.String()
}

func formatField(name, pyType, desc string, isRequired bool) string {
	var b strings.Builder
	b.WriteString(pythonIndent)
	b.WriteString(name)
	b.WriteString(": ")
	
	if !isRequired {
		b.WriteString("Optional[")
		b.WriteString(pyType)
		b.WriteString("] = None")
	} else {
		b.WriteString(pyType)
	}
	
	if desc != "" {
		b.WriteString("  # ")
		b.WriteString(desc)
	}
	b.WriteString("\n")
	return b.String()
}

func requiredSet(schema map[string]any) map[string]bool {
	set := make(map[string]bool)
	arr, _ := schema["required"].([]any)
	for _, v := range arr {
		if s, ok := v.(string); ok {
			set[s] = true
		}
	}
	return set
}

func jsonSchemaToPythonType(prop map[string]any) string {
	t, _ := prop["type"].(string)

	switch t {
	case "string":
		return "str"
	case "boolean":
		return "bool"
	case "integer":
		return "int"
	case "number":
		return "float"
	case "array":
		if items, ok := prop["items"].(map[string]any); ok {
			return "list[" + jsonSchemaToPythonType(items) + "]"
		}
		return "list[Any]"
	case "object":
		return "dict[str, Any]"
	default:
		return "Any"
	}
}

func toPascalCase(s string) string {
	parts := splitIdentifier(s)
	var b strings.Builder
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}

func toSnakeCase(s string) string {
	parts := splitIdentifier(s)
	var result []string
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		result = append(result, strings.ToLower(p))
	}
	return strings.Join(result, "_")
}

func camelToSnake(s string) string {
	var result strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				result.WriteByte('_')
			}
			result.WriteRune(r + 32)
		} else if r == '-' {
			result.WriteByte('_')
		} else {
			result.WriteRune(r)
		}
	}
	return result.String()
}

func sanitizeFileName(name string) string {
	name = strings.TrimPrefix(name, "@")
	name = strings.ReplaceAll(name, "/", "__")
	name = strings.ReplaceAll(name, "-", "_")
	return name
}

func splitIdentifier(s string) []string {
	s = strings.ReplaceAll(s, "-", "_")
	return strings.Split(s, "_")
}

func buildProjectDefaultsLiteral(cfg types.AifuncConfig) string {
	var parts []string
	if cfg.Timeout != nil {
		timeoutSec := float64(*cfg.Timeout) / 1000.0
		parts = append(parts, fmt.Sprintf("timeout=%g", timeoutSec))
	}
	if cfg.MaxRetries != nil {
		parts = append(parts, fmt.Sprintf("max_retries=%d", *cfg.MaxRetries))
	}
	if len(parts) == 0 {
		return "ProjectDefaults()"
	}
	return "ProjectDefaults(" + strings.Join(parts, ", ") + ")"
}
