// Generated by aifn -- do not edit manually.
// Package: generate-title v1.0.0

export interface GenerateTitleInput {
  /** The text, summary, or topic to generate titles for. */
  content: string;
  /** Number of title candidates to generate. Default: 3. */
  count?: number;
  /** Maximum character count per title. Default: 80. */
  maxLength?: number;
  /** Title style: 'neutral', 'clickbait', 'seo', 'academic'. Default: 'neutral'. */
  style?: string;
}

export interface GenerateTitleOutput {
  /** Generated title candidates, ordered from most to least recommended. */
  titles: string[];
}
