// Copyright 2026 GildenEye
// SPDX-License-Identifier: Apache-2.0

package csharp

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"aifunc/cli/internal/types"
)

const (
	csharpIndent = "\t"
	filePerm     = 0644
	dirPerm      = 0755
	defaultNS    = "Aifunc"
)

// Generate writes <Name>Types.cs, <Name>Aifunc.cs, <Name>AifuncMock.cs,
// and <Name>.cs for the given compiled artifact into outputDir.
// rootNamespace is the root C# namespace prefix (e.g. "Aifunc").
func Generate(artifact *types.CompiledArtifact, outputDir string, hasMock bool, engineVersion string, cfg types.AifuncConfig, rootNamespace string) error {
	if rootNamespace == "" {
		rootNamespace = defaultNS
	}
	if err := os.MkdirAll(outputDir, dirPerm); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	baseName := toPascalCase(artifact.Package.Name)
	pkgName := sanitizePackageName(artifact.Package.Name)
	ns := packageNamespace(rootNamespace, pkgName)
	engineNS := engineNamespace(rootNamespace, engineVersion)

	type fileSpec struct {
		name      string
		generator func() (string, error)
	}

	files := []fileSpec{
		{baseName + "Types.cs", func() (string, error) {
			return generateTypes(artifact, ns)
		}},
		{baseName + "Aifunc.cs", func() (string, error) {
			return generateArtifact(artifact, ns)
		}},
	}

	if hasMock {
		files = append(files, fileSpec{baseName + "AifuncMock.cs", func() (string, error) {
			return generateMockStub(artifact, ns)
		}})
	}

	files = append(files, fileSpec{baseName + ".cs", func() (string, error) {
		return generateEntry(artifact, ns, baseName, hasMock, engineNS, cfg, rootNamespace)
	}})

	for _, f := range files {
		content, err := f.generator()
		if err != nil {
			return fmt.Errorf("generate %s: %w", f.name, err)
		}
		if err := os.WriteFile(filepath.Join(outputDir, f.name), []byte(content), filePerm); err != nil {
			return fmt.Errorf("write %s: %w", f.name, err)
		}
	}
	return nil
}

// GenerateRootTypes writes AIFuncConfig.cs and AIFuncException.cs to the
// output root directory (namespace "Aifunc" or whatever rootNamespace is).
// These are shared across all installed packages. Optional when the CLI
// promotes them from the engine package instead.
func GenerateRootTypes(outputDir string, rootNamespace string) error {
	if rootNamespace == "" {
		rootNamespace = defaultNS
	}
	if err := os.MkdirAll(outputDir, dirPerm); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	cfgContent := generateAIFuncConfig(rootNamespace)
	if err := os.WriteFile(filepath.Join(outputDir, "AIFuncConfig.cs"), []byte(cfgContent), filePerm); err != nil {
		return fmt.Errorf("write AIFuncConfig.cs: %w", err)
	}

	excContent := generateAIFuncException(rootNamespace)
	if err := os.WriteFile(filepath.Join(outputDir, "AIFuncException.cs"), []byte(excContent), filePerm); err != nil {
		return fmt.Errorf("write AIFuncException.cs: %w", err)
	}
	return nil
}

func generateAIFuncConfig(rootNS string) string {
	return `// Generated by aifn — do not edit manually.

namespace ` + rootNS + `;

/// <summary>
/// Controls the function's runtime mode and model connection.
/// Use object initializers to construct an instance.
/// </summary>
public sealed class AIFuncConfig
{
    public string? BaseUrl { get; init; }
    public string? ApiKey { get; init; }
    public string? Model { get; init; }
    public double? Temperature { get; init; }
    public double? TopP { get; init; }
    public int? MaxTokens { get; init; }
    public int TimeoutMs { get; init; } = 0;
    public int MaxRetries { get; init; } = 0;
    public bool Mock { get; init; } = false;
    public object? MockData { get; init; }

    /// <summary>
    /// Returns a copy with selected properties overridden (mirrors Java <c>toBuilder</c>).
    /// Pass <paramref name="mockData"/> together with <paramref name="setMockData"/>=<c>true</c>
    /// to replace or clear mock data (including setting it to <c>null</c>).
    /// </summary>
    public AIFuncConfig With(
        string? baseUrl = null,
        string? apiKey = null,
        string? model = null,
        double? temperature = null,
        double? topP = null,
        int? maxTokens = null,
        int? timeoutMs = null,
        int? maxRetries = null,
        bool? mock = null,
        object? mockData = null,
        bool setMockData = false)
    {
        return new AIFuncConfig
        {
            BaseUrl     = baseUrl     ?? BaseUrl,
            ApiKey      = apiKey      ?? ApiKey,
            Model       = model       ?? Model,
            Temperature = temperature ?? Temperature,
            TopP        = topP        ?? TopP,
            MaxTokens   = maxTokens   ?? MaxTokens,
            TimeoutMs   = timeoutMs   ?? TimeoutMs,
            MaxRetries  = maxRetries  ?? MaxRetries,
            Mock        = mock        ?? Mock,
            MockData    = setMockData ? mockData : (mockData ?? MockData),
        };
    }

    /// <summary>Returns a copy with <see cref="MockData"/> replaced.</summary>
    public AIFuncConfig WithMockData(object? mockData) =>
        With(mockData: mockData, setMockData: true);
}
`
}

func generateAIFuncException(rootNS string) string {
	return `// Generated by aifn — do not edit manually.

using System;

namespace ` + rootNS + `;

/// <summary>
/// Thrown by the engine when execution fails.
/// </summary>
public sealed class AIFuncException : Exception
{
    public AIFuncException(string message) : base(message) {}
    public AIFuncException(string message, Exception? inner) : base(message, inner) {}
}
`
}

// ---- Types file ----

func generateTypes(artifact *types.CompiledArtifact, ns string) (string, error) {
	var b strings.Builder
	writeCSharpHeader(&b, artifact)
	fmt.Fprintf(&b, "namespace %s;\n\n", ns)
	b.WriteString("using System.Collections.Generic;\n\n")
	fmt.Fprintf(&b, "public static class %sTypes\n{\n", toPascalCase(artifact.Package.Name))

	baseName := toPascalCase(artifact.API.Name)
	writeCSharpPojo(&b, baseName+"Input", artifact.API.Input)
	b.WriteString("\n")
	writeCSharpPojo(&b, baseName+"Output", artifact.API.Output)
	b.WriteString("}\n")
	return b.String(), nil
}

func writeCSharpPojo(b *strings.Builder, className string, schema map[string]any) {
	props, _ := schema["properties"].(map[string]any)
	required := requiredSet(schema)

	var reqKeys, optKeys []string
	for _, k := range sortedKeys(props) {
		if required[k] {
			reqKeys = append(reqKeys, k)
		} else {
			optKeys = append(optKeys, k)
		}
	}
	allKeys := append(reqKeys, optKeys...)

	fmt.Fprintf(b, "%spublic sealed class %s\n%s{\n", csharpIndent, className, csharpIndent)

	for _, key := range allKeys {
		prop, ok := props[key].(map[string]any)
		if !ok {
			continue
		}
		desc, _ := prop["description"].(string)
		csType := jsonSchemaToCSharpType(prop, required[key])
		propName := toPascalCase(key)
		if desc != "" {
			fmt.Fprintf(b, "%s%s/// <summary>%s</summary>\n", csharpIndent, csharpIndent, desc)
		}
		if required[key] {
			fmt.Fprintf(b, "%s%spublic %s %s { get; }\n", csharpIndent, csharpIndent, csType, propName)
		} else {
			fmt.Fprintf(b, "%s%spublic %s %s { get; set; }\n", csharpIndent, csharpIndent, csType, propName)
		}
	}
	b.WriteString("\n")

	// constructor: required params first, then optional with = null
	var params []string
	for _, key := range allKeys {
		prop, ok := props[key].(map[string]any)
		if !ok {
			continue
		}
		csType := jsonSchemaToCSharpType(prop, required[key])
		param := toCamelCase(key)
		if required[key] {
			params = append(params, csType+" "+param)
		} else {
			params = append(params, csType+" "+param+" = null")
		}
	}

	if len(params) > 0 || len(reqKeys) > 0 {
		fmt.Fprintf(b, "%s%spublic %s(%s)\n%s%s{\n", csharpIndent, csharpIndent, className, strings.Join(params, ", "), csharpIndent, csharpIndent)
		for _, key := range allKeys {
			if _, ok := props[key].(map[string]any); !ok {
				continue
			}
			propName := toPascalCase(key)
			param := toCamelCase(key)
			fmt.Fprintf(b, "%s%s%s%s = %s;\n", csharpIndent, csharpIndent, csharpIndent, propName, param)
		}
		fmt.Fprintf(b, "%s%s}\n", csharpIndent, csharpIndent)
	} else {
		fmt.Fprintf(b, "%s%spublic %s() {}\n", csharpIndent, csharpIndent, className)
	}

	fmt.Fprintf(b, "%s}\n", csharpIndent)
}

// ---- Artifact data file ----

func generateArtifact(artifact *types.CompiledArtifact, ns string) (string, error) {
	var b strings.Builder
	writeCSharpHeader(&b, artifact)
	fmt.Fprintf(&b, "namespace %s;\n\n", ns)
	b.WriteString("using System.Collections.Generic;\n\n")
	fmt.Fprintf(&b, "internal static class %sAifunc\n{\n", toPascalCase(artifact.Package.Name))
	b.WriteString(csharpIndent + "internal static readonly Dictionary<string, object?> ARTIFACT_DATA =\n")
	b.WriteString(csharpIndent + csharpIndent + ToCSharpLiteral(artifact, 2) + ";\n}\n")
	return b.String(), nil
}

// ---- Mock stub (overwritten later with real data) ----

func generateMockStub(artifact *types.CompiledArtifact, ns string) (string, error) {
	var b strings.Builder
	writeCSharpHeader(&b, artifact)
	basePascal := toPascalCase(artifact.Package.Name)
	fmt.Fprintf(&b, "namespace %s;\n\n", ns)
	fmt.Fprintf(&b, "internal static class %sAifuncMock\n{\n", basePascal)
	b.WriteString(csharpIndent + "internal static readonly object? MOCK_DATA = null;\n}\n")
	return b.String(), nil
}

// WriteMockFile writes the mock data C# file from parsed mock.json content.
func WriteMockFile(mockRaw any, artifact *types.CompiledArtifact, pkgOutputDir, pkgName, rootNamespace string) error {
	if rootNamespace == "" {
		rootNamespace = defaultNS
	}
	basePascal := toPascalCase(artifact.Package.Name)
	ns := packageNamespace(rootNamespace, pkgName)
	var b strings.Builder
	writeCSharpHeader(&b, artifact)
	fmt.Fprintf(&b, "namespace %s;\n\n", ns)
	b.WriteString("using System.Collections.Generic;\n\n")
	fmt.Fprintf(&b, "internal static class %sAifuncMock\n{\n", basePascal)
	b.WriteString(csharpIndent + "internal static readonly object? MOCK_DATA =\n")
	b.WriteString(csharpIndent + csharpIndent + ToCSharpLiteral(mockRaw, 2) + ";\n}\n")
	return os.WriteFile(filepath.Join(pkgOutputDir, basePascal+"AifuncMock.cs"), []byte(b.String()), filePerm)
}

// ---- Entry file ----

func generateEntry(artifact *types.CompiledArtifact, ns, baseName string, hasMock bool, engineNS string, cfg types.AifuncConfig, rootNS string) (string, error) {
	var b strings.Builder

	funcPascal := toPascalCase(artifact.API.Name)
	inputName := funcPascal + "Input"
	outputName := funcPascal + "Output"
	typeClass := baseName + "Types"
	methodName := funcPascal + "Async"

	writeCSharpHeader(&b, artifact)
	fmt.Fprintf(&b, "namespace %s;\n\n", ns)
	b.WriteString("using System;\n")
	b.WriteString("using System.Collections.Generic;\n")
	b.WriteString("using System.Threading.Tasks;\n")
	fmt.Fprintf(&b, "using %s;\n", rootNS)
	fmt.Fprintf(&b, "using %s;\n\n", engineNS)

	desc := artifact.API.Description
	if desc == "" {
		desc = artifact.Package.Description
	}
	if desc != "" {
		fmt.Fprintf(&b, "/// <summary>%s</summary>\n", desc)
	}
	fmt.Fprintf(&b, "public static class %s\n{\n", baseName)

	if hasMock {
		fmt.Fprintf(&b, "%sprivate static readonly object? MOCK_DATA = %sAifuncMock.MOCK_DATA;\n\n", csharpIndent, baseName)
	}

	fmt.Fprintf(&b, "%spublic static async Task<%s.%s> %s(AIFuncConfig? config, %s.%s input)\n%s{\n",
		csharpIndent, typeClass, outputName, methodName, typeClass, inputName, csharpIndent)

	if hasMock {
		fmt.Fprintf(&b, "%s%sif (config is null)\n", csharpIndent, csharpIndent)
		fmt.Fprintf(&b, "%s%s%sconfig = new AIFuncConfig { Mock = true, MockData = MOCK_DATA };\n", csharpIndent, csharpIndent, csharpIndent)
		fmt.Fprintf(&b, "%s%selse if (config.Mock && config.MockData is null)\n", csharpIndent, csharpIndent)
		fmt.Fprintf(&b, "%s%s%sconfig = config.WithMockData(MOCK_DATA);\n\n", csharpIndent, csharpIndent, csharpIndent)
	} else {
		fmt.Fprintf(&b, "%s%sif (config is null)\n", csharpIndent, csharpIndent)
		fmt.Fprintf(&b, "%s%s%sconfig = new AIFuncConfig();\n\n", csharpIndent, csharpIndent, csharpIndent)
	}

	if cfg.Timeout != nil {
		fmt.Fprintf(&b, "%s%sif (config.TimeoutMs == 0) config = config.With(timeoutMs: %d);\n", csharpIndent, csharpIndent, *cfg.Timeout)
	}
	if cfg.MaxRetries != nil {
		fmt.Fprintf(&b, "%s%sif (config.MaxRetries == 0) config = config.With(maxRetries: %d);\n", csharpIndent, csharpIndent, *cfg.MaxRetries)
	}

	b.WriteString("\n")
	fmt.Fprintf(&b, "%s%svar artifact = Artifact.FromMap(%sAifunc.ARTIFACT_DATA);\n", csharpIndent, csharpIndent, baseName)
	fmt.Fprintf(&b, "%s%svar inputMap = InputToMap(input);\n", csharpIndent, csharpIndent)
	fmt.Fprintf(&b, "%s%svar result = await Runtime.ExecuteAsync(artifact, inputMap, config).ConfigureAwait(false);\n", csharpIndent, csharpIndent)
	fmt.Fprintf(&b, "%s%sreturn MapToOutput(result);\n", csharpIndent, csharpIndent)
	fmt.Fprintf(&b, "%s}\n\n", csharpIndent)

	// InputToMap
	fmt.Fprintf(&b, "%sprivate static Dictionary<string, object?> InputToMap(%s.%s input)\n%s{\n", csharpIndent, typeClass, inputName, csharpIndent)
	fmt.Fprintf(&b, "%s%svar m = new Dictionary<string, object?>();\n", csharpIndent, csharpIndent)
	inputProps, _ := artifact.API.Input["properties"].(map[string]any)
	for _, key := range sortedKeys(inputProps) {
		propName := toPascalCase(key)
		if isRequired(key, artifact.API.Input) {
			fmt.Fprintf(&b, "%s%sm[%q] = input.%s;\n", csharpIndent, csharpIndent, key, propName)
		} else {
			fmt.Fprintf(&b, "%s%sif (input.%s is not null) m[%q] = input.%s;\n", csharpIndent, csharpIndent, propName, key, propName)
		}
	}
	fmt.Fprintf(&b, "%s%sreturn m;\n%s}\n\n", csharpIndent, csharpIndent, csharpIndent)

	// MapToOutput
	outputProps, _ := artifact.API.Output["properties"].(map[string]any)
	outputRequired := requiredSet(artifact.API.Output)
	var reqOutKeys, optOutKeys []string
	for _, k := range sortedKeys(outputProps) {
		if outputRequired[k] {
			reqOutKeys = append(reqOutKeys, k)
		} else {
			optOutKeys = append(optOutKeys, k)
		}
	}
	allOutKeys := append(reqOutKeys, optOutKeys...)

	fmt.Fprintf(&b, "%sprivate static %s.%s MapToOutput(Dictionary<string, object?> m)\n%s{\n", csharpIndent, typeClass, outputName, csharpIndent)
	for i, key := range allOutKeys {
		prop, ok := outputProps[key].(map[string]any)
		if !ok {
			continue
		}
		csType := jsonSchemaToCSharpType(prop, outputRequired[key])
		field := toCamelCase(key)
		tmp := fmt.Sprintf("_v%d", i)
		coerce := csharpCoerceExpr(csType, tmp, i)
		fmt.Fprintf(&b, "%s%s%s %s;\n", csharpIndent, csharpIndent, csType, field)
		fmt.Fprintf(&b, "%s%sif (m.TryGetValue(%q, out var %s))\n", csharpIndent, csharpIndent, key, tmp)
		fmt.Fprintf(&b, "%s%s%s%s = %s;\n", csharpIndent, csharpIndent, csharpIndent, field, coerce)
		fmt.Fprintf(&b, "%s%selse\n", csharpIndent, csharpIndent)
		fmt.Fprintf(&b, "%s%s%s%s = %s;\n", csharpIndent, csharpIndent, csharpIndent, field, csharpDefaultExpr(csType))
	}
	var ctorArgs []string
	for _, key := range allOutKeys {
		if _, ok := outputProps[key].(map[string]any); ok {
			ctorArgs = append(ctorArgs, toCamelCase(key))
		}
	}
	fmt.Fprintf(&b, "%s%sreturn new %s.%s(%s);\n%s}\n}\n", csharpIndent, csharpIndent, typeClass, outputName, strings.Join(ctorArgs, ", "), csharpIndent)

	return b.String(), nil
}

// ---- C# literal serializer ----

// ToCSharpLiteral serialises any value to a C# initializer expression using
// Dictionary / List constructors so ordering is preserved.
func ToCSharpLiteral(v any, indent int) string {
	switch val := v.(type) {
	case nil:
		return "null"
	case bool:
		if val {
			return "true"
		}
		return "false"
	case float64:
		if val == float64(int64(val)) {
			return fmt.Sprintf("(double)%d", int64(val))
		}
		return fmt.Sprintf("%g", val)
	case string:
		return csharpQuote(val)
	case []any:
		return sliceToCSharp(val, indent)
	case map[string]any:
		return mapToCSharp(val, indent)
	default:
		data, _ := json.Marshal(val)
		var parsed any
		_ = json.Unmarshal(data, &parsed)
		return ToCSharpLiteral(parsed, indent)
	}
}

func mapToCSharp(m map[string]any, indent int) string {
	if len(m) == 0 {
		return "new Dictionary<string, object?>()"
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	prefix := strings.Repeat(csharpIndent, indent+1)
	closing := strings.Repeat(csharpIndent, indent)

	var b strings.Builder
	b.WriteString("new Dictionary<string, object?>\n")
	b.WriteString(closing + "{\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "%s[%s] = %s,\n", prefix, csharpQuote(k), ToCSharpLiteral(m[k], indent+1))
	}
	b.WriteString(closing + "}")
	return b.String()
}

func sliceToCSharp(arr []any, indent int) string {
	if len(arr) == 0 {
		return "new List<object?>()"
	}
	prefix := strings.Repeat(csharpIndent, indent+1)
	closing := strings.Repeat(csharpIndent, indent)

	var b strings.Builder
	b.WriteString("new List<object?>\n")
	b.WriteString(closing + "{\n")
	for _, val := range arr {
		fmt.Fprintf(&b, "%s%s,\n", prefix, ToCSharpLiteral(val, indent+1))
	}
	b.WriteString(closing + "}")
	return b.String()
}

func csharpQuote(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		case '\x00':
			b.WriteString(`\0`)
		default:
			if r < 0x20 {
				fmt.Fprintf(&b, `\u%04x`, r)
			} else {
				b.WriteRune(r)
			}
		}
	}
	b.WriteByte('"')
	return b.String()
}

// ---- Helpers ----

func writeCSharpHeader(b *strings.Builder, artifact *types.CompiledArtifact) {
	b.WriteString("// Generated by aifn — do not edit manually.\n")
	fmt.Fprintf(b, "// Package: %s v%s\n\n", artifact.Package.Name, artifact.Package.Version)
}

func packageNamespace(rootNS, pkgName string) string {
	return rootNS + "." + toPascalCase(pkgName)
}

func engineNamespace(rootNS, engineVersion string) string {
	// engineVersion "0.1.0" → namespace segment V0_1_0
	return rootNS + ".Engine.Csharp.V" + strings.ReplaceAll(engineVersion, ".", "_")
}

func jsonSchemaToCSharpType(prop map[string]any, required bool) string {
	t, _ := prop["type"].(string)
	switch t {
	case "string":
		if required {
			return "string"
		}
		return "string?"
	case "boolean":
		if required {
			return "bool"
		}
		return "bool?"
	case "integer":
		if required {
			return "int"
		}
		return "int?"
	case "number":
		if required {
			return "double"
		}
		return "double?"
	case "array":
		inner := "object?"
		if items, ok := prop["items"].(map[string]any); ok {
			inner = jsonSchemaToCSharpElementType(items)
		}
		if required {
			return "List<" + inner + ">"
		}
		return "List<" + inner + ">?"
	case "object":
		if required {
			return "Dictionary<string, object?>"
		}
		return "Dictionary<string, object?>?"
	default:
		if required {
			return "object"
		}
		return "object?"
	}
}

// Element types inside List<> are non-nullable when the schema type is known.
func jsonSchemaToCSharpElementType(prop map[string]any) string {
	t, _ := prop["type"].(string)
	switch t {
	case "string":
		return "string"
	case "boolean":
		return "bool"
	case "integer":
		return "int"
	case "number":
		return "double"
	case "array":
		if items, ok := prop["items"].(map[string]any); ok {
			return "List<" + jsonSchemaToCSharpElementType(items) + ">"
		}
		return "List<object?>"
	case "object":
		return "Dictionary<string, object?>"
	default:
		return "object?"
	}
}

func csharpCoerceExpr(csType, tmpVar string, idx int) string {
	base := strings.TrimSuffix(csType, "?")
	switch base {
	case "string":
		if strings.HasSuffix(csType, "?") {
			return fmt.Sprintf("%s is string _s%d ? _s%d : %s?.ToString()", tmpVar, idx, idx, tmpVar)
		}
		return fmt.Sprintf("%s is string _s%d ? _s%d : (%s?.ToString() ?? \"\")", tmpVar, idx, idx, tmpVar)
	case "int":
		return fmt.Sprintf("%s is IConvertible _c%d ? Convert.ToInt32(_c%d) : %s", tmpVar, idx, idx, csharpDefaultExpr(csType))
	case "double":
		return fmt.Sprintf("%s is IConvertible _c%d ? Convert.ToDouble(_c%d) : %s", tmpVar, idx, idx, csharpDefaultExpr(csType))
	case "bool":
		return fmt.Sprintf("%s is bool _b%d ? _b%d : %s", tmpVar, idx, idx, csharpDefaultExpr(csType))
	case "Dictionary<string, object?>":
		return fmt.Sprintf("%s is Dictionary<string, object?> _d%d ? _d%d : %s", tmpVar, idx, idx, csharpDefaultExpr(csType))
	default:
		if strings.HasPrefix(base, "List<") {
			return fmt.Sprintf("%s is %s _l%d ? _l%d : %s", tmpVar, base, idx, idx, csharpDefaultExpr(csType))
		}
		return fmt.Sprintf("%s as %s", tmpVar, csType)
	}
}

func csharpDefaultExpr(csType string) string {
	if strings.HasSuffix(csType, "?") {
		return "null"
	}
	switch csType {
	case "string":
		return `""`
	case "int":
		return "0"
	case "double":
		return "0.0"
	case "bool":
		return "false"
	case "Dictionary<string, object?>":
		return "new Dictionary<string, object?>()"
	default:
		if strings.HasPrefix(csType, "List<") {
			return "new " + csType + "()"
		}
		return "null!"
	}
}

// toPascalCase converts snake_case, kebab-case, or camelCase identifiers to PascalCase.
// camelCase keys (e.g. maxLength) keep internal capitals → MaxLength.
func toPascalCase(s string) string {
	c := toCamelCase(s)
	if c == "" {
		return ""
	}
	return strings.ToUpper(c[:1]) + c[1:]
}

func toCamelCase(s string) string {
	// If the key already has uppercase letters it is already camelCase — preserve it.
	if strings.ContainsAny(s, "ABCDEFGHIJKLMNOPQRSTUVWXYZ") {
		return s
	}
	parts := splitIdentifier(s)
	var b strings.Builder
	for i, p := range parts {
		if len(p) == 0 {
			continue
		}
		if i == 0 {
			b.WriteString(strings.ToLower(p))
		} else {
			b.WriteString(strings.ToUpper(p[:1]) + strings.ToLower(p[1:]))
		}
	}
	return b.String()
}

func sanitizePackageName(name string) string {
	name = strings.TrimPrefix(name, "@")
	if idx := strings.LastIndex(name, "/"); idx >= 0 {
		name = name[idx+1:]
	}
	name = strings.ReplaceAll(name, "-", "_")
	return strings.ToLower(name)
}

func splitIdentifier(s string) []string {
	s = strings.TrimPrefix(s, "@")
	s = strings.ReplaceAll(s, "-", "_")
	if idx := strings.LastIndex(s, "/"); idx >= 0 {
		s = s[idx+1:]
	}
	return strings.Split(s, "_")
}

func sortedKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func requiredSet(schema map[string]any) map[string]bool {
	set := make(map[string]bool)
	arr, _ := schema["required"].([]any)
	for _, v := range arr {
		if s, ok := v.(string); ok {
			set[s] = true
		}
	}
	return set
}

func isRequired(key string, schema map[string]any) bool {
	return requiredSet(schema)[key]
}
