// Generated by aifn — do not edit manually.
// Package: generate-title v1.0.0

namespace Aifunc.GenerateTitle;

using System.Collections.Generic;

internal static class GenerateTitleAifunc
{
	internal static readonly Dictionary<string, object?> ARTIFACT_DATA =
		new Dictionary<string, object?>
		{
			["api"] = new Dictionary<string, object?>
			{
				["description"] = "Generate title or headline candidates for a piece of content.",
				["input"] = new Dictionary<string, object?>
				{
					["additionalProperties"] = false,
					["properties"] = new Dictionary<string, object?>
					{
						["content"] = new Dictionary<string, object?>
						{
							["description"] = "The text, summary, or topic to generate titles for.",
							["minLength"] = (double)1,
							["type"] = "string",
						},
						["count"] = new Dictionary<string, object?>
						{
							["description"] = "Number of title candidates to generate. Default: 3.",
							["maximum"] = (double)10,
							["minimum"] = (double)1,
							["type"] = "integer",
						},
						["maxLength"] = new Dictionary<string, object?>
						{
							["description"] = "Maximum character count per title. Default: 80.",
							["type"] = "integer",
						},
						["style"] = new Dictionary<string, object?>
						{
							["description"] = "Title style: 'neutral', 'clickbait', 'seo', 'academic'. Default: 'neutral'.",
							["type"] = "string",
						},
					},
					["required"] = new List<object?>
					{
						"content",
					},
					["type"] = "object",
				},
				["name"] = "generate-title",
				["output"] = new Dictionary<string, object?>
				{
					["additionalProperties"] = false,
					["properties"] = new Dictionary<string, object?>
					{
						["titles"] = new Dictionary<string, object?>
						{
							["description"] = "Generated title candidates, ordered from most to least recommended.",
							["items"] = new Dictionary<string, object?>
							{
								["type"] = "string",
							},
							["type"] = "array",
						},
					},
					["required"] = new List<object?>
					{
						"titles",
					},
					["type"] = "object",
				},
			},
			["artifactVersion"] = "0.1.0",
			["metadata"] = new Dictionary<string, object?>
			{
				["contentHash"] = "sha256:22ec3881fab0d05cf08324780aa9ed1dcddb7ff0cbfca1ab00cb289c0dd35ce4",
				["generatedAt"] = "2026-07-16T23:51:14Z",
				["sourcePackageVersion"] = "1.0.0",
			},
			["modelParams"] = new Dictionary<string, object?>
			{
				["rules"] = new List<object?>
				{
					new Dictionary<string, object?>
					{
						["match"] = new Dictionary<string, object?>
						{
							["pattern"] = ".*",
						},
						["params"] = new Dictionary<string, object?>
						{
							["maxTokens"] = (double)512,
							["temperature"] = 0.7,
						},
					},
				},
				["schemaVersion"] = "0.1.0",
			},
			["package"] = new Dictionary<string, object?>
			{
				["author"] = new Dictionary<string, object?>
				{
					["name"] = "GildenEye",
				},
				["description"] = "Generate title or headline candidates for a piece of content.",
				["engine"] = "^0.2.0",
				["name"] = "generate-title",
				["type"] = "standalone",
				["version"] = "1.0.0",
			},
			["prompts"] = new Dictionary<string, object?>
			{
				["general"] = "# System\n\nYou are a title generation function. You must only return a JSON object in the following format:\n{\"titles\": [\"<title 1>\", \"<title 2>\", ...]}\n\nDo not output Markdown, do not include any extra explanation, and do not add undeclared fields.\n\nRequirements:\n- Generate the requested number of title candidates (default: 3).\n- Order titles from most to least recommended.\n- Apply the requested style (default: neutral). 'clickbait' uses curiosity-driven language; 'seo' front-loads keywords; 'academic' is formal and descriptive.\n- Each title must not exceed maxLength characters (default: 80).\n- Titles should be distinct from each other — vary wording and angle.\n\n# User\n\nContent:\n{{content}}\n\nStyle: {{style}}\n\nCount: {{count}}\n\nMax length per title: {{maxLength}}\n",
			},
			["schemaVersion"] = "0.1.0",
		};
}
