// Generated by aifn — do not edit manually.
// Package: generate-title v1.0.0

namespace Aifunc.GenerateTitle;

using System.Collections.Generic;

internal static class GenerateTitleAifuncMock
{
	internal static readonly object? MOCK_DATA =
		new Dictionary<string, object?>
		{
			["cases"] = new List<object?>
			{
				new Dictionary<string, object?>
				{
					["description"] = "Generate neutral title candidates for a blog post.",
					["id"] = "blog-titles",
					["output"] = new Dictionary<string, object?>
					{
						["titles"] = new List<object?>
						{
							"How to Build Better Habits That Actually Stick",
							"The Science Behind Lasting Habit Formation",
							"A Practical Guide to Changing Your Daily Routines",
						},
					},
				},
			},
			["delay"] = new Dictionary<string, object?>
			{
				["maxMs"] = (double)120,
				["minMs"] = (double)30,
			},
			["random"] = new Dictionary<string, object?>
			{
				["enabled"] = false,
				["seed"] = "generate-title",
			},
			["version"] = "1.0.0",
		};
}
