// Generated by aifn — do not edit manually.
// Package: generate-title v1.0.0

namespace Aifunc.GenerateTitle;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Aifunc;
using Aifunc.Engine.Csharp.V0_2_0;

/// <summary>Generate title or headline candidates for a piece of content.</summary>
public static class GenerateTitle
{
	private static readonly object? MOCK_DATA = GenerateTitleAifuncMock.MOCK_DATA;

	public static async Task<GenerateTitleTypes.GenerateTitleOutput> GenerateTitleAsync(AIFuncConfig? config, GenerateTitleTypes.GenerateTitleInput input)
	{
		if (config is null)
			config = new AIFuncConfig { Mock = true, MockData = MOCK_DATA };
		else if (config.Mock && config.MockData is null)
			config = config.WithMockData(MOCK_DATA);


		var artifact = Artifact.FromMap(GenerateTitleAifunc.ARTIFACT_DATA);
		var inputMap = InputToMap(input);
		var result = await Runtime.ExecuteAsync(artifact, inputMap, config).ConfigureAwait(false);
		return MapToOutput(result);
	}

	private static System.Collections.Generic.Dictionary<string, object?> InputToMap(GenerateTitleTypes.GenerateTitleInput input)
	{
		var m = new System.Collections.Generic.Dictionary<string, object?>();
		m["content"] = input.Content;
		if (input.Count is not null) m["count"] = input.Count;
		if (input.MaxLength is not null) m["maxLength"] = input.MaxLength;
		if (input.Style is not null) m["style"] = input.Style;
		return m;
	}

	private static GenerateTitleTypes.GenerateTitleOutput MapToOutput(Dictionary<string, object?> m)
	{
		List<string> titles;
		if (m.TryGetValue("titles", out var _v0))
			titles = _v0 is List<string> _l0 ? _l0 : new List<string>();
		else
			titles = new List<string>();
		return new GenerateTitleTypes.GenerateTitleOutput(titles);
	}
}
