// Generated by aifn -- do not edit manually.
// Package: extract-keywords v1.0.0

package extract_keywords

// ExtractKeywordsInput holds the input parameters.
type ExtractKeywordsInput struct {
	// The text to extract keywords from.
	Text string
	// Maximum number of keywords to return. Defaults to 10.
	MaxKeywords *int
}

// ExtractKeywordsOutput holds the function result.
type ExtractKeywordsOutput struct {
	// Extracted keywords sorted by relevance (highest first).
	Keywords []map[string]any
}
