// Generated by aifn -- do not edit manually.
// Package: generate-post v1.0.0

export interface GeneratePostInput {
  /** Whether to append relevant hashtags. Default: false. */
  includeHashtags?: boolean;
  /** Maximum character count. */
  maxLength?: number;
  /** Target platform: 'twitter', 'linkedin', 'instagram', 'general'. Default: 'general'. */
  platform?: string;
  /** Desired tone (e.g. 'professional', 'casual', 'inspirational'). Default: 'casual'. */
  tone?: string;
  /** The subject or key idea of the post. */
  topic: string;
}

export interface GeneratePostOutput {
  /** Character count of the generated post. */
  charCount: number;
  /** Suggested hashtags (empty if includeHashtags is false). */
  hashtags: string[];
  /** The generated post content. */
  post: string;
}
