// Generated by aifn — do not edit manually.
// Package: score-quality v1.0.0

package aifunc.score_quality;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
@SuppressWarnings("serial")
final class ScoreQualityAifuncMock {

	private ScoreQualityAifuncMock() {}

	static final Object MOCK_DATA =
		new java.util.LinkedHashMap<String, Object>() {{
			put("cases", new java.util.ArrayList<Object>(java.util.Arrays.asList(
				new java.util.LinkedHashMap<String, Object>() {{
					put("description", "Evaluate quality of a developer-facing documentation paragraph.");
					put("id", "developer-doc");
					put("output", new java.util.LinkedHashMap<String, Object>() {{
						put("actionabilityScore", 62L);
						put("clarityScore", 78L);
						put("level", "good");
						put("overallScore", 72L);
						put("structureScore", 70L);
						put("suggestions", new java.util.ArrayList<Object>(java.util.Arrays.asList(
							"Add a concrete code example to illustrate the main concept.",
							"Break the paragraph into shorter sections with subheadings.",
							"End with a clear next step or call to action."
						)));
						put("summary", "The text is clear and well-toned but could be more actionable and better structured.");
						put("toneScore", 80L);
					}});
				}}
			)));
			put("delay", new java.util.LinkedHashMap<String, Object>() {{
				put("maxMs", 150L);
				put("minMs", 50L);
			}});
			put("random", new java.util.LinkedHashMap<String, Object>() {{
				put("enabled", false);
				put("seed", "score-quality");
			}});
			put("version", "1.0.0");
		}};
}
