// Generated by aifn — do not edit manually.
// Package: score-quality v1.0.0

package aifunc.score_quality;

import aifunc.AIFuncConfig;
import aifunc._engine.java.v0_1_0.Runtime;
import aifunc._engine.java.v0_1_0.Artifact;
import aifunc._engine.java.v0_1_0.Types.AIFuncArtifact;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

/** Evaluate text quality across multiple dimensions and return structured scores with improvement advice. */
/** Generated by aifn — do not edit manually. */
public final class ScoreQuality {

	private ScoreQuality() {}

	private static final Object MOCK_DATA = ScoreQualityAifuncMock.MOCK_DATA;

	public static CompletableFuture<ScoreQualityTypes.ScoreQualityOutput> scoreQuality(AIFuncConfig config, ScoreQualityTypes.ScoreQualityInput input) {
		if (config == null) {
			config = AIFuncConfig.builder().mock(true).mockData(MOCK_DATA).build();
		} else if (config.isMock() && config.getMockData() == null) {
			config = config.toBuilder().mockData(MOCK_DATA).build();
		}


		AIFuncArtifact artifact = Artifact.fromMap(ScoreQualityAifunc.ARTIFACT_DATA);
		Map<String, Object> inputMap = inputToMap(input);
		return Runtime.executeAsync(artifact, inputMap, config)
			.thenApply(ScoreQuality::mapToOutput);
	}

	private static Map<String, Object> inputToMap(ScoreQualityTypes.ScoreQualityInput input) {
		Map<String, Object> m = new LinkedHashMap<>();
		if (input.getMaxSuggestions() != null) m.put("maxSuggestions", input.getMaxSuggestions());
		if (input.getPurpose() != null) m.put("purpose", input.getPurpose());
		if (input.getStrictness() != null) m.put("strictness", input.getStrictness());
		if (input.getTargetAudience() != null) m.put("targetAudience", input.getTargetAudience());
		m.put("text", input.getText());
		return m;
	}

	@SuppressWarnings("unchecked")
	private static ScoreQualityTypes.ScoreQualityOutput mapToOutput(Map<String, Object> m) {
		Integer actionabilityScore = m.containsKey("actionabilityScore") ? (m.get("actionabilityScore") instanceof Number) ? ((Number) m.get("actionabilityScore")).intValue() : null : null;
		Integer clarityScore = m.containsKey("clarityScore") ? (m.get("clarityScore") instanceof Number) ? ((Number) m.get("clarityScore")).intValue() : null : null;
		String level = m.containsKey("level") ? (m.get("level") instanceof String) ? (String) m.get("level") : String.valueOf(m.get("level")) : null;
		Integer overallScore = m.containsKey("overallScore") ? (m.get("overallScore") instanceof Number) ? ((Number) m.get("overallScore")).intValue() : null : null;
		Integer structureScore = m.containsKey("structureScore") ? (m.get("structureScore") instanceof Number) ? ((Number) m.get("structureScore")).intValue() : null : null;
		java.util.List<String> suggestions = m.containsKey("suggestions") ? (m.get("suggestions") instanceof java.util.List<?>) ? (java.util.List<String>) m.get("suggestions") : null : null;
		String summary = m.containsKey("summary") ? (m.get("summary") instanceof String) ? (String) m.get("summary") : String.valueOf(m.get("summary")) : null;
		Integer toneScore = m.containsKey("toneScore") ? (m.get("toneScore") instanceof Number) ? ((Number) m.get("toneScore")).intValue() : null : null;
		return new ScoreQualityTypes.ScoreQualityOutput(actionabilityScore, clarityScore, level, overallScore, structureScore, suggestions, summary, toneScore);
	}
}
