// Generated by aifn — do not edit manually.
// Package: score-quality v1.0.0

package aifunc.score_quality;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
public final class ScoreQualityTypes {

	private ScoreQualityTypes() {}

	public static final class ScoreQualityInput {
		/** The text content to evaluate. */
		private final String text;
		/** Maximum number of improvement suggestions to return. */
		private Integer maxSuggestions;
		/** Writing purpose (e.g. 'explanation', 'marketing', 'support', 'learning'). */
		private String purpose;
		/** Evaluation strictness from 1 (lenient) to 5 (very strict). */
		private Integer strictness;
		/** Intended readers (e.g. 'developers', 'customers', 'students', 'executives'). */
		private String targetAudience;

		public ScoreQualityInput(String text, Integer maxSuggestions, String purpose, Integer strictness, String targetAudience) {
			this.text = text;
			this.maxSuggestions = maxSuggestions;
			this.purpose = purpose;
			this.strictness = strictness;
			this.targetAudience = targetAudience;
		}

		public String getText() { return text; }
		public Integer getMaxSuggestions() { return maxSuggestions; }
		public void setMaxSuggestions(Integer v) { this.maxSuggestions = v; }
		public String getPurpose() { return purpose; }
		public void setPurpose(String v) { this.purpose = v; }
		public Integer getStrictness() { return strictness; }
		public void setStrictness(Integer v) { this.strictness = v; }
		public String getTargetAudience() { return targetAudience; }
		public void setTargetAudience(String v) { this.targetAudience = v; }
	}

	public static final class ScoreQualityOutput {
		/** How actionable and useful the text is, from 0 to 100. */
		private final Integer actionabilityScore;
		/** Clarity score from 0 to 100. */
		private final Integer clarityScore;
		/** Overall quality level. */
		private final String level;
		/** Overall quality score from 0 to 100. */
		private final Integer overallScore;
		/** Organization and logical structure score from 0 to 100. */
		private final Integer structureScore;
		/** Concise improvement suggestions, ordered by importance. */
		private final java.util.List<String> suggestions;
		/** One short sentence summarizing the evaluation. */
		private final String summary;
		/** Tone suitability score from 0 to 100. */
		private final Integer toneScore;

		public ScoreQualityOutput(Integer actionabilityScore, Integer clarityScore, String level, Integer overallScore, Integer structureScore, java.util.List<String> suggestions, String summary, Integer toneScore) {
			this.actionabilityScore = actionabilityScore;
			this.clarityScore = clarityScore;
			this.level = level;
			this.overallScore = overallScore;
			this.structureScore = structureScore;
			this.suggestions = suggestions;
			this.summary = summary;
			this.toneScore = toneScore;
		}

		public Integer getActionabilityScore() { return actionabilityScore; }
		public Integer getClarityScore() { return clarityScore; }
		public String getLevel() { return level; }
		public Integer getOverallScore() { return overallScore; }
		public Integer getStructureScore() { return structureScore; }
		public java.util.List<String> getSuggestions() { return suggestions; }
		public String getSummary() { return summary; }
		public Integer getToneScore() { return toneScore; }
	}
}
