// Generated by aifn — do not edit manually.
// Package: score-quality v1.0.0

package aifunc.score_quality;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
@SuppressWarnings("serial")
final class ScoreQualityAifunc {

	private ScoreQualityAifunc() {}

	static final java.util.Map<String, Object> ARTIFACT_DATA =
		new java.util.LinkedHashMap<String, Object>() {{
			put("api", new java.util.LinkedHashMap<String, Object>() {{
				put("description", "Evaluate text quality across multiple dimensions and return structured scores with improvement advice.");
				put("input", new java.util.LinkedHashMap<String, Object>() {{
					put("additionalProperties", false);
					put("properties", new java.util.LinkedHashMap<String, Object>() {{
						put("maxSuggestions", new java.util.LinkedHashMap<String, Object>() {{
							put("default", 3L);
							put("description", "Maximum number of improvement suggestions to return.");
							put("maximum", 10L);
							put("minimum", 1L);
							put("type", "integer");
						}});
						put("purpose", new java.util.LinkedHashMap<String, Object>() {{
							put("default", "general communication");
							put("description", "Writing purpose (e.g. 'explanation', 'marketing', 'support', 'learning').");
							put("type", "string");
						}});
						put("strictness", new java.util.LinkedHashMap<String, Object>() {{
							put("default", 3L);
							put("description", "Evaluation strictness from 1 (lenient) to 5 (very strict).");
							put("maximum", 5L);
							put("minimum", 1L);
							put("type", "integer");
						}});
						put("targetAudience", new java.util.LinkedHashMap<String, Object>() {{
							put("default", "general readers");
							put("description", "Intended readers (e.g. 'developers', 'customers', 'students', 'executives').");
							put("type", "string");
						}});
						put("text", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "The text content to evaluate.");
							put("minLength", 1L);
							put("type", "string");
						}});
					}});
					put("required", new java.util.ArrayList<Object>(java.util.Arrays.asList(
						"text"
					)));
					put("type", "object");
				}});
				put("name", "score-quality");
				put("output", new java.util.LinkedHashMap<String, Object>() {{
					put("additionalProperties", false);
					put("properties", new java.util.LinkedHashMap<String, Object>() {{
						put("actionabilityScore", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "How actionable and useful the text is, from 0 to 100.");
							put("maximum", 100L);
							put("minimum", 0L);
							put("type", "integer");
						}});
						put("clarityScore", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Clarity score from 0 to 100.");
							put("maximum", 100L);
							put("minimum", 0L);
							put("type", "integer");
						}});
						put("level", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Overall quality level.");
							put("enum", new java.util.ArrayList<Object>(java.util.Arrays.asList(
								"excellent",
								"good",
								"fair",
								"poor"
							)));
							put("type", "string");
						}});
						put("overallScore", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Overall quality score from 0 to 100.");
							put("maximum", 100L);
							put("minimum", 0L);
							put("type", "integer");
						}});
						put("structureScore", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Organization and logical structure score from 0 to 100.");
							put("maximum", 100L);
							put("minimum", 0L);
							put("type", "integer");
						}});
						put("suggestions", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Concise improvement suggestions, ordered by importance.");
							put("items", new java.util.LinkedHashMap<String, Object>() {{
								put("type", "string");
							}});
							put("minItems", 0L);
							put("type", "array");
						}});
						put("summary", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "One short sentence summarizing the evaluation.");
							put("type", "string");
						}});
						put("toneScore", new java.util.LinkedHashMap<String, Object>() {{
							put("description", "Tone suitability score from 0 to 100.");
							put("maximum", 100L);
							put("minimum", 0L);
							put("type", "integer");
						}});
					}});
					put("required", new java.util.ArrayList<Object>(java.util.Arrays.asList(
						"overallScore",
						"clarityScore",
						"structureScore",
						"toneScore",
						"actionabilityScore",
						"level",
						"summary",
						"suggestions"
					)));
					put("type", "object");
				}});
			}});
			put("artifactVersion", "0.1.0");
			put("metadata", new java.util.LinkedHashMap<String, Object>() {{
				put("contentHash", "sha256:762f256bb8916716b45cb2a91f6c3692630d1124fcb890e1dac2542ec25a0fdc");
				put("generatedAt", "2026-07-12T06:36:23Z");
				put("sourcePackageVersion", "1.0.0");
			}});
			put("modelParams", new java.util.LinkedHashMap<String, Object>() {{
				put("rules", new java.util.ArrayList<Object>(java.util.Arrays.asList(
					new java.util.LinkedHashMap<String, Object>() {{
						put("match", new java.util.LinkedHashMap<String, Object>() {{
							put("pattern", ".*");
						}});
						put("params", new java.util.LinkedHashMap<String, Object>() {{
							put("maxTokens", 700L);
							put("temperature", 0.1);
							put("topP", 0.9);
						}});
					}},
					new java.util.LinkedHashMap<String, Object>() {{
						put("match", new java.util.LinkedHashMap<String, Object>() {{
							put("models", new java.util.ArrayList<Object>(java.util.Arrays.asList(
								"gpt-4o-mini",
								"gpt-4o"
							)));
						}});
						put("params", new java.util.LinkedHashMap<String, Object>() {{
							put("maxTokens", 650L);
							put("temperature", 0L);
						}});
						put("providerParams", new java.util.LinkedHashMap<String, Object>() {{
							put("openai", new java.util.LinkedHashMap<String, Object>() {{
								put("reasoningEffort", "low");
							}});
						}});
					}}
				)));
				put("schemaVersion", "0.1.0");
			}});
			put("package", new java.util.LinkedHashMap<String, Object>() {{
				put("author", new java.util.LinkedHashMap<String, Object>() {{
					put("name", "GildenEye");
				}});
				put("description", "Evaluate text quality across multiple dimensions and return structured scores with improvement advice.");
				put("engine", "^0.1.0");
				put("name", "score-quality");
				put("type", "standalone");
				put("version", "1.0.0");
			}});
			put("prompts", new java.util.LinkedHashMap<String, Object>() {{
				put("general", "# System\n\nYou are a strict text quality evaluation function. You must only return a JSON object in EXACTLY this format:\n{\"overallScore\": <0-100>, \"clarityScore\": <0-100>, \"structureScore\": <0-100>, \"toneScore\": <0-100>, \"actionabilityScore\": <0-100>, \"level\": \"<excellent|good|fair|poor>\", \"summary\": \"<one sentence>\", \"suggestions\": [\"...\"]}\n\nDo not output Markdown, do not include any extra explanation, and do not omit any fields.\n\nScoring dimensions:\n- overallScore: holistic usefulness and quality.\n- clarityScore: ease of understanding, precision, and lack of ambiguity.\n- structureScore: organization, flow, and logical sequencing.\n- toneScore: suitability for the target audience and purpose.\n- actionabilityScore: whether the reader can understand what to do or take away.\n\nLevel mapping:\n- excellent: overallScore >= 90\n- good: overallScore >= 75 and < 90\n- fair: overallScore >= 50 and < 75\n- poor: overallScore < 50\n\nsummary: one concise sentence summarizing the overall evaluation result.\n\nsuggestions: up to maxSuggestions concise, actionable improvement tips (default 3 if not specified).\n\n# User\n\nText to evaluate:\n{{text}}\n\nTarget audience:\n{{targetAudience}}\n\nPurpose:\n{{purpose}}\n\nMaximum suggestions:\n{{maxSuggestions}}\n\nStrictness from 1 to 5:\n{{strictness}}\n");
			}});
			put("schemaVersion", "0.1.0");
		}};
}
