// Generated by aifn -- do not edit manually.
// Package: analyze-sentiment v1.0.0

export interface AnalyzeSentimentInput {
  /** Candidate sentiment labels. Defaults to ["positive", "negative", "neutral"]. */
  labels?: string[];
  /** The text to analyze sentiment for. */
  text: string;
  /** Return only the top K labels by score. If omitted, return all. */
  topK?: number;
}

export interface AnalyzeSentimentOutput {
  /** Confidence score of the top label, between 0 and 1. */
  confidence: number;
  /** The highest-scoring sentiment label. */
  label: string;
  /** All labels ranked by score (highest first), limited by topK. */
  rankings: {
    label: string;
    score: number;
  }[];
}
