// Generated by aifn -- do not edit manually.
// Package: generate-post v1.0.0

package generate_post

// GeneratePostInput holds the input parameters.
type GeneratePostInput struct {
	// The subject or key idea of the post.
	Topic string
	// Whether to append relevant hashtags. Default: false.
	IncludeHashtags *bool
	// Maximum character count.
	MaxLength *int
	// Target platform: 'twitter', 'linkedin', 'instagram', 'general'. Default: 'general'.
	Platform *string
	// Desired tone (e.g. 'professional', 'casual', 'inspirational'). Default: 'casual'.
	Tone *string
}

// GeneratePostOutput holds the function result.
type GeneratePostOutput struct {
	// Character count of the generated post.
	CharCount int
	// Suggested hashtags (empty if includeHashtags is false).
	Hashtags []string
	// The generated post content.
	Post string
}
