// Generated by aifn - do not edit manually.

package answer_question

var answer_questionMockData any = map[string]any{
	"cases": []any{
		map[string]any{
			"description": "Answer a question based on provided context.",
			"id": "context-based-answer",
			"output": map[string]any{
				"answer": "The project was completed three weeks ahead of schedule due to the team's efficient sprint planning and early resolution of key technical blockers.",
				"confidence": 0.92,
				"grounded": true,
			},
		},
	},
	"delay": map[string]any{
		"maxMs": 120,
		"minMs": 30,
	},
	"random": map[string]any{
		"enabled": false,
		"seed": "answer-question",
	},
	"version": "1.0.0",
}
