# Generated by aifn -- do not edit manually.
# Package: chat-stream v1.0.0

from typing import Any, Optional, Union, AsyncGenerator
from dataclasses import asdict, replace

from .._engine.python.v0_2_0 import execute_stream, AIFuncConfig, AIFuncArtifact, ProjectDefaults
from .chat_stream_aifunc import artifact
from .chat_stream_types import ChatStreamInput

__all__ = ["AIFuncConfig", "ChatStreamInput", "chat_stream"]


async def chat_stream(
    config: Optional[AIFuncConfig],
    input_data: Union[ChatStreamInput, dict[str, Any]],
) -> AsyncGenerator[str, None]:
    """Stream a conversational AI reply from a message history. Returns plain text."""
    if config is None:
        config = AIFuncConfig()

    _artifact = AIFuncArtifact.from_dict(artifact)
    if isinstance(input_data, dict):
        _input = input_data
    else:
        _input = _to_camel_dict(asdict(input_data))
    _project_defaults = ProjectDefaults()
    return await execute_stream(_artifact, _input, config, _project_defaults)


def _to_camel(name: str) -> str:
    parts = name.split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def _to_snake(name: str) -> str:
    result = []
    for ch in name:
        if ch.isupper() and result:
            result.append("_")
        result.append(ch.lower())
    return "".join(result)


def _to_camel_dict(d: dict) -> dict:
    return {_to_camel(k): v for k, v in d.items() if v is not None}


def _to_snake_dict(d: dict) -> dict:
    return {_to_snake(k): v for k, v in d.items()}
