# Generated by aifn -- do not edit manually.
# Package: chat-stream v1.0.0

from typing import Any, Optional
from dataclasses import dataclass


@dataclass
class ChatStreamInput:
    messages: list[dict[str, Any]]  # Conversation history. Each item has a 'role' ('user' or 'assistant') and 'content' (string).
    language: Optional[str] = None  # Reply language. If omitted, matches the language of the last user message.
    system_prompt: Optional[str] = None  # Optional system-level instruction that sets the assistant's persona, role, or constraints.

