// Generated by aifn -- do not edit manually.
// Package: detect-language v1.0.0

package detect_language

import (
	"context"
	"fmt"

	engine "all-packages/aifunc/_engine/go/v0.2.0"
)

// AIFuncConfig controls the runtime mode and model connection.
type AIFuncConfig = engine.AIFuncConfig

// mockData contains the built-in offline test cases.
var mockData any = detect_languageMockData

// DetectLanguage Detect the language of input text, returning a language code, language name, and confidence score.
func DetectLanguage(ctx context.Context, config *AIFuncConfig, input DetectLanguageInput) (DetectLanguageOutput, error) {
	if config == nil {
		config = &AIFuncConfig{Mock: true, MockData: mockData}
	}
	if config.Mock && config.MockData == nil {
		copy := *config
		copy.MockData = mockData
		config = &copy
	}

	artifact, err := engine.ArtifactFromMap(artifactData)
	if err != nil {
		return DetectLanguageOutput{}, fmt.Errorf("load artifact: %w", err)
	}

	inputMap := inputToMap(input)

	result, err := engine.Execute(ctx, artifact, inputMap, *config)
	if err != nil {
		return DetectLanguageOutput{}, err
	}

	return mapToOutput(result), nil
}

func inputToMap(input DetectLanguageInput) map[string]any {
	m := map[string]any{}
	m["text"] = input.Text
	return m
}

func mapToOutput(m map[string]any) DetectLanguageOutput {
	var out DetectLanguageOutput
	if v, ok := m["confidence"]; ok { out.Confidence = coerceFloat64(v) }
	if v, ok := m["language"]; ok { out.Language = coerceString(v) }
	if v, ok := m["languageName"]; ok { out.LanguageName = coerceString(v) }
	return out
}

func coerceFloat64(v any) float64 {
	switch n := v.(type) {
	case float64:
		return n
	case int:
		return float64(n)
	}
	return 0
}

func coerceString(v any) string {
	if s, ok := v.(string); ok { return s }
	return fmt.Sprintf("%v", v)
}

