// Generated by aifn -- do not edit manually.
// Package: detect-language v1.0.0

package detect_language

// DetectLanguageInput holds the input parameters.
type DetectLanguageInput struct {
	// The text whose language should be detected.
	Text string
}

// DetectLanguageOutput holds the function result.
type DetectLanguageOutput struct {
	// Confidence score between 0 and 1.
	Confidence float64
	// Detected language code (e.g. 'en', 'zh-CN', 'ja', 'fr').
	Language string
	// Human-readable name of the detected language (e.g. 'English', '中文', '日本語').
	LanguageName string
}
