// Generated by aifn — do not edit manually.
// Package: article-stream v1.0.0

namespace Aifunc.ArticleStream;

using System.Collections.Generic;

public static class ArticleStreamTypes
{
	public sealed class ArticleStreamInput
	{
		/// <summary>The article title.</summary>
		public string Title { get; }
		/// <summary>Target audience (e.g. 'general readers', 'developers', 'executives'). Default: 'general readers'.</summary>
		public string? Audience { get; set; }
		/// <summary>Output language (e.g. 'English', 'Chinese'). If omitted, matches the title language.</summary>
		public string? Language { get; set; }
		/// <summary>Optional outline or key points to cover, one per line or as free text.</summary>
		public string? Outline { get; set; }
		/// <summary>Writing style or tone (e.g. 'informational', 'opinion', 'tutorial', 'news'). Default: 'informational'.</summary>
		public string? Style { get; set; }
		/// <summary>Approximate target word count. Default: 600. Range: 200–3000.</summary>
		public int? WordCount { get; set; }

		public ArticleStreamInput(string title, string? audience = null, string? language = null, string? outline = null, string? style = null, int? wordCount = null)
		{
			Title = title;
			Audience = audience;
			Language = language;
			Outline = outline;
			Style = style;
			WordCount = wordCount;
		}
	}
}
