// Generated by aifn -- do not edit manually.
// Package: classify v1.0.0

package classify

// ClassifyInput holds the input parameters.
type ClassifyInput struct {
	// List of candidate categories to classify into.
	Categories []string
	// The text to classify.
	Text string
	// If true, the text can be assigned to multiple categories. Defaults to false.
	AllowMultiple *bool
}

// ClassifyOutput holds the function result.
type ClassifyOutput struct {
	// Classification results sorted by confidence (highest first).
	Classifications []map[string]any
}
