// Generated by aifn — do not edit manually.
// Package: write-stream v1.0.0

namespace Aifunc.WriteStream;

using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading;
using Aifunc;
using Aifunc.Engine.Csharp.V0_2_0;

/// <summary>Stream long-form writing — articles, reports, or documents — from a prompt and optional structure. Returns plain text.</summary>
public static class WriteStream
{
	/// <summary>
	/// Stream long-form writing — articles, reports, or documents — from a prompt and optional structure. Returns plain text.
	/// </summary>
	/// <remarks>
	/// Pass a <see cref="CancellationToken"/> to cancel the stream at any time.
	/// <code>
	/// using var cts = new CancellationTokenSource();
	/// await foreach (var token in WriteStreamAsync(config, input, cts.Token))
	///     Console.Write(token);
	/// </code>
	/// </remarks>
	public static async IAsyncEnumerable<string> WriteStreamAsync(
		AIFuncConfig? config,
		WriteStreamTypes.WriteStreamInput input,
		[EnumeratorCancellation] CancellationToken cancellationToken = default)
	{
		if (config is null)
			config = new AIFuncConfig();


		var artifact = Artifact.FromMap(WriteStreamAifunc.ARTIFACT_DATA);
		var inputMap = InputToMap(input);
		await foreach (var token in Runtime.ExecuteStreamAsync(
			artifact, inputMap, config, cancellationToken))
		{
			yield return token;
		}
	}

	private static System.Collections.Generic.Dictionary<string, object?> InputToMap(WriteStreamTypes.WriteStreamInput input)
	{
		var m = new System.Collections.Generic.Dictionary<string, object?>();
		if (input.Audience is not null) m["audience"] = input.Audience;
		if (input.Format is not null) m["format"] = input.Format;
		if (input.Language is not null) m["language"] = input.Language;
		m["prompt"] = input.Prompt;
		if (input.Structure is not null) m["structure"] = input.Structure;
		if (input.Tone is not null) m["tone"] = input.Tone;
		if (input.WordCount is not null) m["wordCount"] = input.WordCount;
		return m;
	}

}
