// Generated by aifn — do not edit manually.
// Package: write-stream v1.0.0

namespace Aifunc.WriteStream;

using System.Collections.Generic;

internal static class WriteStreamAifunc
{
	internal static readonly Dictionary<string, object?> ARTIFACT_DATA =
		new Dictionary<string, object?>
		{
			["api"] = new Dictionary<string, object?>
			{
				["description"] = "Stream long-form writing — articles, reports, or documents — from a prompt and optional structure. Returns plain text.",
				["injectOutputSchema"] = false,
				["input"] = new Dictionary<string, object?>
				{
					["additionalProperties"] = false,
					["properties"] = new Dictionary<string, object?>
					{
						["audience"] = new Dictionary<string, object?>
						{
							["default"] = "general readers",
							["description"] = "Target audience (e.g. 'executives', 'engineers', 'general public'). Default: 'general readers'.",
							["type"] = "string",
						},
						["format"] = new Dictionary<string, object?>
						{
							["default"] = "article",
							["description"] = "Document format: 'article', 'report', 'proposal', 'documentation', 'essay'. Default: 'article'.",
							["enum"] = new List<object?>
							{
								"article",
								"report",
								"proposal",
								"documentation",
								"essay",
							},
							["type"] = "string",
						},
						["language"] = new Dictionary<string, object?>
						{
							["description"] = "Output language. If omitted, matches the language of the prompt.",
							["type"] = "string",
						},
						["prompt"] = new Dictionary<string, object?>
						{
							["description"] = "What to write. Can be a title, a brief, a set of requirements, or a full description of the desired content.",
							["minLength"] = (double)1,
							["type"] = "string",
						},
						["structure"] = new Dictionary<string, object?>
						{
							["description"] = "Optional outline, section headings, or structural notes to follow.",
							["type"] = "string",
						},
						["tone"] = new Dictionary<string, object?>
						{
							["default"] = "professional",
							["description"] = "Writing tone (e.g. 'formal', 'professional', 'academic', 'casual'). Default: 'professional'.",
							["type"] = "string",
						},
						["wordCount"] = new Dictionary<string, object?>
						{
							["default"] = (double)800,
							["description"] = "Approximate target word count. Default: 800. Range: 300–5000.",
							["maximum"] = (double)5000,
							["minimum"] = (double)300,
							["type"] = "integer",
						},
					},
					["required"] = new List<object?>
					{
						"prompt",
					},
					["type"] = "object",
				},
				["name"] = "write_stream",
				["output"] = new Dictionary<string, object?>
				{
					["description"] = "The generated document as plain text.",
					["type"] = "string",
					["x-delivery-mode"] = "stream",
				},
			},
			["artifactVersion"] = "0.1.0",
			["metadata"] = new Dictionary<string, object?>
			{
				["contentHash"] = "sha256:476d3ea71cfc031bd7beb05d349fea03c14f10d8519430ec7df44ed1dce5d9ec",
				["generatedAt"] = "2026-07-16T23:54:34Z",
				["sourcePackageVersion"] = "1.0.0",
			},
			["modelParams"] = new Dictionary<string, object?>
			{
				["rules"] = new List<object?>
				{
					new Dictionary<string, object?>
					{
						["match"] = new Dictionary<string, object?>
						{
							["pattern"] = ".*",
						},
						["params"] = new Dictionary<string, object?>
						{
							["maxTokens"] = (double)6144,
							["temperature"] = 0.7,
						},
					},
				},
				["schemaVersion"] = "0.1.0",
			},
			["package"] = new Dictionary<string, object?>
			{
				["author"] = new Dictionary<string, object?>
				{
					["name"] = "GildenEye",
				},
				["description"] = "Stream long-form writing — articles, reports, or documents — from a prompt and optional structure. Returns plain text.",
				["engine"] = "^0.2.0",
				["engineOptions"] = new Dictionary<string, object?>
				{
					["injectOutputSchema"] = false,
				},
				["name"] = "write-stream",
				["type"] = "standalone",
				["version"] = "1.0.0",
			},
			["prompts"] = new Dictionary<string, object?>
			{
				["general"] = "# System\n\nYou are an expert writer. Your task is to produce a complete, well-structured long-form document based on the given prompt.\n\n## Requirements\n\n- Format: {{input.format}} — follow the conventions and structure appropriate for this document type.\n- Tone: {{input.tone}} — maintain this tone consistently throughout.\n- Target audience: {{input.audience}} — calibrate vocabulary, depth, and assumed knowledge accordingly.\n- Write approximately {{input.wordCount}} words.\n- If a structure or outline is provided, follow it faithfully as the backbone of the document.\n- Begin directly with the document content. Do not include meta-commentary, preamble, or a note about what you are writing.\n- Output plain text only — no Markdown formatting, no JSON, no labels.\n- If a language is specified, write in that language. Otherwise, match the language of the prompt.\n- The document must be coherent, complete, and suitable for its intended purpose without further editing.\n\n## Input\n\nPrompt: {{input.prompt}}\n\nFormat: {{input.format}}\n\nStructure / Outline: {{input.structure}}\n\nTone: {{input.tone}}\n\nAudience: {{input.audience}}\n\nLanguage: {{input.language}}\n\nWord count target: {{input.wordCount}}\n",
			},
			["schemaVersion"] = "0.1.0",
		};
}
