// Generated by aifn — do not edit manually.
// Package: summarize v1.0.0

namespace Aifunc.Summarize;

using System.Collections.Generic;

internal static class SummarizeAifuncMock
{
	internal static readonly object? MOCK_DATA =
		new Dictionary<string, object?>
		{
			["cases"] = new List<object?>
			{
				new Dictionary<string, object?>
				{
					["description"] = "Basic summary example.",
					["id"] = "basic-summary",
					["output"] = new Dictionary<string, object?>
					{
						["summary"] = "This article introduces a common AI function for generating concise summaries from input text.",
						["wordCount"] = (double)16,
					},
				},
			},
			["delay"] = new Dictionary<string, object?>
			{
				["maxMs"] = (double)100,
				["minMs"] = (double)30,
			},
			["random"] = new Dictionary<string, object?>
			{
				["enabled"] = false,
				["seed"] = "short-summary",
			},
			["version"] = "1.0.0",
		};
}
