// Generated by aifn -- do not edit manually.
// Package: generate-title v1.0.0

package generate_title

// GenerateTitleInput holds the input parameters.
type GenerateTitleInput struct {
	// The text, summary, or topic to generate titles for.
	Content string
	// Number of title candidates to generate. Default: 3.
	Count *int
	// Maximum character count per title. Default: 80.
	MaxLength *int
	// Title style: 'neutral', 'clickbait', 'seo', 'academic'. Default: 'neutral'.
	Style *string
}

// GenerateTitleOutput holds the function result.
type GenerateTitleOutput struct {
	// Generated title candidates, ordered from most to least recommended.
	Titles []string
}
