// Generated by aifn -- do not edit manually.
// Package: classify v1.0.0

import { execute } from '../_engine/typescript/v0.2.0/index';
import type { AIFuncArtifact, AIFuncConfig } from '../_engine/typescript/v0.2.0/index';
import artifact from './classify.aifunc';
import mockData from './classify.mock';
import type { ClassifyInput, ClassifyOutput } from './classify.types';

export type { AIFuncConfig, ClassifyInput, ClassifyOutput };

/** Classify text into user-defined categories with confidence scores. */
export async function classify(config: AIFuncConfig = { mock: true }, input: ClassifyInput): Promise<ClassifyOutput> {
  const _projectDefaults = {};

  const runtimeConfig: AIFuncConfig = config.mock && !config.mockData
    ? { ...config, mockData }
    : config;

  return execute<ClassifyOutput>(
    artifact as AIFuncArtifact,
    input as unknown as Record<string, unknown>,
    runtimeConfig,
    _projectDefaults,
  );
}
