# Generated by aifn - do not edit manually.

mock_data = {
    "cases": [
        {
            "description": "Rewrite casual text into formal style.",
            "id": "formal-rewrite",
            "output": {
                "rewritten": "We would like to inform you that the project has been completed ahead of schedule. Please review the deliverables at your earliest convenience.",
            },
        },
    ],
    "delay": {
        "maxMs": 120,
        "minMs": 30,
    },
    "random": {
        "enabled": False,
        "seed": "rewrite",
    },
    "version": "1.0.0",
}
