// Generated by aifn -- do not edit manually.
// Package: rewrite v1.0.0

import { execute } from '../_engine/typescript/v0.1.0/index';
import type { AIFuncArtifact, AIFuncConfig } from '../_engine/typescript/v0.1.0/index';
import artifact from './rewrite.aifunc';
import mockData from './rewrite.mock';
import type { RewriteInput, RewriteOutput } from './rewrite.types';

export type { AIFuncConfig, RewriteInput, RewriteOutput };

/** Rewrite text according to a specified style or instruction while preserving the original meaning. */
export async function rewrite(config: AIFuncConfig = { mock: true }, input: RewriteInput): Promise<RewriteOutput> {
  const runtimeConfig: AIFuncConfig = config.mock && !config.mockData
    ? { ...config, mockData }
    : config;

  return execute<RewriteOutput>(
    artifact as AIFuncArtifact,
    input as unknown as Record<string, unknown>,
    runtimeConfig,
  );
}
