// Generated by aifn — do not edit manually.
// Package: detect-language v1.0.0

package aifunc.detect_language;

import aifunc.AIFuncConfig;
import aifunc._engine.java.v0_1_0.Runtime;
import aifunc._engine.java.v0_1_0.Artifact;
import aifunc._engine.java.v0_1_0.Types.AIFuncArtifact;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

/** Detect the language of input text, returning a language code, language name, and confidence score. */
/** Generated by aifn — do not edit manually. */
public final class DetectLanguage {

	private DetectLanguage() {}

	private static final Object MOCK_DATA = DetectLanguageAifuncMock.MOCK_DATA;

	public static CompletableFuture<DetectLanguageTypes.DetectLanguageOutput> detectLanguage(AIFuncConfig config, DetectLanguageTypes.DetectLanguageInput input) {
		if (config == null) {
			config = AIFuncConfig.builder().mock(true).mockData(MOCK_DATA).build();
		} else if (config.isMock() && config.getMockData() == null) {
			config = config.toBuilder().mockData(MOCK_DATA).build();
		}


		AIFuncArtifact artifact = Artifact.fromMap(DetectLanguageAifunc.ARTIFACT_DATA);
		Map<String, Object> inputMap = inputToMap(input);
		return Runtime.executeAsync(artifact, inputMap, config)
			.thenApply(DetectLanguage::mapToOutput);
	}

	private static Map<String, Object> inputToMap(DetectLanguageTypes.DetectLanguageInput input) {
		Map<String, Object> m = new LinkedHashMap<>();
		m.put("text", input.getText());
		return m;
	}

	private static DetectLanguageTypes.DetectLanguageOutput mapToOutput(Map<String, Object> m) {
		Double confidence = m.containsKey("confidence") ? (m.get("confidence") instanceof Number) ? ((Number) m.get("confidence")).doubleValue() : null : null;
		String language = m.containsKey("language") ? (m.get("language") instanceof String) ? (String) m.get("language") : String.valueOf(m.get("language")) : null;
		String languageName = m.containsKey("languageName") ? (m.get("languageName") instanceof String) ? (String) m.get("languageName") : String.valueOf(m.get("languageName")) : null;
		return new DetectLanguageTypes.DetectLanguageOutput(confidence, language, languageName);
	}
}
