// Generated by aifn — do not edit manually.
// Package: detect-language v1.0.0

package aifunc.detect_language;

import java.util.List;
import java.util.Map;

/** Generated by aifn — do not edit manually. */
@SuppressWarnings("serial")
final class DetectLanguageAifuncMock {

	private DetectLanguageAifuncMock() {}

	static final Object MOCK_DATA =
		new java.util.LinkedHashMap<String, Object>() {{
			put("cases", new java.util.ArrayList<Object>(java.util.Arrays.asList(
				new java.util.LinkedHashMap<String, Object>() {{
					put("description", "English text detection.");
					put("id", "english-text");
					put("output", new java.util.LinkedHashMap<String, Object>() {{
						put("confidence", 0.98);
						put("language", "en");
						put("languageName", "English");
					}});
				}}
			)));
			put("delay", new java.util.LinkedHashMap<String, Object>() {{
				put("maxMs", 80L);
				put("minMs", 20L);
			}});
			put("random", new java.util.LinkedHashMap<String, Object>() {{
				put("enabled", false);
				put("seed", "detect-language");
			}});
			put("version", "1.0.0");
		}};
}
