// Generated by aifn — do not edit manually.
// Package: translate-stream v1.0.0

namespace Aifunc.TranslateStream;

using System.Collections.Generic;

public static class TranslateStreamTypes
{
	public sealed class TranslateStreamInput
	{
		/// <summary>The text or document to translate.</summary>
		public string Text { get; }
		/// <summary>Target language (e.g. 'Chinese', 'English', 'French', 'zh-CN').</summary>
		public string TargetLang { get; }
		/// <summary>Subject domain hint to improve terminology accuracy (e.g. 'legal', 'medical', 'technical', 'literary'). Optional.</summary>
		public string? Domain { get; set; }
		/// <summary>Source language. If omitted, it is auto-detected.</summary>
		public string? SourceLang { get; set; }
		/// <summary>Translation style: 'literal' (close to source), 'natural' (idiomatic), 'formal'. Default: 'natural'.</summary>
		public string? Style { get; set; }

		public TranslateStreamInput(string text, string targetLang, string? domain = null, string? sourceLang = null, string? style = null)
		{
			Text = text;
			TargetLang = targetLang;
			Domain = domain;
			SourceLang = sourceLang;
			Style = style;
		}
	}
}
