// Copyright 2026 GildenEye
// SPDX-License-Identifier: Apache-2.0

package typescript

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"aifunc/cli/internal/types"
)

// Generate writes index.ts, <name>.types.ts, and <name>.aifunc.ts for the given compiled artifact into outputDir.
// engineVersion is the resolved engine version string, e.g. "0.1.0".
func Generate(artifact *types.CompiledArtifact, outputDir string, hasMock bool, engineVersion string, cfg types.AifuncConfig) error {
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	fileBase := sanitizeFileName(artifact.Package.Name)

	typesContent, err := generateTypes(artifact)
	if err != nil {
		return fmt.Errorf("generate %s.types.ts: %w", fileBase, err)
	}
	if err := os.WriteFile(filepath.Join(outputDir, fileBase+".types.ts"), []byte(typesContent), 0644); err != nil {
		return fmt.Errorf("write %s.types.ts: %w", fileBase, err)
	}

	artifactContent, err := generateArtifactModule(artifact)
	if err != nil {
		return fmt.Errorf("generate %s.aifunc.ts: %w", fileBase, err)
	}
	if err := os.WriteFile(filepath.Join(outputDir, fileBase+".aifunc.ts"), []byte(artifactContent), 0644); err != nil {
		return fmt.Errorf("write %s.aifunc.ts: %w", fileBase, err)
	}

	indexContent, err := generateIndex(artifact, hasMock, engineVersion, cfg)
	if err != nil {
		return fmt.Errorf("generate index.ts: %w", err)
	}
	if err := os.WriteFile(filepath.Join(outputDir, "index.ts"), []byte(indexContent), 0644); err != nil {
		return fmt.Errorf("write index.ts: %w", err)
	}

	return nil
}

// generateTypes produces the <name>.types.ts file with strongly-typed input/output interfaces.
func generateTypes(artifact *types.CompiledArtifact) (string, error) {
	var b strings.Builder

	b.WriteString("// Generated by aifn -- do not edit manually.\n")
	b.WriteString(fmt.Sprintf("// Package: %s v%s\n\n", artifact.Package.Name, artifact.Package.Version))

	inputName := toPascalCase(artifact.API.Name) + "Input"
	outputName := toPascalCase(artifact.API.Name) + "Output"

	inputFields, err := schemaToTSFields(artifact.API.Input, 0)
	if err != nil {
		return "", fmt.Errorf("input schema: %w", err)
	}
	var outputFields string
	if !outputIsStream(artifact.API.Output) {
		outputFields, err = schemaToTSFields(artifact.API.Output, 0)
		if err != nil {
			return "", fmt.Errorf("output schema: %w", err)
		}
	}

	b.WriteString(fmt.Sprintf("export interface %s {\n", inputName))
	b.WriteString(inputFields)
	b.WriteString("}\n\n")

	if outputIsStream(artifact.API.Output) {
		b.WriteString(fmt.Sprintf("export type %s = string;\n", outputName))
	} else {
		b.WriteString(fmt.Sprintf("export interface %s {\n", outputName))
		b.WriteString(outputFields)
		b.WriteString("}\n")
	}

	return b.String(), nil
}

// generateIndex produces the index.ts file with the callable function.
func generateIndex(artifact *types.CompiledArtifact, hasMock bool, engineVersion string, cfg types.AifuncConfig) (string, error) {
	var b strings.Builder

	fileBase := sanitizeFileName(artifact.Package.Name)
	funcName := toCalmelCase(artifact.API.Name)
	inputName := toPascalCase(artifact.API.Name) + "Input"
	outputName := toPascalCase(artifact.API.Name) + "Output"
	isStream := outputIsStream(artifact.API.Output)

	b.WriteString("// Generated by aifn -- do not edit manually.\n")
	b.WriteString(fmt.Sprintf("// Package: %s v%s\n\n", artifact.Package.Name, artifact.Package.Version))
	if isStream {
		b.WriteString(fmt.Sprintf("import { executeStream } from '../_engine/typescript/v%s/index';\n", engineVersion))
	} else {
		b.WriteString(fmt.Sprintf("import { execute } from '../_engine/typescript/v%s/index';\n", engineVersion))
	}
	b.WriteString(fmt.Sprintf("import type { AIFuncArtifact, AIFuncConfig } from '../_engine/typescript/v%s/index';\n", engineVersion))
	b.WriteString(fmt.Sprintf("import artifact from './%s.aifunc';\n", fileBase))
	if hasMock {
		b.WriteString(fmt.Sprintf("import mockData from './%s.mock';\n", fileBase))
	}
	b.WriteString(fmt.Sprintf("import type { %s, %s } from './%s.types';\n\n", inputName, outputName, fileBase))
	b.WriteString(fmt.Sprintf("export type { AIFuncConfig, %s, %s };\n\n", inputName, outputName))

	b.WriteString(fmt.Sprintf("/** %s */\n", artifact.API.Description))

	if isStream {
		b.WriteString(fmt.Sprintf(
			"export async function* %s(config: AIFuncConfig = %s, input: %s): AsyncIterable<%s> {\n",
			funcName, defaultConfigLiteral(hasMock), inputName, outputName,
		))
	} else {
		b.WriteString(fmt.Sprintf(
			"export async function %s(config: AIFuncConfig = %s, input: %s): Promise<%s> {\n",
			funcName, defaultConfigLiteral(hasMock), inputName, outputName,
		))
	}

	// Inject projectDefaults from aifunc.json (build-time injection)
	projectDefaultsLiteral := buildProjectDefaultsLiteral(cfg)
	b.WriteString(fmt.Sprintf("  const _projectDefaults = %s;\n\n", projectDefaultsLiteral))

	if hasMock {
		b.WriteString("  const runtimeConfig: AIFuncConfig = config.mock && !config.mockData\n")
		b.WriteString("    ? { ...config, mockData }\n")
		b.WriteString("    : config;\n\n")
	} else {
		b.WriteString("  const runtimeConfig: AIFuncConfig = config;\n\n")
	}

	if isStream {
		b.WriteString("  yield* executeStream(\n")
	} else {
		b.WriteString("  return execute<")
		b.WriteString(outputName)
		b.WriteString(">(\n")
	}
	b.WriteString("    artifact as AIFuncArtifact,\n")
	b.WriteString("    input as unknown as Record<string, unknown>,\n")
	b.WriteString("    runtimeConfig,\n")
	b.WriteString("    _projectDefaults,\n")
	b.WriteString("  );\n")
	b.WriteString("}\n")


	return b.String(), nil
}

func defaultConfigLiteral(hasMock bool) string {
	if hasMock {
		return "{ mock: true }"
	}
	return "{}"
}

func generateArtifactModule(artifact *types.CompiledArtifact) (string, error) {
	data, err := json.MarshalIndent(artifact, "", "  ")
	if err != nil {
		return "", fmt.Errorf("marshal artifact: %w", err)
	}

	var b strings.Builder
	b.WriteString("const artifact = ")
	b.Write(data)
	b.WriteString(";\n\n")
	b.WriteString("export default artifact;\n")
	return b.String(), nil
}

// schemaToTSFields converts a JSON Schema object's properties into TypeScript interface fields.
func schemaToTSFields(schema map[string]any, depth int) (string, error) {
	if schema == nil {
		return "", nil
	}

	schemaType, _ := schema["type"].(string)
	if schemaType != "object" {
		return "", nil
	}

	props, _ := schema["properties"].(map[string]any)
	required := requiredSet(schema)
	indent := strings.Repeat("  ", depth+1)

	keys := make([]string, 0, len(props))
	for key := range props {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	var b strings.Builder
	for _, key := range keys {
		val := props[key]
		prop, ok := val.(map[string]any)
		if !ok {
			continue
		}
		desc, _ := prop["description"].(string)
		if desc != "" {
			b.WriteString(fmt.Sprintf("%s/** %s */\n", indent, desc))
		}
		optional := ""
		if _, isRequired := required[key]; !isRequired {
			optional = "?"
		}
		tsType := jsonSchemaToTSType(prop)
		b.WriteString(fmt.Sprintf("%s%s%s: %s;\n", indent, key, optional, tsType))
	}
	return b.String(), nil
}

func requiredSet(schema map[string]any) map[string]struct{} {
	set := make(map[string]struct{})
	arr, _ := schema["required"].([]any)
	for _, v := range arr {
		if s, ok := v.(string); ok {
			set[s] = struct{}{}
		}
	}
	return set
}

// jsonSchemaToTSType maps a JSON Schema property definition to a TypeScript type string.
func jsonSchemaToTSType(prop map[string]any) string {
	return jsonSchemaToTSTypeIndent(prop, 1)
}

func jsonSchemaToTSTypeIndent(prop map[string]any, depth int) string {
	t, _ := prop["type"].(string)
	format, _ := prop["format"].(string)

	switch t {
	case "string":
		if enumVals, ok := prop["enum"].([]any); ok {
			parts := make([]string, 0, len(enumVals))
			for _, v := range enumVals {
				parts = append(parts, fmt.Sprintf("%q", v))
			}
			return strings.Join(parts, " | ")
		}
		return "string"
	case "boolean":
		return "boolean"
	case "integer", "number":
		_ = format
		return "number"
	case "array":
		items, ok := prop["items"].(map[string]any)
		if !ok {
			return "unknown[]"
		}
		return jsonSchemaToTSTypeIndent(items, depth) + "[]"
	case "object":
		return objectToInlineTS(prop, depth)
	case "stream-string":
		return "string"
	default:
		return "unknown"
	}
}

// objectToInlineTS generates an inline TypeScript object type if properties are defined,
// otherwise falls back to Record<string, unknown>.
func objectToInlineTS(prop map[string]any, depth int) string {
	props, ok := prop["properties"].(map[string]any)
	if !ok || len(props) == 0 {
		return "Record<string, unknown>"
	}

	required := requiredSet(prop)
	indent := strings.Repeat("  ", depth)
	innerIndent := strings.Repeat("  ", depth+1)

	keys := make([]string, 0, len(props))
	for key := range props {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("{\n")
	for _, key := range keys {
		val := props[key]
		p, ok := val.(map[string]any)
		if !ok {
			continue
		}
		optional := ""
		if _, isRequired := required[key]; !isRequired {
			optional = "?"
		}
		tsType := jsonSchemaToTSTypeIndent(p, depth+1)
		b.WriteString(fmt.Sprintf("%s%s%s: %s;\n", innerIndent, key, optional, tsType))
	}
	b.WriteString(indent + "}")
	return b.String()
}

// outputIsStream returns true when the output schema declares streaming delivery.
// Supports two conventions:
//   - New spec: output root has "x-delivery-mode": "stream"
//   - Legacy:   any top-level output property has a type prefixed with "stream-"
func outputIsStream(schema map[string]any) bool {
	if mode, _ := schema["x-delivery-mode"].(string); mode == "stream" {
		return true
	}
	props, _ := schema["properties"].(map[string]any)
	for _, v := range props {
		prop, ok := v.(map[string]any)
		if !ok {
			continue
		}
		t, _ := prop["type"].(string)
		if strings.HasPrefix(t, "stream-") {
			return true
		}
	}
	return false
}

// toPascalCase converts snake_case or kebab-case identifiers to PascalCase.
func toPascalCase(s string) string {
	parts := splitIdentifier(s)
	var b strings.Builder
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}

// toCalmelCase converts snake_case or kebab-case identifiers to camelCase.
func toCalmelCase(s string) string {
	parts := splitIdentifier(s)
	var b strings.Builder
	for i, p := range parts {
		if len(p) == 0 {
			continue
		}
		if i == 0 {
			b.WriteString(strings.ToLower(p))
		} else {
			b.WriteString(strings.ToUpper(p[:1]) + p[1:])
		}
	}
	return b.String()
}

func sanitizeFileName(name string) string {
	name = strings.TrimPrefix(name, "@")
	name = strings.ReplaceAll(name, "/", "__")
	return name
}

func splitIdentifier(s string) []string {
	s = strings.ReplaceAll(s, "-", "_")
	return strings.Split(s, "_")
}

func buildProjectDefaultsLiteral(cfg types.AifuncConfig) string {
	var parts []string
	if cfg.Timeout != nil {
		parts = append(parts, fmt.Sprintf("timeout: %d", *cfg.Timeout))
	}
	if cfg.MaxRetries != nil {
		parts = append(parts, fmt.Sprintf("maxRetries: %d", *cfg.MaxRetries))
	}
	if len(parts) == 0 {
		return "{}"
	}
	return "{ " + strings.Join(parts, ", ") + " }"
}
